### ISSUE TITLE
Rollup Angular 2 final 2.0.1 project encounter errors seems related to umd

### ISSUE THREAD

**Issue by sunshineo** [rollup/rollup#1026]
The error I got is:
```
Module /Users/gordon/workspace/CraigsMenu/web/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js does not export platformBrowserDynamic (imported by /Users/gordon/workspace/CraigsMenu/web/dist/main.js)
Error: Module /Users/gordon/workspace/CraigsMenu/web/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js does not export platformBrowserDynamic (imported by /Users/gordon/workspace/CraigsMenu/web/dist/main.js)
    at Module.trace (/Users/gordon/workspace/CraigsMenu/web/node_modules/rollup/src/Module.js:666:30)
    at /Users/gordon/workspace/CraigsMenu/web/node_modules/rollup/src/Module.js:264:30
    at Array.forEach (native)
    at /Users/gordon/workspace/CraigsMenu/web/node_modules/rollup/src/Module.js:262:25
    at Array.forEach (native)
    at Module.bindReferences (/Users/gordon/workspace/CraigsMenu/web/node_modules/rollup/src/Module.js:255:19)
    at /Users/gordon/workspace/CraigsMenu/web/node_modules/rollup/src/Bundle.js:96:44
    at Array.forEach (native)
    at /Users/gordon/workspace/CraigsMenu/web/node_modules/rollup/src/Bundle.js:96:18
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

I have first built my project int ES6/ES2015 modules under dist folder and the command I used to roll up is:
```
rollup -f iife -c -o dist/bundle.es2015.js
```

**Comment by sunshineo** [comment]
Sorry, I think I just needed to update the rollup-plugin-node-resolve plugin version
