### ISSUE TITLE
 Unexpected character '@ rollup@0.36.1

### ISSUE THREAD

**Issue by tmvnk** [rollup/rollup#1030]
[16:38:20]  bundle dev failed:  Unexpected character '@' (8:0) in /Users/Tom/dev/MyApp/src/pages/login/login.js

[16:38:20]  SyntaxError: Unexpected character '@' (8:0) in /Users/Tom/dev/MyApp/src/pages/login/login.js
    at Parser.pp$4.raise (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4070:13)
    at Parser.pp$7.getTokenFromCode (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4609:8)
    at Parser.pp$7.readToken (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4330:15)
    at Parser.pp$7.nextToken (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4321:13)
    at Parser.pp$7.next (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:4266:8)
    at Parser.pp.eat (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2200:10)
    at Parser.pp.semicolon (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2245:13)
    at Parser.pp$1.parseImport (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2996:8)
    at Parser.pp$1.parseStatement (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2409:44)
    at Parser.pp$1.parseTopLevel (/Users/Tom/dev/MyApp/node_modules/rollup/dist/rollup.js:2313:23)

{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": true,
  "atom": {
    "rewriteTsconfig": false
  }
}

**Comment by AgronKabashi** [comment]
Are you using decorators/Angular 2? Might want to look into the following babel-plugins:

* angular2-annotations
* transform-decorators-legacy
* transform-class-properties
* transform-flow-strip-types

Either pass them directly into rollup-plugin-babel or create a .babelrc file.

**Comment by Rich-Harris** [comment]
I'm going to close this issue as there's no information with which to reproduce it. Please follow [the instructions you saw](https://raw.githubusercontent.com/rollup/rollup/master/.github/ISSUE_TEMPLATE.md) when you opened the issue.
