### ISSUE TITLE
illegal reassignment with undeclared variable

### ISSUE THREAD

**Issue by whtevn** [rollup/rollup#1041]
Hello, I'm having some trouble getting aws-sdk into an ionic v2 app, with typescript, and at the end of the line it seems like rollup (v 0.36.1) is the one ultimately throwing an error. I have not been able to reproduce the issue on rollup's site, but any direction that can be given would be appreciated.

I can import the package, but any time I try to use it, even to log out the resulting variable, I receive the following error (full text at the end of this report)

```
[16:26:26]  Error: Illegal reassignment to import 'process'
```

which I have come to understand means that something is trying to left-side assign the node reserved variable `process`. The code I am using to produce this error is

```
import AWS from 'aws-sdk';
console.log(AWS);
```

and it is specifically the `console.log(AWS)` that is demonstrating the issue, which occurs even when the code is as follows

```
import AWS from 'aws-sdk';
AWS;
```

however, I grepped the aws-sdk package and found a line in `lib/browser_loader.js` which contained `process = ...`, and when removed the rollup error disappears. The lines I removed from the package were 

```
if (typeof process === 'undefined') {
  process = {
    browser: true
  };
}
```

it is worth noting that `process` is never defined with a `var` keyword in that file. If I add the `var` in before `process`, the build error goes away. Unfortunately that produces an application error that I have not been able to track down, but is irrelevant to this issue. 

apologies for this disjointed error description. I tried to recreate it by making samples on the site with the `process` variable, but it did not seem to be an issue on the site. Please let me know if there is any additional information I can provide. I have also tried this with and without a aws-sdk typings definition, but it did not seem to make any difference. 

full text of the error stack:

```
Error: Illegal reassignment to import 'process'
    at error (/Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5404:12)
    at disallowIllegalReassignment (/Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5429:4)
    at AssignmentExpression.bind (/Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5492:3)
    at /Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5149:50
    at ExpressionStatement.eachChild (/Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5166:5)
    at ExpressionStatement.bind (/Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5149:7)
    at BlockStatement.bind (/Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5615:9)
    at /Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5149:50
    at IfStatement.eachChild (/Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5166:5)
    at IfStatement.bind (/Users/evan/Documents/dev/dn/flashtastic-ionic/node_modules/rollup/dist/rollup.js:5149:7)
```

**Comment by whtevn** [comment]
hey, sorry about this, I was able to look a little closer and it is looking like this error is specific to the ionic app scripts package. I made an error report over there. thanks for your time.

**Comment by raphaguasta** [comment]
I'm with the same error @whtevn! How did you fix it?

**Comment by eXist-FraGGer** [comment]
Any solutions?
