### ISSUE TITLE
Cannot overwrite the same content twice: blah blah

### ISSUE THREAD

**Issue by vetik32** [rollup/rollup#105]
I couldn't understand the meaning of this error or how to run properly rollup.
Maybe I do something very wrong.
To reproduce:
(assuming lodash,rollup are globally installed)
```
$ lodash modularize compat include="isTypedArray" exports=es
```
then
```
$  rollup -f iife modularize/lang/isTypedArray.js -n qqq
```

the error :
```
Cannot overwrite the same content twice: ';\n\nvar '
Error: Cannot overwrite the same content twice: ';\n\nvar '
    at MagicString.overwrite (/home/zzz/.npm-packages/lib/node_modules/rollup/node_modules/magic-string/dist/magic-string.js:521:11)
    at /home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:1568:17
    at Array.forEach (native)
    at Module.render (/home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:1533:19)
    at /home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:2083:24
    at Array.forEach (native)
    at Bundle.render (/home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:2082:23)
    at Object.generate (/home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:2289:19)
    at /home/zzz/.npm-packages/lib/node_modules/rollup/bin/runRollup.js:72:23
    at lib$es6$promise$$internal$$tryCatch (/home/zzz/.npm-packages/lib/node_modules/rollup/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:331:16)
```

**Comment by vetik32** [comment]
test_bad.js :
```js

var a,
    b,
    c;

var d,
    e,
    f;
```

test_good.js: 
```js

var a,
    b,
    c,
    d,
    e,
    f;
```

```
$ rollup test_good.js
var a;
var b;
var c;
var d;
var e;
var f;

```

```
$ rollup test_bad.js
Cannot overwrite the same content twice: ';\n\nvar '
Error: Cannot overwrite the same content twice: ';\n\nvar '
    at MagicString.overwrite (/home/zzz/.npm-packages/lib/node_modules/rollup/node_modules/magic-string/dist/magic-string.js:521:11)
    at /home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:1568:17
    at Array.forEach (native)
    at Module.render (/home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:1533:19)
    at /home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:2083:24
    at Array.forEach (native)
    at Bundle.render (/home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:2082:23)
    at Object.generate (/home/zzz/.npm-packages/lib/node_modules/rollup/dist/rollup.js:2289:19)
    at /home/zzz/.npm-packages/lib/node_modules/rollup/bin/runRollup.js:72:23
    at lib$es6$promise$$internal$$tryCatch (/home/zzz/.npm-packages/lib/node_modules/rollup/node_modules/sander/node_modules/es6-promise/dist/es6-promise.js:331:16)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

**Comment by Rich-Harris** [comment]
Thanks, and sorry this took a while – the fix will be in the next release

**Comment by vetik32** [comment]
thank you.
