### ISSUE TITLE
commonjs module that exports `default`

### ISSUE THREAD

**Issue by travi** [rollup/rollup#1135]
I'm hoping that there is already a configuration that I have overlooked for this situation, but any thoughts would be helpful, either way. I'm using [joi](https://github.com/hapijs/joi) to [validate the schema of the options](https://github.com/GainCompliance/hapi-auth-stormpath/blob/949ca2c4631e5e2d6fe55862ab88a19800cb4f30/src/scheme.js#L7-L12) passed to a hapi authentication scheme.

[My rollup config](https://github.com/GainCompliance/hapi-auth-stormpath/blob/949ca2c4631e5e2d6fe55862ab88a19800cb4f30/rollup.config.js) is pretty simple and `joi` is treated as an external as I expect. However, in the common-js bundle, the `_interopDefault` is causing a problem because `joi` exports an [instance of a class](https://github.com/hapijs/joi/blob/abfe727885af779a676e6a205ee15cdc8b435691/lib/index.js#L29) that has a [`default` method](https://github.com/hapijs/joi/blob/abfe727885af779a676e6a205ee15cdc8b435691/lib/any.js#L319). My assumption is that this is causing `_interopDefault` to assume that `joi` is an es6 module, which it is not.

<details>
  <summary>Stack trace</summary>

```
/Users/travi/development/gain/front-end/reference-client/node_modules/@gaincompliance/hapi-auth-stormpath/lib/plugin.cjs.js:14
    applicationHref: joi.string().uri().required(),
                         ^

TypeError: joi.string is not a function
    at validate (/Users/travi/development/gain/front-end/reference-client/node_modules/@gaincompliance/hapi-auth-stormpath/lib/plugin.cjs.js:14:26)
    at Object.scheme [as stormpath] (/Users/travi/development/gain/front-end/reference-client/node_modules/@gaincompliance/hapi-auth-stormpath/lib/plugin.cjs.js:26:18)
    at module.exports.internals.Auth.internals.Auth.strategy (/Users/travi/development/gain/front-end/reference-client/node_modules/hapi/lib/auth.js:51:43)
    at module.exports.internals.Plugin.internals.Plugin._applyChild (/Users/travi/development/gain/front-end/reference-client/node_modules/hapi/lib/plugin.js:600:19)
    at Object.strategy (/Users/travi/development/gain/front-end/reference-client/node_modules/hapi/lib/plugin.js:64:54)
    at Object.register (/Users/travi/development/gain/front-end/reference-client/lib/server/auth/strategies.js:9:15)
    at Object.target [as register] (/Users/travi/development/gain/front-end/reference-client/node_modules/hapi/node_modules/joi/lib/object.js:77:34)
    at each (/Users/travi/development/gain/front-end/reference-client/node_modules/hapi/lib/plugin.js:318:14)
    at iterate (/Users/travi/development/gain/front-end/reference-client/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/Users/travi/development/gain/front-end/reference-client/node_modules/hapi/node_modules/items/lib/index.js:39:9)
```
</details>

If I remove the `_interopDefault`, the code executes correctly. Is there a way to mark `joi` as common-js (without vendoring it into the bundle) so that the `_interopDefault` doesn't result in this behavior?

**Comment by Victorystick** [comment]
I think the implementation of `_interopDefault` should be changed to support this use case. In the mean time, can you import `joi` as a namespace instead?
```js
import * as joi from 'joi';
```

**Comment by travi** [comment]
sorry for the delay, but your suggested import technique did seem to solve the problem. i'm disappointed that i did not try that solution myself, but it didn't dawn on me because i was so focused on why my tests (using babel) were working, but the node consumer couldn't consume the build bundle.

i'm glad that you think this is a big enough to resolve it because it is one that a maintainer of a package may not even realize until someone downstream reports it. luckily, i was the first consumer of this module, so i found it quickly.

**Comment by Rich-Harris** [comment]
I'm not sure it's possible to have an implementation of `interopDefault` that supports this scenario. We could check for `mod.__esModule` instead of `mod.default` but I've seen that blow up as well. Honestly, I think the best move here would be for `joi` to not have an export named `default`, because it's bound to cause these sorts of problems.

**Comment by Rich-Harris** [comment]
Closing this issue as using namespace imports works for this case, and there isn't a way that we can fix it that wouldn't break other code anyway

**Comment by ljharb** [comment]
When has checking for `mod.__esModule` blown up? (given that that's how babel does it for every babel-transpiled package on npm)

**Comment by such** [comment]
@Rich-Harris:
I'm having the same issue described here with [qs](https://github.com/ljharb/qs).
As you can see they're rejecting my [PR](https://github.com/ljharb/qs/pull/229). What's your take on this one?
Thanks!
