### ISSUE TITLE
node 7.0.0 Error: Cannot find module 'babel-runtime'

### ISSUE THREAD

**Issue by lzxb** [rollup/rollup#1141]
#### rollup.config.js
```javascript
const rollup = require('rollup')
const babel = require('rollup-plugin-babel')


rollup
    .rollup({
        entry: 'src/index.js',
        plugins: [
            babel()
        ]
    })
    .then(function (bundle) {
        bundle.write({
            format: 'es',
            dest: 'dist/vue-router-history.js'
        })
    })
```
#### package.json
```JSON
{
  "scripts": {
    "build": "node rollup.config.js"
  },
  "devDependencies": {
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015-rollup": "^1.2.0",
    "rollup": "^0.36.4",
    "rollup-plugin-babel": "^2.6.1"
  }
}

```
#### .babelrc
```JSON
{
    "presets": [
        "es2015-rollup"
    ]
}
```

```
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.requireRelative.resolve (/Users/lzxb/Documents/vue-router-history/node_modules/require-relative/index.j
s:30:17)
    at resolve (/Users/lzxb/Documents/vue-router-history/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/Users/lzxb/Documents/vue-router-history/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /Users/lzxb/Documents/vue-router-history/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/Users/lzxb/Documents/vue-router-history/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/Users/lzxb/Documents/vue-router-history/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/Users/lzxb/Documents/vue-router-history/node_modules/babel-preset-es2015-rollup/index.js:3:
18)
    at Module._compile (module.js:573:32) code: 'MODULE_NOT_FOUND' } babel-runtime
```

**Comment by roastlechon** [comment]
I have this issue too

**Comment by roastlechon** [comment]
This is related to https://github.com/rollup/babel-preset-es2015-rollup/issues/18 it looks like.

@lzxb do you have babel-preset-es2015-rollup?

**Comment by lzxb** [comment]
"babel-preset-es2015-rollup": "^1.2.0",

**Comment by lzxb** [comment]
ok , Problem has been solved
