### ISSUE TITLE
with react  has a problem

### ISSUE THREAD

**Issue by 1233443** [rollup/rollup#1160]
ReactCurrentOwner.js:1 Warning: Exception thrown by hook while handling onBeforeMountComponent: ReferenceError: validateProperty is not defined
ReferenceError: validateProperty is not defined
    at warnUnknownProperties (http://localhost/work/demo/rollup/build/js/main.min.js:18705:19)
    at handleElement (http://localhost/work/demo/rollup/build/js/main.min.js:18729:3)
    at Object.onBeforeMountComponent (http://localhost/work/demo/rollup/build/js/main.min.js:18734:5)
    at callHook (http://localhost/work/demo/rollup/build/js/main.min.js:6493:8)
    at emitEvent (http://localhost/work/demo/rollup/build/js/main.min.js:6505:7)
    at Object.onBeforeMountComponent (http://localhost/work/demo/rollup/build/js/main.min.js:6782:5)
    at Object.mountComponent (http://localhost/work/demo/rollup/build/js/main.min.js:6869:42)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost/work/demo/rollup/build/js/main.min.js:12021:36)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost/work/demo/rollup/build/js/main.min.js:11908:21)
    at Object.mountComponent (http://localhost/work/demo/rollup/build/js/main.min.js:6872:35)

**Comment by Rich-Harris** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)
