### ISSUE TITLE
Got an error when rollup vue2

### ISSUE THREAD

**Issue by g8up** [rollup/rollup#1296]
```
Cannot read property '0' of null
TypeError: Cannot read property '0' of null
    at ExportDefaultDeclaration.render (D:\code\oschina\auto-fetch\node_modules\rollup\src\ast\nodes\ExportDefaultDeclaration.js:56:82)
    at Module.render (D:\code\oschina\auto-fetch\node_modules\rollup\src\Module.js:317:9)
    at D:\code\oschina\auto-fetch\node_modules\rollup\src\Bundle.js:373:26
    at Array.forEach (native)
    at Bundle.render (D:\code\oschina\auto-fetch\node_modules\rollup\src\Bundle.js:372:23)
    at generate (D:\code\oschina\auto-fetch\node_modules\rollup\src\rollup.js:73:28)
    at Object.write (D:\code\oschina\auto-fetch\node_modules\rollup\src\rollup.js:102:20)
    at D:\code\oschina\auto-fetch\node_modules\rollup\bin\rollup:908:18
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
```
```javascript
// rollup.config.js
import babel      from 'rollup-plugin-babel';
import babelrc    from 'babelrc-rollup';
import istanbul   from 'rollup-plugin-istanbul';
import vue        from 'rollup-plugin-vue2';
import css        from 'rollup-plugin-css-only';
import less       from 'rollup-plugin-less';

let pkg = require('./package.json');
let external = Object.keys(pkg.dependencies);
export default {
	entry: 'src/option.js',
	dest: 'dist/option.js',
	plugins: [
		vue(),
		less(),
		css(),
		babel(babelrc()),
		istanbul({
			exclude: ['test/**/*', 'node_modules/**/*']
		}),
	],
	external: external,
};
```
[repo](http://git.oschina.net/g8up/auto-fetch/tree/buildError)

**Comment by kzc** [comment]
You're using:
```
    "rollup": "^0.37.0",
```
which is a few revisions old. Please upgrade all your dependencies and report what happens.

**Comment by g8up** [comment]
thx @kzc .

I followed this project [rollup/rollup-starter-project](https://github.com/rollup/rollup-starter-project/blob/master/package.json#L44) which is the older version.

Now I have updated to the lastest version.
