### ISSUE TITLE
Provide more information for "[name] is not exported by [module]"

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup#1306]
Please improve the error message for https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module to indicate who (file + line number) is attempting the import [name]

Currently, the stack-trace reads:

```
Error: 'default' is not exported by src\Requirements.js
    at error (C:\Users\Gili\Documents\requirements.js\node_modules\rollup\src\utils\error.js:2:14)
    at Module.error$1 [as error] (C:\Users\Gili\Documents\requirements.js\node_modules\rollup\src\Module.js:303:2)
    at Module.traceExport (C:\Users\Gili\Documents\requirements.js\node_modules\rollup\src\Module.js:425:10)
    at C:\Users\Gili\Documents\requirements.js\node_modules\rollup\src\Bundle.js:140:38
    at Array.forEach (native)
    at C:\Users\Gili\Documents\requirements.js\node_modules\rollup\src\Bundle.js:139:30
```

As you can see, I have no way of knowing who is doing the importing. In a large project when I refactored the exporters, I have a very hard time tracking down the broken references on the importer end.

**Comment by Rich-Harris** [comment]
Sorry for the delayed response — this was actually implemented a while back so I'll close this
