### ISSUE TITLE
Exception on bad code

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#140]
I made a mistake making the example for #139 and I got a reference exception from rollup..

Ideally it should be a nicer explanation of what is wrong...

entry.js
```
import a from './foo';

a();
```

foo.js
```
import * as a from './bar';

function b() {
  console.log(a.foo, a.bar);
}

export { b }; // this is wrong, it should be export default b;
```

bar.js
```
function foo() {

}
function bar() {

}
export { foo, bar };
```

The mistake is in foo.js (commented).

I expect a smaller sample could be made, I didn't dig into it.

Exception:

```
TypeError: undefined is not a function
    at c:\dev\grunt-rollup\node_modules\rollup\dist\rollup.js:2019:39
    at Array.forEach (native)
    at Statement.mark (c:\dev\grunt-rollup\node_modules\rollup\dist\rollup.js:2017:24)
    at c:\dev\grunt-rollup\node_modules\rollup\dist\rollup.js:2697:17
    at Array.forEach (native)
    at Module.markAllStatements (c:\dev\grunt-rollup\node_modules\rollup\dist\rollup.js:2670:19)
    at c:\dev\grunt-rollup\node_modules\rollup\dist\rollup.js:3257:16
    at lib$es6$promise$$internal$$tryCatch (c:\dev\grunt-rollup\node_modules\es6-promise\dist\es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (c:\dev\grunt-rollup\node_modules\es6-promise\dist\es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (c:\dev\grunt-rollup\node_modules\es6-promise\dist\es6-promise.js:314:11)
```

version = latest (0.16.3 )

**Comment by Victorystick** [comment]
I can reproduce this and I know what's causing it. I'm looking at how best to address it.
