### ISSUE TITLE
on syntax error, report the file it occurred in

### ISSUE THREAD

**Issue by lukeapage** [rollup/rollup#143]
I had a syntax error somewhere and just got this...
```
SyntaxError: Unexpected token (1:18)
    at Parser.pp.raise (c:\git\less.js\node_modules\acorn\dist\acorn.js:975:13)
    at Parser.pp.unexpected (c:\git\less.js\node_modules\acorn\dist\acorn.js:1523:8)
    at Parser.pp.semicolon (c:\git\less.js\node_modules\acorn\dist\acorn.js:1502:73)
    at Parser.pp.parseExport (c:\git\less.js\node_modules\acorn\dist\acorn.js:2155:25)
    at Parser.pp.parseStatement (c:\git\less.js\node_modules\acorn\dist\acorn.js:1732:85)
    at Parser.pp.parseTopLevel (c:\git\less.js\node_modules\acorn\dist\acorn.js:1657:21)
    at Parser.parse (c:\git\less.js\node_modules\acorn\dist\acorn.js:1627:17)
    at Object.parse (c:\git\less.js\node_modules\acorn\dist\acorn.js:937:44)
    at Module.parse (c:\git\less.js\node_modules\rollup\dist\rollup.js:2724:17)
    at new Module (c:\git\less.js\node_modules\rollup\dist\rollup.js:2298:26)
```

**Comment by Victorystick** [comment]
This would be nice. Perhaps even point out the error?
```
1. import { foo ] from 'foo';
                ^
SyntaxError: Unexpected token (1:14)
    ...
```

**Comment by Rich-Harris** [comment]
+1. Ideally the error object would have the location data in a structured form as well, so that other tooling can use it intelligently (e.g. [Gobble](https://github.com/gobblejs/gobble) uses the line/column/file info to produce a readable error log and trace sourcemaps where possible).

**Comment by Victorystick** [comment]
I'm really starting to warm up to Gobble. Astonishing! :astonished:

**Comment by Rich-Harris** [comment]
Fixed in both master and contingency-plan – turns out most of the location info is already present on the object, we just need to add the module ID to the error message

**Comment by yairEO** [comment]
So how do I get it to show errors? what configuration do I need to use for Rollup? 

Wiki doesn't mention anything regarding error handling btw.
