### ISSUE TITLE
Error quality down?

### ISSUE THREAD

**Issue by talmobi** [rollup/rollup#1433]
Error quality has diminished?

version 0.39.0

```bash
$ npm run build:js -s
Error transforming /Users/mollie/work/solar-marketing-site/scripts/app-contact-form.js with 'buble' plugin: Unexpected token (114:58)
SyntaxError: Error transforming /Users/mollie/work/solar-marketing-site/scripts/app-contact-form.js with 'buble' plugin: Unexpected token (114:58)
110 :         )
111 :       ),
112 :       html('.app-solar-contact-form-checkbox__text', opts.text || '')
113 :     ),
114 :     _input = SolarContactFormInput({ type: 'businessId' }):
                                                                ^
    at Parser.pp$4.raise (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$3.parseExprList (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:2152:16)
    at Parser.pp$3.parseSubscripts (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/mollie/work/solar-marketing-site/node_modules/acorn/dist/acorn.js:1597:21)
```

```bash
$ npm run build:js 2>&1 -s | wooster

 >> wooster output <<
 SyntaxError: Error transforming ./s/app-contact-form.js with 'buble' plugin: Unexpected token (114:58)

 @ ./scripts/app-contact-form.js 114:58
  110 |         )
  111 |       ),
  112 |       html('.app-solar-contact-form-checkbox__text', opts.text
  113 |     ),
> 114 |     _input = SolarContactFormInput({ type: 'businessId' }):
      |                                                           ^
  115 |   )
```

version 0.40.0

```bash
$ npm run build:js -s
🚨   Error transforming scripts/app-contact-form.js with 'buble' plugin: Unexpected token (114:58)
```

still barely parsable by wooster though

```bash
$ npm run build:js 2>&1 -s | wooster

 >> wooster output <<
 Error: Error transforming ./s/app-contact-form.js with 'buble' plugin: Unexpected token (114:58)

 @ ./scripts/app-contact-form.js 114:58
  110 |         )
  111 |       ),
  112 |       html('.app-solar-contact-form-checkbox__text', opts.text
  113 |     ),
> 114 |     _input = SolarContactFormInput({ type: 'businessId' }):
      |                                                           ^
  115 |   )
```

version 0.41.00

```bash
$ npm run build:js 2>&1 -s
🚨   (buble plugin) Unexpected token (114:58)
undefined (114:58)
```

Critical information missing (source filename), not parsable by wooster

```bash
$ npm run build:js 2>&1 -s | wooster
🚨   (buble plugin) Unexpected token (114:58)
undefined (114:58)
```

Also version 0.40.0+ describes errors as PLUGIN_ERROR instead of SyntaxError as in version 0.39.0

```bash
``` PLUGIN_ERROR (114:58)
 109|         })
 110|       )
 111|     ),
 112|     html(".app-solar-contact-form-checkbox__text", opts.text || "")
 113|   ),
 114|   _input = SolarContactFormInput({ type: "businessId" }):
--------------------------------------------------------------^
 115| )
 116|
 117| function update (checked) {

PLUGIN_ERROR: Unexpected token (114:58)
    at error ([app-contact-form.js]
url: /Users/mollie/work/solar-marketing-site/scripts/app-contact-form.js
```

```bash
``` SyntaxError (114:58)
 109|         })
 110|       )
 111|     ),
 112|     html(".app-solar-contact-form-checkbox__text", opts.text || "")
 113|   ),
 114|   _input = SolarContactFormInput({ type: "businessId" }):
--------------------------------------------------------------^
 115| )
 116|
 117| function update (checked) {

SyntaxError: Error transforming [app-contact-form.js]
url: /Users/mollie/work/solar-marketing-site/scripts/app-contact-form.js
```

Any thoughts on this?

**Comment by talmobi** [comment]
`rollup.config.js` looks like this:

```js
import buble from 'rollup-plugin-buble'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
// import replace from 'rollup-plugin-replace'

export default {
  entry: 'scripts/app-index.js',
  dest: 'public/js/app-bundle.js',
  format: 'iife',
  moduleName: 'Solar',
  plugins: [
    buble(),
    nodeResolve({ jsnext: true, main: true }),
    commonjs({
      include: './node_modules/**',
      exclude: './node_modules/redux/node_modules/symbol-observable/**' // for redux@3.6.0
    })
  ]
}
```

**Comment by Rich-Harris** [comment]
Can you provide a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)? Also, I don't know what wooster is

**Comment by talmobi** [comment]
https://github.com/talmobi/rollup_1433

```bash
git clone https://github.com/talmobi/rollup_1433
cd rollup_1433
npm i
npm test
```

or without wooster (a bit cluttery since v 39 prints out a bunch of logs)

```bash
npm run test-without-wooster
```

`wooster` isn't really relevant, it just parses error log like output into a more short and concise format

Point being that the most recent versions have skimmed error log output so it's very hard or impossible to see where the error is located in -- just wondering why this is the case, intended? I'm wondering how this hasn't bothered anyone else? Or is everyone still using the old versions?

**Comment by nathancahill** [comment]
I submitted a fix for this issue 2 months ago in rollup-plugin-buble (I'm currently using a fork until it's merged). https://gitlab.com/Rich-Harris/rollup-plugin-buble/merge_requests/4

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.

**Comment by talmobi** [comment]
@guybedford This was fixed in https://github.com/rollup/rollup/pull/1451

Didn't have the presence of mind to close this issue, my apologies.
