### ISSUE TITLE
How to configure treeshaking, es module and prevent "An unexpected situation arose." error

### ISSUE THREAD

**Issue by kopax** [rollup/rollup#1453]
I have the following `debug.log` when I try to bundle my rollup : 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build:dist' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prebuild:dist', 'build:dist', 'postbuild:dist' ]
5 info lifecycle template-greenmoon@0.0.1~prebuild:dist: template-greenmoon@0.0.1
6 verbose lifecycle template-greenmoon@0.0.1~prebuild:dist: unsafe-perm in lifecycle true
7 verbose lifecycle template-greenmoon@0.0.1~prebuild:dist: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/me/workspace/module.domain.com/styled-components/template-greenmoon/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/npm-global/bin:/home/me/utils:/home/me/utils
8 verbose lifecycle template-greenmoon@0.0.1~prebuild:dist: CWD: /home/me/workspace/module.domain.com/styled-components/template-greenmoon
9 silly lifecycle template-greenmoon@0.0.1~prebuild:dist: Args: [ '-c', 'rimraf dist/*' ]
10 silly lifecycle template-greenmoon@0.0.1~prebuild:dist: Returned: code: 0  signal: null
11 info lifecycle template-greenmoon@0.0.1~build:dist: template-greenmoon@0.0.1
12 verbose lifecycle template-greenmoon@0.0.1~build:dist: unsafe-perm in lifecycle true
13 verbose lifecycle template-greenmoon@0.0.1~build:dist: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/me/workspace/module.domain.com/styled-components/template-greenmoon/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/npm-global/bin:/home/me/utils:/home/me/utils
14 verbose lifecycle template-greenmoon@0.0.1~build:dist: CWD: /home/me/workspace/module.domain.com/styled-components/template-greenmoon
15 silly lifecycle template-greenmoon@0.0.1~build:dist: Args: [ '-c', 'rollup -c && rollup -c --environment PRODUCTION' ]
16 silly lifecycle template-greenmoon@0.0.1~build:dist: Returned: code: 1  signal: null
17 info lifecycle template-greenmoon@0.0.1~build:dist: Failed to exec build:dist script
18 verbose stack Error: template-greenmoon@0.0.1 build:dist: `rollup -c && rollup -c --environment PRODUCTION`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:194:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:194:7)
18 verbose stack     at maybeClose (internal/child_process.js:899:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid template-greenmoon@0.0.1
20 verbose cwd /home/me/workspace/module.domain.com/styled-components/template-greenmoon
21 error Linux 4.9.0-3-amd64
22 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:dist"
23 error node v7.10.0
24 error npm  v4.2.0
25 error code ELIFECYCLE
26 error errno 1
27 error template-greenmoon@0.0.1 build:dist: `rollup -c && rollup -c --environment PRODUCTION`
27 error Exit status 1
28 error Failed at the template-greenmoon@0.0.1 build:dist script 'rollup -c && rollup -c --environment PRODUCTION'.
28 error Make sure you have the latest version of node.js and npm installed.
28 error If you do, this is most likely a problem with the template-greenmoon package,
28 error not with npm itself.
28 error Tell the author that this fails on your system:
28 error     rollup -c && rollup -c --environment PRODUCTION
28 error You can get information on how to open an issue for this project with:
28 error     npm bugs template-greenmoon
28 error Or if that isn't available, you can get their info via:
28 error     npm owner ls template-greenmoon
28 error There is likely additional logging output above.
29 verbose exit [ 1, true ]
```
I have configured my `.babelrc` as follow: 

```json
{
  "only": [
    "src"
  ],
  "presets": [
    [
      "env", {
        "modules": false
      }
    ],
    "stage-2"
  ],
  "plugins": [
    "array-includes",
    "add-module-exports",
    "transform-class-properties"
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs",
        "dynamic-import-node"
      ]
    }
  }
}
```

And this is my `rollup.config.js`.

```jsx
/* eslint-disable flowtype-errors/show-errors, no-console, import/extensions */
import nodeResolve from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-replace';
import commonjs from 'rollup-plugin-commonjs';
import inject from 'rollup-plugin-inject';
import babel from 'rollup-plugin-babel';
import json from 'rollup-plugin-json';
import uglify from 'rollup-plugin-uglify';
import cleanup from 'rollup-plugin-cleanup';

import visualizer from 'rollup-plugin-visualizer';
const path = require('path');
const packageJsonPath = path.join(__dirname, './package.json');
const pkg = require(packageJsonPath);
const processShim = '\0process-shim';
const prod = process.env.PRODUCTION;
const mode = prod ? 'production' : 'development';

console.log(`Creating ${mode} bundle...`);

const targets = prod ?
[
  { dest: `dist/${pkg.name}.min.js`, format: 'umd' },
] :
[
  { dest: `dist/${pkg.name}.js`, format: 'umd' },
  { dest: `dist/${pkg.name}.es.js`, format: 'es' },
];

const plugins = [
  // Unlike Webpack and Browserify, Rollup doesn't automatically shim Node
  // builtins like `process`. This ad-hoc plugin creates a 'virtual module'
  // which includes a shim containing just the parts the bundle needs.
  {
    resolveId(importee) {
      if (importee === processShim) return importee;
      return null;
    },
    load(id) {
      if (id === processShim) return 'export default { argv: [], env: {} }';
      return null;
    },
  },
  nodeResolve(),
  commonjs({
    include: 'node_modules/**',
  }),
  replace({
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  }),
  inject({
    process: processShim,
  }),
  babel(),
  json(),
  cleanup(),
];

if (prod) plugins.push(uglify(), visualizer({ filename: './bundle-stats.html' }));

export default {
  entry: 'src/index.js',
  moduleName: pkg.name,
  external: [],
  exports: 'named',
  targets,
  plugins,
  globals: {},
};
```

And my `package.json`

```json
{
  "name": "template-greenmoon",
  "version": "0.0.1",
  "description": "",
  "main": "lib/index.js",
  "jsnext:main": "dist/template-greenmoon.es.js",
  "module": "dist/template-greenmoon.es.js",
  "scripts": {
    "prebuild": "npm run build:clean && npm run test",
    "build": "npm run build:lib && npm run build:dist",
    "prebuild:lib": "rimraf lib/*",
    "build:lib": "BABEL_ENV=production babel --out-dir lib src",
    "prebuild:dist": "rimraf dist/*",
    "build:clean": "rimraf lib/* dist/*",
    "build:dist": "rollup -c && rollup -c --environment PRODUCTION",
    "build:readme": "toctoc README.md -w",
    "build:watch": "npm run build:lib -- --watch",
    "test": "npm run lint && npm run test:web",
    "test:web": "NODE_ENV=test TEST_REPORT_PATH=reports jest --coverage",
    "test:clean": "rimraf ./coverage",
    "test:watch": "npm run test -- --watch",
    "lint": "eslint src",
    "prepublish": "npm run build",
    "lint-staged": "lint-staged",
    "rollup-umd": "node ./internal/rollup-umd --"
  },
  "repository": {
    "url": ""
  },
  "files": [
    "CODE_OF_CONDUCT.md",
    "dist",
    "lib",
    "src"
  ],
  "keywords": "",
  "author": "",
  "license": "UNLICENSED",
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends": "airbnb",
    "env": {
      "browser": true,
      "node": true,
      "jest": true,
      "es6": true
    },
    "parserOptions": {
      "ecmaVersion": 6,
      "sourceType": "module"
    },
    "rules": {
      "arrow-parens": [
        "error",
        "always"
      ],
      "arrow-body-style": [
        2,
        "as-needed"
      ],
      "comma-dangle": [
        2,
        "always-multiline"
      ],
      "import/imports-first": 0,
      "import/newline-after-import": 0,
      "import/no-dynamic-require": 0,
      "import/no-extraneous-dependencies": 0,
      "import/no-named-as-default": 0,
      "import/no-unresolved": 2,
      "import/prefer-default-export": 0,
      "indent": [
        2,
        2,
        {
          "SwitchCase": 1
        }
      ],
      "max-len": 0,
      "newline-per-chained-call": 0,
      "no-confusing-arrow": 0,
      "no-console": 1,
      "no-use-before-define": 0,
      "prefer-template": 2,
      "class-methods-use-this": 0,
      "require-yield": 0,
      "jsx-a11y/aria-props": 2,
      "jsx-a11y/heading-has-content": 0,
      "jsx-a11y/href-no-hash": 2,
      "jsx-a11y/label-has-for": 2,
      "jsx-a11y/mouse-events-have-key-events": 2,
      "jsx-a11y/role-has-required-aria-props": 2,
      "jsx-a11y/role-supports-aria-props": 2,
      "react/forbid-prop-types": 0,
      "react/jsx-first-prop-new-line": [
        2,
        "multiline"
      ],
      "react/jsx-filename-extension": 0,
      "react/jsx-no-target-blank": 0,
      "react/require-extension": 0,
      "react/self-closing-comp": 0
    }
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.24.1",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^6.2.10",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-array-includes": "^2.0.3",
    "babel-plugin-dynamic-import-node": "^1.0.2",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-react-intl": "^2.3.1",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-styled-components": "^1.1.4",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-react-constant-elements": "^6.23.0",
    "babel-plugin-transform-react-inline-elements": "^6.22.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.6",
    "babel-preset-env": "^1.4.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "bootstrap-styled": "git+ssh://git@module.domain.com/styled-components/bootstrap-styled.git#v1.1.3",
    "classnames": "^2.2.5",
    "enzyme": "^2.8.2",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-react": "^7.1.0",
    "jest-cli": "^19.0.2",
    "jest-sonar-reporter": "^1.1.1",
    "lint-staged": "^3.3.0",
    "pre-commit": "^1.2.2",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-addons-test-utils": "^15.6.0",
    "react-dom": "^15.6.1",
    "react-router-dom": "4.1.1",
    "react-test-renderer": "^15.6.1",
    "react-transition-group": "^1.2.0",
    "rimraf": "^2.6.1",
    "rollup": "^0.42.0",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-cleanup": "^1.0.1",
    "rollup-plugin-commonjs": "^8.0.2",
    "rollup-plugin-inject": "^2.0.0",
    "rollup-plugin-json": "^2.3.0",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-replace": "^1.1.1",
    "rollup-plugin-uglify": "^1.0.2",
    "rollup-plugin-visualizer": "^0.2.1",
    "sinon": "^2.3.2",
    "styled-components": "^2.1.0",
    "toctoc": "^0.2.3"
  },
  "jest": {
    "roots": [
      "<rootDir>/src/"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/dist/",
      "<rootDir>/lib/"
    ],
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}",
      "!src/**/*.test.{js,jsx}"
    ],
    "coverageThreshold": {
      "global": {
        "statements": 15,
        "branches": 15,
        "functions": 0,
        "lines": 30
      }
    },
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "testRegex": "tests/.*\\.test\\.js$",
    "testResultsProcessor": "jest-sonar-reporter"
  },
  "lint-staged": {
    "*.js": [
      "eslint --fix",
      "git add"
    ]
  },
  "pre-commit": [
    "build:readme",
    "lint-staged"
  ],
  "dependencies": {
    "lodash.omit": "^4.5.0"
  },
  "peerDependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "prop-types": "^15.5.10",
    "styled-components": "^2.1.0",
    "bootstrap-styled": "git+ssh://git@module.domain.com/styled-components/bootstrap-styled.git#v1.1.3",
    "classnames": "^2.2.5",
    "react-transition-group": "^1.2.0"
  }
}
```

With such configuration, the `dist` and `lib` look like this : 

**Original**

`src/index.js`:

```jsx
/**
 * Code your first module here
 */
import React from 'react';
import PropTypes from 'prop-types';

// eslint-disable-next-line react/prefer-stateless-function
export default class ReactDemo extends React.Component {

  static propTypes = {
    testProps: PropTypes.bool.isRequired,
  }

  static defaultProps = {
    testProps: true,
  }

  render() {
    const { testProps, ...rest } = this.props;
    return (
      <div {...rest}>Hello {testProps}</div>
    );
  }

}

```

`src/tests/index.test.js`:

```jsx
/**
 * Testing example
 */

import { shallow } from 'enzyme';
import React from 'react';
import ReactDemo from '../index';

const renderComponent = (props = {}) => shallow(
  <ReactDemo {...props}/>
);

describe('<ReactDemo />', () => {
  it('should render an <ReactDemo /> tag', () => {
    const renderedComponent = renderComponent();
    expect(renderedComponent.length).toBe(1);
  });
});

```

**lib/**

`lib/index.js`:

```jsx
var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

/**
 * Code your first module here
 */
import React from 'react';
import PropTypes from 'prop-types';

// eslint-disable-next-line react/prefer-stateless-function

var ReactDemo = function (_React$Component) {
  _inherits(ReactDemo, _React$Component);

  function ReactDemo() {
    _classCallCheck(this, ReactDemo);

    return _possibleConstructorReturn(this, (ReactDemo.__proto__ || Object.getPrototypeOf(ReactDemo)).apply(this, arguments));
  }

  _createClass(ReactDemo, [{
    key: 'render',
    value: function render() {
      var _props = this.props,
          testProps = _props.testProps,
          rest = _objectWithoutProperties(_props, ['testProps']);

      return React.createElement(
        'div',
        rest,
        'Hello ',
        testProps
      );
    }
  }]);

  return ReactDemo;
}(React.Component);

ReactDemo.propTypes = {
  testProps: PropTypes.bool.isRequired
};
ReactDemo.defaultProps = {
  testProps: true
};
export default ReactDemo;
module.exports = exports['default'];
```

`lib/tests/index.test.js`:

```jsx
/**
 * Testing example
 */

import { shallow } from 'enzyme';
import React from 'react';
import ReactDemo from '../index';

var renderComponent = function renderComponent() {
  var props = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
  return shallow(React.createElement(ReactDemo, props));
};

describe('<ReactDemo />', function () {
  it('should render an <ReactDemo /> tag', function () {
    var renderedComponent = renderComponent();
    expect(renderedComponent.length).toBe(1);
  });
});
```

**dist/**

`dist/template-greenmoon.es.js`:

```jsx
import React from 'react';
import PropTypes from 'prop-types';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();
function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }
function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
var ReactDemo = function (_React$Component) {
  _inherits(ReactDemo, _React$Component);
  function ReactDemo() {
    _classCallCheck(this, ReactDemo);
    return _possibleConstructorReturn(this, (ReactDemo.__proto__ || Object.getPrototypeOf(ReactDemo)).apply(this, arguments));
  }
  _createClass(ReactDemo, [{
    key: 'render',
    value: function render() {
      var _props = this.props,
          testProps = _props.testProps,
          rest = _objectWithoutProperties(_props, ['testProps']);
      return React.createElement(
        'div',
        rest,
        'Hello ',
        testProps
      );
    }
  }]);
  return ReactDemo;
}(React.Component);
ReactDemo.propTypes = {
  testProps: PropTypes.bool.isRequired
};
ReactDemo.defaultProps = {
  testProps: true
};
module.exports = exports['default'];

export default ReactDemo;

```

`dist/template-greenmoon.js`:

```jsx
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react'), require('prop-types')) :
	typeof define === 'function' && define.amd ? define(['exports', 'react', 'prop-types'], factory) :
	(factory((global['rollup-umd'] = global['rollup-umd'] || {}),global.React,global.PropTypes));
}(this, (function (exports,React,PropTypes) { 'use strict';

React = 'default' in React ? React['default'] : React;
PropTypes = 'default' in PropTypes ? PropTypes['default'] : PropTypes;

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();
function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }
function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
var ReactDemo = function (_React$Component) {
  _inherits(ReactDemo, _React$Component);
  function ReactDemo() {
    _classCallCheck(this, ReactDemo);
    return _possibleConstructorReturn(this, (ReactDemo.__proto__ || Object.getPrototypeOf(ReactDemo)).apply(this, arguments));
  }
  _createClass(ReactDemo, [{
    key: 'render',
    value: function render() {
      var _props = this.props,
          testProps = _props.testProps,
          rest = _objectWithoutProperties(_props, ['testProps']);
      return React.createElement(
        'div',
        rest,
        'Hello ',
        testProps
      );
    }
  }]);
  return ReactDemo;
}(React.Component);
ReactDemo.propTypes = {
  testProps: PropTypes.bool.isRequired
};
ReactDemo.defaultProps = {
  testProps: true
};
module.exports = exports['default'];

exports['default'] = ReactDemo;

Object.defineProperty(exports, '__esModule', { value: true });

})));

```

`dist/template-greenmoon.min.js`:

```js
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports,require("react"),require("prop-types")):"function"==typeof define&&define.amd?define(["exports","react","prop-types"],t):t(e["rollup-umd"]=e["rollup-umd"]||{},e.React,e.PropTypes)}(this,function(e,t,r){"use strict";function o(e,t){var r={};for(var o in e)t.indexOf(o)>=0||Object.prototype.hasOwnProperty.call(e,o)&&(r[o]=e[o]);return r}function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function u(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!t||"object"!=typeof t&&"function"!=typeof t?e:t}function p(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t);e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}}),t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t)}t="default"in t?t.default:t,r="default"in r?r.default:r;var i=function(){function e(e,t){for(var r=0;r<t.length;r++){var o=t[r];o.enumerable=o.enumerable||!1,o.configurable=!0,"value"in o&&(o.writable=!0),Object.defineProperty(e,o.key,o)}}return function(t,r,o){return r&&e(t.prototype,r),o&&e(t,o),t}}(),f=function(e){function r(){return n(this,r),u(this,(r.__proto__||Object.getPrototypeOf(r)).apply(this,arguments))}return p(r,e),i(r,[{key:"render",value:function(){var e=this.props,r=e.testProps,n=o(e,["testProps"]);return t.createElement("div",n,"Hello ",r)}}]),r}(t.Component);f.propTypes={testProps:r.bool.isRequired},f.defaultProps={testProps:!0},module.exports=e.default,e.default=f,Object.defineProperty(e,"__esModule",{value:!0})});
```

I am not sure if my configuration is correct, I have started to use rollup after trying webpack and found interesting to use es module. 

So far I am using only one environment for babel using the `.babelrc`

Can anyone help me have a good configuration for writing next gen javascript :) ?

**Comment by bfred-it** [comment]
That's a lot of files to copy/paste. Can you create a repo instead? That's less work if anyone wants to try to help.

**Comment by kopax** [comment]
Thanks @bfred-it. I think my issue is related to a library I am importing (tether) which can't be used in an es module. I am trying to import the es module in the react boilerplate (webpack2). Closing as it is not related to rollup configuration. I might come back but closing for now. 

Thanks for helping!
