### ISSUE TITLE
rollupjs API wiki wrong example

### ISSUE THREAD

**Issue by lx93uv** [rollup/rollup#1454]
`debian 9`, `node 8`

```
$ cat bundler.js
var rollup = require( 'rollup' );                                               
var cache;                                                                      
                                                                                
rollup.rollup({                                                                 
  entry: 'foo.js',                                                              
  cache: cache                                                                  
}).then( function ( bundle ) {                                                  
  // Generate bundle + sourcemap                                                
  var result = bundle.generate({                                                
    // output format - 'amd', 'cjs', 'es', 'iife', 'umd'                        
    format: 'cjs'                                                               
  });                                                                           
                                                                                
  cache = bundle;                                                               
                                                                                
  bundle.write({                                                                
    format: 'cjs',                                                              
    dest: 'bundle.js'                                                           
  });                                                                           
});

$ node bundler.js
(node:16782) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Unexpected token
(node:16782) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Inspired by https://github.com/rollup/rollup/wiki/JavaScript-API.

Can someone help to fix it?

**Comment by bfred-it** [comment]
The warnings you see are because there's no `.catch()` and because there's an error in there (which you can't see because there's no `.catch()` with logging inside).

I fixed the example:

```js
                                          
rollup.rollup({                                                                 
  entry: 'foo.js',                                                              
  cache: cache                                                                  
}).then( function ( bundle ) {
////////////////////// code                                        
}).catch(console.error);
```

And now it shows the error:

```
{ Error: Could not resolve entry (foo.js)
    at error (/Users/bfred/delme/node_modules/rollup/dist/rollup.js:170:12)
    at /Users/bfred/delme/node_modules/rollup/dist/rollup.js:9622:5
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3 code: 'UNRESOLVED_ENTRY' }
```

You don't have a file called `foo.js`
