### ISSUE TITLE
0.46.3+ Type error.

### ISSUE THREAD

**Issue by cebor** [rollup/rollup#1547]
Since `0.46.3` i get following error when compiling my angular library:

```
build/angular-highcharts.js → dist/angular-highcharts.js...
[!] TypeError: declaration.module.getExports is not a function
TypeError: declaration.module.getExports is not a function
    at addDeclaration (/Users/felix/code/angular-highcharts/node_modules/rollup/dist/rollup.js:8094:25)
    at /Users/felix/code/angular-highcharts/node_modules/rollup/dist/rollup.js:8103:5
    at Array.forEach (<anonymous>)
    at /Users/felix/code/angular-highcharts/node_modules/rollup/dist/rollup.js:8102:34
    at /Users/felix/code/angular-highcharts/node_modules/rollup/dist/rollup.js:127:57
    at Array.forEach (<anonymous>)
    at forOwn (/Users/felix/code/angular-highcharts/node_modules/rollup/dist/rollup.js:127:24)
    at ModuleScope.deshadow (/Users/felix/code/angular-highcharts/node_modules/rollup/dist/rollup.js:8089:3)
    at /Users/felix/code/angular-highcharts/node_modules/rollup/dist/rollup.js:5908:57
    at Array.forEach (<anonymous>)
```

Repo: https://github.com/cebor/angular-highcharts (build.sh)

With 0.46.2 all works fine.

**Comment by Rich-Harris** [comment]
Thanks — this is fixed in 0.47.2
