### ISSUE TITLE
dynamic import 

### ISSUE THREAD

**Issue by willin** [rollup/rollup#1609]
```js
// ./config/index.js
const ENV = process.env.NODE_ENV || 'development';
// eslint-disable-next-line import/no-dynamic-require
const options = require(`./_${ENV}`);

// export default options;
module.exports = options;
```

```js
// ./config/_development.js
export const enabledModules = ['sms', 'user', 'org', 'device', 'upload', 'routine', 'qcloud', 'app', 'email'];

export const mysq = {
  connectionLimit: 10,
  host: '127.0.0.1',
  user: 'root',
  password: 'root'
};

export const redis = {
  host: '127.0.0.1',
  port: 6379,
  db: 1,
  ttl: 3600
};

export const server = {
  port: 3300,
  hostname: '127.0.0.1'
};

// export const hostname = `${server.hostname}:${server.port}`;
// export const liveStreamPrefix = 'http://127.0.0.1:3300/routine/live/';
// export const interfacePrefix = 'http://127.0.0.1:3300/';
```

this is ok:

```js
// ./src/index.js
import { server as serverOptions } from '../config/_development';

console.log(serverOptions);
```

this occurs error:

```js
// ./src/index.js
import { server as serverOptions } from '../config';

console.log(serverOptions);
```

```

/Users/willin/Documents/dwing/v2/airx/src/index.js → dist/airx.js...
[!] Error: Could not resolve '../config' from src/index.js
Error: Could not resolve '../config' from src/index.js
    at error (/Users/willin/Documents/dwing/v2/airx/node_modules/rollup/dist/rollup.js:185:14)
    at then.resolvedId (/Users/willin/Documents/dwing/v2/airx/node_modules/rollup/dist/rollup.js:9805:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

error Command failed with exit code 1.
```

**Comment by kzc** [comment]
https://github.com/rollup/rollup-plugin-node-resolve

**Comment by willin** [comment]
rollup-plugin-node-resolve does not support exclude,  all `node_modules` dep will be bundled in

**Comment by willin** [comment]
no use.

see https://github.com/AirDwing/rollup-demo

**Comment by guybedford** [comment]
Dynamic import is now supported under the experimental flag option - https://rollupjs.org/guide/en#experimental-code-splitting.
