### ISSUE TITLE
Bundling react-dom causes "Maximum callstack size exceeded" error

### ISSUE THREAD

**Issue by herrstucki** [rollup/rollup#1627]
Rollup 0.49 exits with this error:

```
[!] RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at SetIterator (native)
    at Set.values (native)
    at Function.from (native)
    at Node.hasEffectsWhenMutated (/Users/jeremy/Code/Experiments/rollup-react-bug/node_modules/rollup/dist/rollup.js:6900:10)
    at Node.hasEffectsWhenMutated (/Users/jeremy/Code/Experiments/rollup-react-bug/node_modules/rollup/dist/rollup.js:7091:21)
    at declaration.declaration.included.declaration.isParam.declaration.isGlobal.declaration.isExternal.declaration.isNamespace.declaration.assignedExpressions.Array.from.some.node (/Users/jeremy/Code/Experiments/rollup-react-bug/node_modules/rollup/dist/rollup.js:6900:74)
    at Array.some (<anonymous>)
    at Node.hasEffectsWhenMutated (/Users/jeremy/Code/Experiments/rollup-react-bug/node_modules/rollup/dist/rollup.js:6900:55)
    at Node.hasEffectsWhenMutated (/Users/jeremy/Code/Experiments/rollup-react-bug/node_modules/rollup/dist/rollup.js:7091:21)
    at declaration.declaration.included.declaration.isParam.declaration.isGlobal.declaration.isExternal.declaration.isNamespace.declaration.assignedExpressions.Array.from.some.node (/Users/jeremy/Code/Experiments/rollup-react-bug/node_modules/rollup/dist/rollup.js:6900:74)
```

0.48 is fine.

Repro: https://gist.github.com/herrstucki/b6fe9d68f0490271f6f6cc43410e6eb5

**Comment by lukastaegert** [comment]
Hi @herrstucki, thanks for the report + repro. I just checked it locally, this should be fixed once #1624 is merged, sorry for the hassles.

**Comment by herrstucki** [comment]
@lukastaegert awesome, thanks! 🙇

**Comment by perrin4869** [comment]
Any clue when this might land? Making development a bit hard right now...

**Comment by lukastaegert** [comment]
@Rich-Harris …

**Comment by lukastaegert** [comment]
Until then I fear you need to stick with a previous version.

**Comment by herrstucki** [comment]
Thanks @lukastaegert & @Rich-Harris 👍 💯
