### ISSUE TITLE
Rollup 0.49.3 regression bundling React

### ISSUE THREAD

**Issue by shanewholloway** [rollup/rollup#1631]
Working with React 15.6.1, I discovered a regression when bundling with Rollup 0.49.3 in the form of a `RangeError: Maximum call stack size exceeded` exception. This gist bundles without error with Rollup 0.49.2.

### Repro
[Gist reproduction](https://gist.github.com/shanewholloway/0300fe7a4f6ce1b200275b880f79a2d2#file-readme-md)

`git checkout https://gist.github.com/shanewholloway/0300fe7a4f6ce1b200275b880f79a2d2`

### Error text:

```node
Error during rollup build: RangeError: Maximum call stack size exceeded
    at Set.values (native)
    at Function.from (native)
    at Node.hasEffectsWhenMutated (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:6900:10)
    at Node.hasEffectsWhenMutated (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:7091:21)
    at declaration.declaration.included.declaration.isParam.declaration.isGlobal.declaration.isExternal.declaration.isNamespace.declaration.assignedExpressions.Array.from.some.node (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:6900:74)
    at Array.some (<anonymous>)
    at Node.hasEffectsWhenMutated (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:6900:55)
    at Node.hasEffectsWhenMutated (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:7091:21)
    at declaration.declaration.included.declaration.isParam.declaration.isGlobal.declaration.isExternal.declaration.isNamespace.declaration.assignedExpressions.Array.from.some.node (/Users/sholloway/sandbox/2017-09-12-rollup-react/node_modules/rollup/dist/rollup.js:6900:74)
    at Array.some (<anonymous>)
```

**Comment by daemonburrito** [comment]
This is #1627, I think (I had the same trouble).

**Comment by shanewholloway** [comment]
Yes, a duplicate of #1627. I found it yesterday as well…

**Comment by raphaelokon** [comment]
Cheers for reporting it … I had the very same issue and was about to post it.
