### ISSUE TITLE
Error: Unexpected token

### ISSUE THREAD

**Issue by zxc0254** [rollup/rollup#1652]
Error: Unexpected token
    at error (E:\work\wsearch\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error (E:\work\wsearch\node_modules\rollup\dist\rollup.js:8171:3)
    at tryParse (E:\work\wsearch\node_modules\rollup\dist\rollup.js:7889:10)
    at new Module (E:\work\wsearch\node_modules\rollup\dist\rollup.js:7925:15)
    at load.catch.then.then.then.source (E:\work\wsearch\node_modules\rollup\dist\rollup.js:9750:20)
    at <anonymous>

Ask for help, thank you!

**Comment by ak4wrapp** [comment]
Any solutions so far?

**Comment by TrySound** [comment]
Which node do you use guys? Which version of rollup? What is your OS?

**Comment by ak4wrapp** [comment]
I have not install rollup explicitly but yarn info rollup version shows as 0.55.0
os: windows
nom 3.10.10

**Comment by ak4wrapp** [comment]
and it occurs when I used **npm run ngpackagr**

**Comment by adrianheine** [comment]
Which nodejs version?

**Comment by kerwitz** [comment]
Node 6.9.5, npm 3.10.10 and Rollup 0.55.5 here:

`[18:01:38] Error: Unexpected token
    at error (/home/kerwitz/workspace/project/node_modules/rollup/dist/rollup.js:185:14)
    at Module.error (/home/kerwitz/workspace/project/node_modules/rollup/dist/rollup.js:8452:3)
    at tryParse (/home/kerwitz/workspace/project/node_modules/rollup/dist/rollup.js:8168:10)
    at new Module (/home/kerwitz/workspace/project/node_modules/rollup/dist/rollup.js:8209:15)
    at load.catch.then.then.then.source (/home/kerwitz/workspace/project/node_modules/rollup/dist/rollup.js:10069:20)`

The original error might even be in our own source, but the way it is handled makes it impossible to know that.

**Comment by allexcd** [comment]
Build fails with `Unexpected token }`

```js
C:\[project-name]\node_modules\rollup\bin\rollup:2471
});
^

SyntaxError: Unexpected token }
   at new Script (vm.js:51:7)
   at createScript (vm.js:138:10)
   at Object.runInThisContext (vm.js:199:10)
   at Module._compile (module.js:624:28)
   at Object.Module._extensions..js (module.js:671:10)
   at Module.load (module.js:573:32)
   at tryModuleLoad (module.js:513:12)
   at Function.Module._load (module.js:505:3)
   at Function.Module.runMain (module.js:701:10)
   at startup (bootstrap_node.js:190:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Rollup version: 0.55.6
OS: Windows 10 Pro x64
Node: 9.5.0 / also tried with Node 8.9.1

I have commented all the project code and still get this error. I've also tried downgrade, version by version until `0.47.0` which seems to give me different errors

None of the solutions work for me in a Windows environment. Hope someone has some clue about what it might happen.

**Comment by shellscape** [comment]
@allexcd if you have a spare moment, could you confirm that the latest version exhibits the same behavior? if that's still happening, would you be able to provide a [REPL](https://rollupjs.org/repl) or repo link to a reproduction?

**Comment by ben-page** [comment]
This still happens. A more precise error message would be extremely helpful.

node - v `v10.10.0`
yarn rollup -v `v0.66.0`
Windows 10

**build.js**
This is my rollup build script.
```javascript
const rollup = require('rollup');
const resolve = require('rollup-plugin-node-resolve');
const commonjs  = require('rollup-plugin-commonjs');

async function build() {
    try {
        const bundle = await rollup.rollup({
            input: './moment-timezone.js',
            plugins: [
                resolve(),
                commonjs(),
            ]
        });

        await bundle.write({
            file: 'moment-timezone-bundle.js',
            format: 'esm'
        });
    } catch (err) {
        console.error(err.stack);
    }
}

build();
```

**moment-timezone.js**
This file is the entry point. Make sure to add moment-timezone.
i.e. `yarn add moment-timezone`
```javascript
'use strict';
const moment = require('moment-timezone');
moment.tz.load(require('moment-timezone/data/packed/latest.json'));
module.exports = moment;
```

**output**
```
Error: Unexpected token
    at error (C:\XXX\node_modules\rollup\dist\rollup.js:3461:30)
    at Module.error (C:\XXX\node_modules\rollup\dist\rollup.js:13358:9)
    at tryParse (C:\XXX\node_modules\rollup\dist\rollup.js:13016:16)
    at Module.setSource (C:\XXX\node_modules\rollup\dist\rollup.js:13089:33)
    at C:\projects\XXX\node_modules\rollup\dist\rollup.js:21758:20
```

**Comment by lukastaegert** [comment]
I created #2466 to improve error messages with regard to the issues encountered above. Note that rollup usually does not "swallow" original error messages but instead puts additional properties on the error objects. Rollup's own CLI will output this additional information. If you use the JS API, note that for parse errors, you may want to inspect:
* `error.loc` for the file and position (or `error.pos` and `error.id`)
* `error.frame` to get a few lines surrounding the error plus a marker where the error occurred

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
