### ISSUE TITLE
import debug problem

### ISSUE THREAD

**Issue by portfolio-systems** [rollup/rollup#1676]
Rollup working absolutely fine until I introduce
import debug from 'debug';
and enable it in the plugins array

rollup -c

[!] TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Function.enabled (/usr/local/var/www/rollup-starter-app/node_modules/debug/src/debug.js:197:16)
    at createDebug (/usr/local/var/www/rollup-starter-app/node_modules/debug/src/debug.js:119:27)
    at Object.<anonymous> (/usr/local/var/www/rollup-starter-app/rollup.config.js:36:3)
    at Module._compile (module.js:624:30)
    at Object.require.extensions..js (/usr/local/var/www/rollup-starter-app/node_modules/rollup/bin/rollup:2675:8)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rollup-starter-app@ build: `rollup -c`
npm ERR! Exit status 1

**Comment by guybedford** [comment]
It's necessary to use the Rollup CommonJS plugin for importing node modules.

**Comment by guybedford** [comment]
Closing as this has been inactive for a while and newer relevant issues can track these concerns. Happy to continue discussion as well here too.
