### ISSUE TITLE
Rollup watch is interrupted very often

### ISSUE THREAD

**Issue by StarpTech** [rollup/rollup#1752]
When I run rollup in watch mode my build is interrupted very often. That's the log output.

Rollup: 0.50.0
Windows
npm@5.5.1
node@v8.6.0
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   '-w' ]
2 info using npm@5.5.1
3 info using node@v8.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle kernload-theme@1.0.0~prebuild: kernload-theme@1.0.0
6 info lifecycle kernload-theme@1.0.0~build: kernload-theme@1.0.0
7 verbose lifecycle kernload-theme@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle kernload-theme@1.0.0~build: PATH: XXX
10 silly lifecycle kernload-theme@1.0.0~build: Args: [ '/d /s /c', 'rollup -c config/rollup.config.js "-w"' ]
11 silly lifecycle kernload-theme@1.0.0~build: Returned: code: 4294963238  signal: null
12 info lifecycle kernload-theme@1.0.0~build: Failed to exec build script
13 verbose stack Error: kernload-theme@1.0.0 build: `rollup -c config/rollup.config.js "-w"`
13 verbose stack Exit status 4294963238
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid kernload-theme@1.0.0
15 verbose cwd C:\Users\dev\Documents\Repositorys\Kernkraft\Kernload\netzkern.Kernload.Mvc\wwwroot
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--" "-w"
18 verbose node v8.6.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 4294963238
22 error kernload-theme@1.0.0 build: `rollup -c config/rollup.config.js "-w"`
22 error Exit status 4294963238
23 error Failed at the kernload-theme@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294963238, true ]
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
