### ISSUE TITLE
GC error with node V9, and rollup 0.51.8

### ISSUE THREAD

**Issue by DrYSG** [rollup/rollup#1753]
I know I have a lot of imports of .js files that are data (400K lines) so I suspect that is the problem.  So I don't think I need to create a repl and overburden your site. I am not using any plugins. It is straight ES6 code meant for Chrome V61,

Anything that I can do about this?

```

workbench@1.0.0 build D:\wwwroot\Workbench
> rollup -c


    scripts/Main.js → bundle.js...
    
    <--- Last few GCs --->
    
    [11428:000001AAB15A09D0]    34674 ms: Mark-sweep 1509.9 (1568.1) -> 1509.8 (1569.1) MB, 1151.5 / 0.0 ms  allocation failure GC in old space requested
    [11428:000001AAB15A09D0]    35753 ms: Mark-sweep 1509.8 (1569.1) -> 1509.8 (1538.1) MB, 1078.9 / 0.0 ms  last resort GC in old space requested
    [11428:000001AAB15A09D0]    36888 ms: Mark-sweep 1509.8 (1538.1) -> 1509.8 (1538.1) MB, 1135.4 / 0.0 ms  last resort GC in old space requested
    
    
    <--- JS stacktrace --->
    
    ==== JS stack trace =========================================
    
    Security context: 0000018AA5225729 <JSObject>
        1: split(this=000002F007782201 <Very long string[7147106]>)
        2: guessIndent(aka guessIndent) [D:\wwwroot\Workbench\node_modules\rollup\dist\rollup.js:639] [bytecode=00000237F3924959 offset=11](this=000002F71B0022D1 <undefined>,code=000002F007782201 <Very long string[7147106]>)
        3: new MagicString$1 [D:\wwwroot\Workbench\node_modules\rollup\dist\rollup.js:865] [bytecode=00000237F3923C...
    
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
    npm ERR! code ELIFECYCLE
    npm ERR! errno 134
    npm ERR! workbench@1.0.0 build: `rollup -c`
    npm ERR! Exit status 134
    npm ERR!
    npm ERR! Failed at the workbench@1.0.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\ysg4206\AppData\Roaming\npm-cache\_logs\2017-11-22T21_53_17_670Z-debug.log

```

**Comment by kzc** [comment]
```
node --max-old-space-size=4096 /path/to/rollup -c
```
experiment with the heap size.

**Comment by DrYSG** [comment]
sounded good. But I am having some issue with that:

```
D:\>node --max-old-space-size=4096 D:\wwwroot\Workbench\node_modules\.bin\rollup -c
D:\wwwroot\Workbench\node_modules\.bin\rollup:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

**Comment by kzc** [comment]
That's a bash script. It won't work in Windows. Specify `node_modules/rollup/bin/rollup` instead.

**Comment by DrYSG** [comment]
I found this npm utility that adds heap for one or all of your node binary scripts.
https://www.npmjs.com/package/increase-memory-limit

And that solved the problem. Thank you.

**Comment by kzc** [comment]
Glad you found a workaround. That tool is doing the same thing as https://github.com/rollup/rollup/issues/1753#issuecomment-346511427

https://github.com/endel/increase-memory-limit/blob/4f411689cc9078ff6c61082e33726d3d59d3fb2e/index.js#L30
