### ISSUE TITLE
Error: You must specify options.file when using rollup.config.js

### ISSUE THREAD

**Issue by cswl** [rollup/rollup#1754]
I've followed the instructions from: 
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency

And here's my `rollup.config.js`
```

import pkg from './package.json';

export default {
    input: 'src/main.mjs',
    output: [
        { file: pkg.main, format: 'cjs' },
        { file: pkg.module, format: 'es' }
    ],
    external: ['path'], // <-- suppresses the warning
};
```

Howeve, running `rollup -c` produces the following error.
```
src/main.mjs → main.js, ...
[!] Error: You must specify options.file
Error: You must specify options.file
    at error (/home/cswl/repos/fcc_cli_challenges/node_modules/rollup/dist/rollup.js:185:14)
    at Object.write (/home/cswl/repos/fcc_cli_challenges/node_modules/rollup/dist/rollup.js:18714:7)
    at output (/home/cswl/repos/fcc_cli_challenges/node_modules/rollup/bin/rollup:3295:19)
    at next (/home/cswl/repos/fcc_cli_challenges/node_modules/rollup/bin/rollup:3249:27)
    at promise.then (/home/cswl/repos/fcc_cli_challenges/node_modules/rollup/bin/rollup:3253:33)
    at <anonymous>

```

**Comment by cswl** [comment]
Never mind it was a derp.
I didnt had pkg.module ..

**Comment by lukastaegert** [comment]
I assume this means this issue can be closed?

**Comment by cswl** [comment]
Yes..
Although I think the error message could be improved.. since it's not `options.file` but `output[1].file`.. however it's an edge case

**Comment by lukastaegert** [comment]
Thanks for the tip. The array might be an edge case but I made a note to at least change it to read `output.file`.
