### ISSUE TITLE
--environment CLI param doesn't allow multiple entries

### ISSUE THREAD

**Issue by tivac** [rollup/rollup#1764]
```bash
$ rollup --version
rollup version 0.52.0

$ rollup --environment=ONE --environment=TWO

C:\node_modules\rollup\bin\rollup:3896
                command.environment.split( ',' ).forEach( pair => {
                      ^
TypeError: command.environment.split is not a function
    at runRollup (C:\node_modules\rollup\bin\rollup:3896:23)
    at Object.<anonymous> (C:\node_modules\rollup\bin\rollup:4014:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Is this intended to only allow a single `environment` CLI param? If not, would a PR to fix it be accepted?

**Comment by lukastaegert** [comment]
For now, the only way to pass in multiple arguments is to supply a comma-separated list after `--environment`. But I can see the value of being able to use the argument several times, e.g. if you want to be able to `npm run my-job -- --environment BONUS_ENV=true`.
Yes, a PR would be welcome! My only fear is that the argument validation code is quite repetitive and convoluted already so trying to find a sort-of clean solution would be preferred.

**Comment by tivac** [comment]
Yeah, setting nested `--environment` flags in npm scripts is my exact use-case for wanting this. I'll take a stab at it and see how things end up.
