### ISSUE TITLE
Reexported modules not resolving?

### ISSUE THREAD

**Issue by Birowsky** [rollup/rollup#1852]
It's my first day with rollup, so I might be missing something obvious. 

Given: 

```
import {Lambda} from "aws-sdk";
console.log(Lambda);
```

Rollup fails with:

> ERROR in ./src/entry.ts Module build failed: Error: 'Lambda' is not exported by node_modules/aws-sdk/lib/aws.js

The content of the [aws-sdk](https://github.com/aws/aws-sdk-js/blob/master/index.d.ts) module is:

```
import {GlobalConfigInstance} from './lib/config';
export * from './lib/core';
export * from './clients/all';
export var config: GlobalConfigInstance
export as namespace AWS;
```

Here's a setup that demonstrates this:
https://github.com/Birowsky/testing-typescript-treeshaking/tree/rollup-issue

Let me know if I need to provide anything else. Thanx!

**Comment by Birowsky** [comment]
@guybedford just tried. Problem is still there.

```
ERROR in ./src/entry.ts
Module build failed: Error: 'Lambda' is not exported by node_modules/aws-sdk/lib/aws.js
    at error (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:199:15)
    at Module.error (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:16925:9)
    at handleMissingExport (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:17234:21)
    at /Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:20035:56
    at Array.reduce (<anonymous>)
    at Graph.handleMissingExport (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:20034:27)
    at Module.traceVariable (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:17008:28)
    at ModuleScope.findVariable (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:13443:29)
    at Identifier.bind (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:14134:40)
    at CallExpression.NodeBase.bind (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:13484:31)
    at CallExpression.bind (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:14684:31)
    at ExpressionStatement.NodeBase.bind (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:13488:23)
    at Program.NodeBase.bind (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:13484:31)
    at Module.bindReferences (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:16879:18)
    at Graph.link (/Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:20185:20)
    at /Users/Birowsky/Projects/Opensource/testing-typescript-treeshaking/node_modules/rollup/dist/rollup.js:20222:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by guybedford** [comment]
It seems the issue here is that you need to configure the CommonJS plugin for Rollup, and then that allows you to define exports using configuration as well using something like:

```js
plugins: [..., commonjs({
  namedExports: { './node_modules/aws-sdk/lib/aws.js': ['Lambda'] }
})]
```

**Comment by Birowsky** [comment]
@guybedford the need to remember to declare all these named exports is what I would consider an unnecessary worry.

**Comment by guybedford** [comment]
Expanding the static exports extraction is definitely important, and can be tracked at the commonjs plugin repo.
