### ISSUE TITLE
Error: An unexpected situation arose

### ISSUE THREAD

**Issue by vc1** [rollup/rollup#1927]
error info
```bash
> rollup -c

loaded rollup.config.js with warnings
(!) Unused external imports
default imported from external module 'rollup-plugin-uglify' but never used

./index.js → ./dist/bundle.js...
[!] (babel plugin) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
node_modules\_request-promise-native@1.0.5@request-promise-native\lib\rp.js
Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
    at error (D:\Users\x\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:170:15)
    at Object.error (D:\Users\x\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:17506:21)
    at D:\Users\x\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:17515:29
    at <anonymous>
```
https://github.com/request/request-promise-native/blob/master/lib/rp.js

rollup.config.js
```js
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import babel from 'rollup-plugin-babel'
import uglify from 'rollup-plugin-uglify'
import json from 'rollup-plugin-json'
import pkg from './package.json'

export default {
  input: './index.js',
  output: {
    name: 'music',
    file: pkg.main,
    format: 'cjs',
    sourcemap: true,
    banner: '/* my-library */\n\n'
  },
  watch: {
    include: './src/**'
  },
  plugins: [
    json(),
    resolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      preferBuiltins: true
    }),
    commonjs({
      include: 'node_modules/**',
      exclude: ['node_modules/foo/**', 'node_modules/bar/**'],
      ignore: ['conditional-runtime-dependency']
    }),
    babel()
    // uglify({
    //   mangle: true,
    //   sourceMap: true
    // }),
  ]
}
```

.babelrc
```json
{
    "comments": true,
    "presets": [
        [
            "env",
            {
                "modules": false,
                "useBuiltIns": true,
                "targets": {
                    "node": "current"
                }
            }
        ]
    ],
    "plugins": [
        "external-helpers",
        "closure-elimination",
        "transform-object-rest-spread",
        "transform-class-properties",
        "transform-exponentiation-operator",
        "transform-function-bind",
        "transform-decorators",
        "transform-strict-mode", 
        [
            "module-resolver",
            {
                "root": [
                    "./src"
                ],
                "alias": {
                    "~": "./src"
                }
            }
        ]
    ],
    "ignore": [
        "node_modules/**",
        "foo.js",
        "bar/**/*.js",
        "userDataDir",
        "tmp",
        "image",
        "download",
        "dist",
        "_src"
    ],
    "sourceMaps": "both"
}
```

node v9.2.0
npm  v5.6.0

**Comment by lukastaegert** [comment]
You need rollup-plugin-json to load JSON files

**Comment by vc1** [comment]
@lukastaegert reply so fast
There was a new problem, I just updated the issue

**Comment by vc1** [comment]
solved   use babel before commonjs
rollup.config.js
```js
 plugins: [
    json(),
    resolve(),
    babel()
    commonjs()
 ]
```
