### ISSUE TITLE
Error: Unexpected token }

### ISSUE THREAD

**Issue by allexcd** [rollup/rollup#2054]
Build fails with `Unexpected token }`

```js
C:\[project-name]\node_modules\rollup\bin\rollup:2471
});
^

SyntaxError: Unexpected token }
   at new Script (vm.js:51:7)
   at createScript (vm.js:138:10)
   at Object.runInThisContext (vm.js:199:10)
   at Module._compile (module.js:624:28)
   at Object.Module._extensions..js (module.js:671:10)
   at Module.load (module.js:573:32)
   at tryModuleLoad (module.js:513:12)
   at Function.Module._load (module.js:505:3)
   at Function.Module.runMain (module.js:701:10)
   at startup (bootstrap_node.js:190:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

`rollup.config.js` looks like this:

```js
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';

export default {
    input: 'src/index.js',
    plugins: [
        nodeResolve(),
        commonjs(),
        babel(),
        uglify()
    ],
    output: {
        file: 'dist/bundle.js',
        format: 'umd',
        name: 'bundle',
        sourcemap: false
    }
};
```

Rollup version: 0.56.5
OS: Windows 10 Pro x64
Node: 9.5.0 / also tried with Node 8.9.1

I have commented all the project code and still get this error. I've also tried downgrade, version by version until `0.47.0` which seems to give me different errors

None of the solutions mentioned above worked for me in a Windows environment. Hope someone has some clue about what it might happen.

**Comment by TrySound** [comment]
Did you mean 0.56.5?

**Comment by allexcd** [comment]
Sorry. Yes, rollup version 0.56.5 I've updated the previous comment with the proper version.
I've tried downgrading the rollup version and the error was triggered by each version. The only version that didn't trigger that error during build was 0.47.0.

I've also got the same `Unexpected token }` for a simple project like this one:

`index.js`

```js
function x (){console.log("test")}
x()
```

`package.json`

```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "rollup -c"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "rollup": "0.56.5"
  },
  "devDependencies": {
    "rollup": "0.56.5"
  }
}
```

`rollup.config.js`

```js
export default {
 input: 'src/index.js',
 output: {
        file: 'bundle.js',
        format: 'umd',
        name: 'bundle',
        sourcemap: false
    }
};
```

The debug log for this one looks like this:
```js
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle test@1.0.0~prebuild: test@1.0.0
6 info lifecycle test@1.0.0~build: test@1.0.0
7 verbose lifecycle test@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle test@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\[username]\Desktop\test\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Gradle\bin;C:\Program Files\nodejs\;C:\Users\[username]\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\[username]\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle test@1.0.0~build: CWD: C:\Users\[username]\Desktop\test
10 silly lifecycle test@1.0.0~build: Args: [ '/d /s /c', 'rollup -c' ]
11 silly lifecycle test@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle test@1.0.0~build: Failed to exec build script
13 verbose stack Error: test@1.0.0 build: `rollup -c`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid test@1.0.0
15 verbose cwd C:\Users\[username]\Desktop\test
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error test@1.0.0 build: `rollup -c`
22 error Exit status 1
23 error Failed at the test@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Also downgrading the rollup version up to `0.47.4`, I got a different error:

```js
C:\[project-name]\node_modules\rollup\bin\rollup:2663
var libretto = "libre
              ^^^^^^

SyntaxError: Invalid or unexpected token
   at new Script (vm.js:51:7)
   at createScript (vm.js:138:10)
   at Object.runInThisContext (vm.js:199:10)
   at Module._compile (module.js:624:28)
   at Object.Module._extensions..js (module.js:671:10)
   at Module.load (module.js:573:32)
   at tryModuleLoad (module.js:513:12)
   at Function.Module._load (module.js:505:3)
   at Function.Module.runMain (module.js:701:10)
   at startup (bootstrap_node.js:190:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The debug log for this one looks like this:
```js
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle test@1.0.0~prebuild: test@1.0.0
6 info lifecycle test@1.0.0~build: test@1.0.0
7 verbose lifecycle test@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle test@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\[username]\Desktop\test\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Gradle\bin;C:\Program Files\nodejs\;C:\Users\[username]\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\[username]\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle test@1.0.0~build: CWD: C:\Users\[username]\Desktop\test
10 silly lifecycle test@1.0.0~build: Args: [ '/d /s /c', 'rollup -c' ]
11 silly lifecycle test@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle test@1.0.0~build: Failed to exec build script
13 verbose stack Error: test@1.0.0 build: `rollup -c`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid test@1.0.0
15 verbose cwd C:\Users\[username]\Desktop\test
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v9.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error test@1.0.0 build: `rollup -c`
22 error Exit status 1
23 error Failed at the test@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I've also updated npm to version `5.7.1` and still got the same issues

Then I've uninstalled `nodejs 9.5.0` and installed `nodejs 9.8.0` in a different location, not in `Program Files`. Got the same issues.

**Comment by TrySound** [comment]
@allexcd Can you send a few lines under and below this line in `node_modules/rollup/bin/rollup` files?

**Comment by allexcd** [comment]
```js
C:\Users\alex.dominguez\Desktop\test\node_modules\rollup\bin\rollup:2485
});
^

SyntaxError: Unexpected token }
   at new Script (vm.js:51:7)
   at createScript (vm.js:136:10)
   at Object.runInThisContext (vm.js:197:10)
   at Module._compile (module.js:613:28)
   at Object.Module._extensions..js (module.js:660:10)
   at Module.load (module.js:561:32)
   at tryModuleLoad (module.js:501:12)
   at Function.Module._load (module.js:493:3)
   at Function.Module.runMain (module.js:690:10)
   at startup (bootstrap_node.js:194:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[username]\AppData\Roaming\npm-cache\_logs\2018-03-14T09_52_32_865Z-debug.log
```

The code from lines 2480 - 2519:

```js
return {
       inputOptions: inputOptions,
       outputOptions: outputOptions,
       deprecations: deprecations,
       optionError: errors.length
           ? "Unknown option found: " + errors.join(', ') + ". Allowed keys: " + validKeys.join(', ')
           : null
   };
}
function deprecate(config, command, deprecateConfig) {
   if (command === void 0) { command = {}; }
   if (deprecateConfig === void 0) { deprecateConfig = { input: true, output: true }; }
   var deprecations = [];
   // CLI
   if (command.id) {
       deprecations.push({
           old: '-u/--id',
           new: '--amd.id'
       });
       (command.amd || (command.amd = {})).id = command.id;
   }
   if (typeof command.output === 'string') {
       deprecations.push({
           old: '--output',
           new: '--output.file'
       });
       command.output = { file: command.output };
   }
   if (command.format) {
       deprecations.push({
           old: '--format',
           new: '--output.format'
       });
       (command.output || (command.output = {})).format = command.format;
   }
   // config file
   deprecations.push.apply(deprecations, deprecateOptions(config, deprecateConfig));
   return deprecations;
}
```

The exact code on line 2485 is:
```js
? "Unknown option found: " + errors.join(', ') + ". Allowed keys: " + validKeys.join(', ')
```

**Comment by allexcd** [comment]
I've also tried with six Windows environments (same Windows 10 Pro x64, same `node` and `npm` versions). It fails on five of them, it works on one. I also couldn't reproduce the bug on any Windows VM, using VirtualBox. I can't see any difference between the machines and I don't know what was left to try to understand why is this happening

**Comment by allexcd** [comment]
I have to come back with an explanation as I was struggling with this issue for a while. 

It seems that on some Windows environments there is an issue during node bootstrapping. The invoked libraries get truncated somehow. This issue is reproducible on some Windows environments and not reproducible on other Windows environments. Same Windows, same node version. But I couldn't find the reason behind this.

I've tried various things, like generating a `test.js` file with 100k console.logs and then `node test.js`. The issue was still in place. The issue was still reproducible when triggering rollup using: `node -c ./node_modules/rollup/dist/rollup.js` for instance, in order to bundle my project.

But the issue was gone when requiring that file using Node shell.

So for who's interested, see this: https://github.com/nodejs/node/blob/master/lib/internal/bootstrap/node.js#L215
Reading the file with `fs.readFileSync` and compiling with `vm` module. There might be some issue during the bootstrap process.

So, for those that might encounter this issue, a workaround for using rollup is requiring it and make use of its api:

1. Create a rollup config under `rollup.js` or whatever name you'd like

```js
const rollup = require('rollup');
const babel = require('rollup-plugin-babel');
const uglify = require('rollup-plugin-uglify');

(async () => {
	const bundle = await rollup.rollup({
		input: 'index.js',
		plugins: [
			babel(),
			uglify()
                       // ... etc
		],
	});
    await bundle.write({
        file: 'dist/bundle.js',
        format: 'umd'
        // ... etc
    });
})();
```

2. do this in `package.json`:

```json
"scripts": {
    "build": "node ./rollup.js"
  }
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
