### ISSUE TITLE
0.59.0 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by victoriafrench** [rollup/rollup#2192]
I have checked the changelog and do not see any breaking changes. Our codebase has been compiling on rollup for two years. I just attempted to upgrade from 0.58.2 and am getting `Maximum call stack size exceeded`:

```
RangeError: Maximum call stack size exceeded
    at LogicalExpression.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:15437:66)
    at LocalVariable.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:8081:26)
    at Identifier$$1.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:14181:34)
    at LogicalExpression.getLeftValue (node_modules/rollup/dist/rollup.js:15556:31)
    at LogicalExpression.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:15438:73)
    at LocalVariable.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:8081:26)
    at Identifier$$1.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:14181:34)
    at LogicalExpression.getLeftValue (node_modules/rollup/dist/rollup.js:15556:31)
    at LogicalExpression.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:15438:73)
    at LocalVariable.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:8081:26)
    at Identifier$$1.getLiteralValueAtPath (node_modules/rollup/dist/rollup.js:14181:34)
```

gulp task:

```
var gulp = require('gulp');
var path = require('path');
var rollup = require('rollup');
var rollupstream = require('rollup-stream');
var source = require('vinyl-source-stream');

gulp.task('build-reactkit', function () {
	return rollupstream({
		input: process.env.NODE_ENV === 'production' ? 'js-src/ReactKit/index.production.js' : 'js-src/ReactKit/index.development.js',
		rollup: rollup,
		external: [],
		plugins: [
			progress({
				clearLine: true
			}),
			nodeResolve({
				module: true,
				jsnext: true,
				main: true,
				browser: true,
				preferBuiltins: false,
				externals: []
			}),
			json(),
			filesize()
		],
		output: {
			file: path.join(__dirname, '../../public_html/js/reactkit.js'),
			format: 'iife',
			name: 'ReactKit',
			globals: {},
			sourcemap: false,
			strict: false,
			exports: 'none'
		}
	})
		.pipe(source(settings.outputName))
		.pipe(gulp.dest(settings.outputPath));
});
```

Entry file simply merges precompiled iife dependencies into one file (dev version uses unminified, production version brings in the min versions):

```
import 'firebase/firebase';
import 'redux/dist/redux';
import 'redux-logger/dist/redux-logger';
import 'redux-promise-middleware/dist/umd/redux-promise-middleware';
import 'redux-thunk/dist/redux-thunk';
import 'react/umd/react.development';
import 'prop-types/prop-types';
import 'react-dom/umd/react-dom.development';
import 'react-redux/dist/react-redux';
import 'radium/dist/radium';
```

Running on node 6.12.0 with npm 3.10.10 on darwin 10.13.4

**Comment by lukastaegert** [comment]
Hi @victoriafrench,
I am so sorry. I think this is a variation of an issue we had with other variable tracking optimizations in the past that bites us now. This is probably the simplest way of triggering it:

https://rollupjs.org/repl?version=0.59.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHglMjAlM0QlMjB5JTNCJTVDbnZhciUyMHklMjAlM0QlMjB4JTNCJTVDbmlmJTIwKHgpJTIwY29uc29sZS5sb2coMSklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==

Hope I can have a look soon so that we can fix this, should not be too difficult.

**Comment by funkybob** [comment]
I also ran into this this morning after upgrading to 0.59.0.

```
[!] RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at ConditionalExpression.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14877:70)
    at LocalVariable.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:8081:26)
    at Identifier$$1.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14181:34)
    at BinaryExpression.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14673:35)
    at ConditionalExpression.getTestValue (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14988:31)
    at ConditionalExpression.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14878:73)
    at LocalVariable.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:8081:26)
    at Identifier$$1.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14181:34)
    at BinaryExpression.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14673:35)
    at ConditionalExpression.getTestValue (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14988:31)
    at ConditionalExpression.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14878:73)
    at LocalVariable.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:8081:26)
    at Identifier$$1.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14181:34)
    at BinaryExpression.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14673:35)
    at ConditionalExpression.getTestValue (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14988:31)
    at ConditionalExpression.getLiteralValueAtPath (/home/curtis/src/git/tb/fe-rollup/node_modules/rollup/dist/rollup.js:14878:73)
```

**Comment by lukastaegert** [comment]
@victoriafrench @funkybob Could you please check if the issue is resolved when you install rollup via
`npm install rollup/rollup#circular-get-value`? Thanks!

**Comment by funkybob** [comment]
Works for me!

**Comment by victoriafrench** [comment]
Sorry wasn't available. I just pulled 0.59.1 and am confirming that it is indeed fixed here as well. -- Thanks!
