### ISSUE TITLE
https://rollupjs.org is down

### ISSUE THREAD

**Issue by tomByrer** [rollup/rollup#2204]
```shell
Error
Module build failed: TypeError: Cannot read property 'watchRun' of undefined
    at new VirtualModulesPlugin (/home/nowuser/src/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/home/nowuser/src/node_modules/svelte-loader/index.js:83:46)
    at new VirtualModulesPlugin (/home/nowuser/src/node_modules/svelte-loader/lib/virtual.js:35:17)
    at Object.module.exports (/home/nowuser/src/node_modules/svelte-loader/index.js:83:46)
    at Object.module.exports.Object.defineProperty.value (/home/nowuser/src/.sapper/server/main.75836b2a24015baaa293.js:170:7)
    at __webpack_require__ (/home/nowuser/src/.sapper/server/main.75836b2a24015baaa293.js:21:30)
    at Object.module.exports.Object.defineProperty.value (/home/nowuser/src/.sapper/server/main.75836b2a24015baaa293.js:116:99)
    at __webpack_require__ (/home/nowuser/src/.sapper/server/main.75836b2a24015baaa293.js:21:30)
    at /home/nowuser/src/.sapper/server/main.75836b2a24015baaa293.js:64:18
    at Object. (/home/nowuser/src/.sapper/server/main.75836b2a24015baaa293.js:67:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

Thanks for rollup! :)

**Comment by petrleocompel** [comment]
Your issue is duplicate -> #2200

**Comment by lukastaegert** [comment]
Sorry for the inconvenience. @Rich-Harris is working on a fix at rollup/rollupjs.org#135 but it will take a little while longer due to time-constraints on his side.
