### ISSUE TITLE
version 0.60.0 broke rollup-analyzer plugin

### ISSUE THREAD

**Issue by jharris4** [rollup/rollup#2245]
I filed an issue with [rollup-analyzer-plugin](https://github.com/doesdev/rollup-analyzer-plugin/issues/2). It seems that something in rollup version 0.60.0 has broken that plugin.

Filing an issue here in case someone can suggest a fix, in which case I'd be happy to create a PR to that plugin to fix it...

**Comment by jharris4** [comment]
Oh, and here's the error stack trace that I posted in the plugin issue:

```
TypeError: Cannot read property 'modules' of undefined
    at Promise (/Source/project/node_modules/rollup-analyzer/index.js:46:26)
    at new Promise (<anonymous>)
    at analyze (/Source/project/node_modules/rollup-analyzer/index.js:45:10)
    at Object.formatted (/Source/project/node_modules/rollup-analyzer/index.js:40:36)
    at Object.ongenerate (/Source/project/node_modules/rollup-analyzer-plugin/index.js:14:29)
    at /Source/project/node_modules/rollup/dist/rollup.js:21676:58
    at Array.map (<anonymous>)
    at /Source/project/node_modules/rollup/dist/rollup.js:21675:34
```

**Comment by doesdev** [comment]
I would say this issue can be closed, part of the API changes that caused this to break were due to changes I requested here to enable treeshaking analysis. I'll have a release out of rollup-analyzer this evening that fixes this.

**Comment by jharris4** [comment]
Yep, thanks for the follow up, I'll close the issue.
