### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'signedAttrs' in undefined

### ISSUE THREAD

**Issue by YuryStrozhevsky** [rollup/rollup#2337]
I had been using `Rollup` in a number of my projects for years and all was normal utill latest release `0.63.0`. So, [here is the code](https://github.com/PeculiarVentures/CAdES.js/tree/master/examples/CAdESComplexExample) which I would like to compile using `Rollup`. But when I am trying this I have error:
```text
A:\_Work\PROG\Ryan\CAdES.js>npm run build:examples

> cadesjs@1.0.11 build:examples A:\_Work\PROG\Ryan\CAdES.js
> npm run ex1


> cadesjs@1.0.11 ex1 A:\_Work\PROG\Ryan\CAdES.js
> cd examples/CAdESComplexExample && npm run build && cd ../..


> @ build A:\_Work\PROG\Ryan\CAdES.js\examples\CAdESComplexExample
> rollup -c && sed -f ../script.sed  es6.js > ../../test/cadesComplexExample.js


es6.js → bundle.js, ../../test/browser/cadesComplexExample.js...
[!] TypeError: Cannot use 'in' operator to search for 'signedAttrs' in undefined
TypeError: Cannot use 'in' operator to search for 'signedAttrs' in undefined
    at in (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:10137:46)
    at BinaryExpression.getLiteralValueAtPath (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:10157:16)
    at IfStatement.bind (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:10781:40)
    at BlockStatement$$1.NodeBase.bind (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:9111:31)
    at ForOfStatement$$1.NodeBase.bind (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:9115:23)
    at ForOfStatement$$1.bind (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:10709:31)
    at BlockStatement$$1.NodeBase.bind (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:9111:31)
    at FunctionDeclaration$$1.NodeBase.bind (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:9115:23)
    at Program.NodeBase.bind (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:9111:31)
    at Module.bindReferences (A:\_Work\PROG\Ryan\CAdES.js\node_modules\rollup\dist\rollup.js:13351:18)
```
With `0.60.0` version everything is fine. Could you, please, advice me what is wrong here?

**Comment by lukastaegert** [comment]
Looks like an internal error, thanks for the issue! Will need to do a little digging.

**Comment by YuryStrozhevsky** [comment]
@lukastaegert Thanks for the fix. When I can expect a release of `Rollup` with the fix?

**Comment by lukastaegert** [comment]
Now :)

**Comment by YuryStrozhevsky** [comment]
@lukastaegert Thank you for the fast fixing Rollup, really appreciated :)
