### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'selectionStart in null

### ISSUE THREAD

**Issue by amacleay** [rollup/rollup#2342]
Similar to #2337 but not resolved by #2338.

After upgrading to v0.16.0 (and .1 and .2), I now get the following error compiling my project:
```
TypeError: Cannot use 'in' operator to search for 'selectionStart' in null
    at in (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:10137:46)
```
I trace this to the minified version of this code in `react-dom`:
https://github.com/facebook/react/blob/72434a7686035b4af766ee7d06c070d7f5d6a5f2/packages/react-dom/src/events/SelectEventPlugin.js#L66

I'm able to reproduce in a unit test on the rollup project, which I have demoed in #2343 (a do-not-merge PR to add the test)

Full error text:
```
$ rollup -c docs/rollup.config.js

docs/index.tsx → docs/dist/index.js...
[!] TypeError: Cannot use 'in' operator to search for 'selectionStart' in null
TypeError: Cannot use 'in' operator to search for 'selectionStart' in null
    at in (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:10137:46)
    at BinaryExpression.getLiteralValueAtPath (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:10157:16)
    at LogicalExpression.analyseBranchResolution (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:11127:35)
    at LogicalExpression.bind (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:11015:18)
    at ConditionalExpression.NodeBase.bind (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:9115:23)
    at ConditionalExpression.bind (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:10434:31)
    at ExpressionStatement$$1.NodeBase.bind (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:9115:23)
    at BlockStatement$$1.NodeBase.bind (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:9111:31)
    at FunctionDeclaration$$1.NodeBase.bind (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:9115:23)
    at Program.NodeBase.bind (/home/amacleay/src/cht-ng/cht-ui-component-lib/node_modules/rollup/dist/rollup.js:9111:31)

error Command failed with exit code 1.
```

**Comment by lukastaegert** [comment]
I think I got an idea what is going on. The issue is that in order to determine the value of binary expressions like `x + 1` or `"x" in y`, we use the value of the variable in question and just execute the expression. Which can fail for the `in` operator. Will add a check here.

**Comment by lukastaegert** [comment]
Fix at #2344.

**Comment by lukastaegert** [comment]
Again thanks for the test. Even though it did not directly help here, having a test is usually a great starting point for us that also really motivates us to dig into an issue quickly :)

**Comment by amacleay** [comment]
Thanks so much for resolving this so quickly!
