### ISSUE TITLE
How to upgrade rollup and dependencies

### ISSUE THREAD

**Issue by kopax** [rollup/rollup#2597]
We are trying to update our rollup and we encounter issues:

This was the dependencies used before upgrade:

```
"rollup": "^0.57.1",
    "rollup-plugin-babel": "^4.0.1",
    "rollup-plugin-cleanup": "^2.0.0",
    "rollup-plugin-commonjs": "^9.1.0",
    "rollup-plugin-inject": "^2.0.0",
    "rollup-plugin-json": "^2.3.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-replace": "^2.0.0",
    "rollup-plugin-uglify": "^3.0.0",
    "rollup-plugin-visualizer": "^0.5.0",
```

This is the dependency used after upgrade:

```
    "rollup": "^0.68.0",
    "rollup-plugin-babel": "^4.1.0",
    "rollup-plugin-cleanup": "^3.0.0",
    "rollup-plugin-commonjs": "^9.2.0",
    "rollup-plugin-inject": "^2.2.0",
    "rollup-plugin-json": "^3.1.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-resolve": "^4.0.0",
    "rollup-plugin-uglify": "^6.0.0",
    "rollup-plugin-replace": "^2.1.0",
    "rollup-plugin-terser": "^3.0.0",
    "rollup-plugin-visualizer": "^0.9.2",
```

- We have noticed a change of export for `rollup-plugin-uglify`

```
  1658 | 
> 1659 | export default ColorWrapper;
       |       ^ Unexpected token: keyword (default)
  1660 | export { ColorMock };
[!] (uglify plugin) Error: Unexpected token: keyword (default)
SyntaxError: Unexpected token: keyword (default)

```

Is there anything we should know before upgrading that far?

**Comment by lukastaegert** [comment]
Curious, you are using both uglify and terser, which is a fork of uglify adding ES6+ compatibility. I would only use terser.

**Comment by kopax** [comment]
Hi, this was a mistake. I am using `uglify` and I have read somewhere I needed to replace it to `terser` for some reason. I have removed the useless and unfinished, unrepaired implementation with `babel-plugin-terser`.

I am upgrading dependencies 1 by 1 and I have issues when:

## Rollup

- I **upgrade from** `0.59.4` **to ** `0.60.0`:
```

[!] TypeError: Cannot read property 'end' of undefined
TypeError: Cannot read property 'end' of undefined
```

**Comment by kopax** [comment]
Using rollup `0.68.0` If I do : 

```
npm uninstall --save-dev rollup-plugin-uglify
npm install --save-dev rollup-plugin-terser
```

and in `rollup.config.js`

```diff
- import { uglify } from "rollup-plugin-uglify";
+ import { terser } from "rollup-plugin-terser";

- if (prod) plugins.push(uglify(), visualizer({ filename: './bundle-stats.html' }));
+ if (prod) plugins.push(terser(), visualizer({ filename: './bundle-stats.html' }));
```

I have the following error: 

```
[!] (terser plugin) Error: Farm is ended, no more calls can be done to it
Error: Farm is ended, no more calls can be done to it
    at exports.default.end (/home/dka/workspace/github.com/bootstrap-styled/color/node_modules/rollup-plugin-terser/node_modules/jest-worker/build/index.js:166:13)
    at Object.generateBundle (/home/dka/workspace/github.com/bootstrap-styled/color/node_modules/rollup-plugin-terser/index.js:38:19)
    at /home/dka/workspace/github.com/bootstrap-styled/color/node_modules/rollup/dist/rollup.js:21948:25
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
````

**Comment by TrySound** [comment]
This is related only to uglify/terser plugin.

**Comment by chovy** [comment]
any idea how to upgrade all the rollup packages at once? Nothing works with node12 anymore.

**Comment by shellscape** [comment]
@chovy we.dont offer support in the issues here. read the readme for support options.
