### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#2625]
- Rollup Version: 1.0.0
- Operating System (or Browser):
- Node Version: 8.15

### How Do We Reproduce?

Don't know how yet. Will try to reproduce.

### Expected Behavior

No errors

### Actual Behavior

```
./src/index.js → build/static/js...
[!] TypeError: Cannot read property 'toString' of undefined
TypeError: Cannot read property 'toString' of undefined
    at Chunk.getRenderedHash (project/node_modules/rollup/dist/rollup.js:15468:41)
    at project/node_modules/rollup/dist/rollup.js:15513:33
    at Chunk.visitDependencies (project/node_modules/rollup/dist/rollup.js:15493:13)
    at Chunk.computeContentHashWithDependencies (project/node_modules/rollup/dist/rollup.js:15509:14)
    at project/node_modules/rollup/dist/rollup.js:15731:34
    at project/node_modules/rollup/dist/rollup.js:14863:27
    at String.replace (<anonymous>)
    at renderNamePattern (project/node_modules/rollup/dist/rollup.js:14862:20)
    at Chunk.generateId (project/node_modules/rollup/dist/rollup.js:15726:30)
    at assignChunkIds (project/node_modules/rollup/dist/rollup.js:17660:19)
```

**Comment by lukastaegert** [comment]
Thanks, your findings were very helpful! Fix at #2638

**Comment by TrySound** [comment]
Great! Thank you!

**Comment by anualias1997** [comment]
sfsdfsdss
