### ISSUE TITLE
Rollup with gulp and typescript outputs Cannot find module 'tslib/tslib.es6.js'

### ISSUE THREAD

**Issue by stephenbe** [rollup/rollup#2830]
I submitted my problem in gitter and in stackoverflow before submitting this bug and no one seem to have an answer.

- Rollup Version:^1.10.1
- Operating System (or Browser): Windows 10
- Node Version:v8.9.4

I am using gulp + rollup with typescript as shown here : 
https://rollupjs.org/guide/en#gulp

### How Do We Reproduce?

Packages.json : 
```
{
  "name": "rollupa",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^4.0.1",
    "rollup-plugin-babel": "^4.3.2"
  },
  "dependencies": {
    "rollup": "^1.10.1",
    "rollup-plugin-typescript": "^1.0.1",
    "typescript": "^3.4.5"
  }
}
```

Gulp file 
```
const gulp = require("gulp");
const rollup = require("rollup");
const rollupTypescript = require("rollup-plugin-typescript");

gulp.task("build", () => {
  return rollup
    .rollup({
      input: "./main.ts",
      plugins: [rollupTypescript()]
    })
    .then(bundle => {
      return bundle.write({
        file: "./main.js",
        format: "umd",
        name: "library",
        sourcemap: true
      });
    });
});
```

tsconfig
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es5", "dom"]
  }
}

```

main.ts
```
class Menu {
  constructor(container, options) {
    this.init();
  }

  init() {
    alert("hey");
  }
}

export default Menu;

```

### Expected Behavior
When I do gulp build it should build main.js without errors and transfer my classes to es5.

### Actual Behavior
It's giving me this error : 
```
Error: Cannot find module 'tslib/tslib.es6.js' from 'C:\projets\Tests\rollup\node_modules\rollup-plugin-typescript\dist'
    at Function.module.exports [as sync] (C:\projets\Tests\rollup\node_modules\resolve\lib\sync.js:58:15)
    at typescript (C:\projets\Tests\rollup\node_modules\rollup-plugin-typescript\dist\rollup-plugin-typescript.cjs.js:109:29)
    at gulp.task (C:\projets\Tests\rollup\gulpfile.js:9:17)
    at taskWrapper (C:\projets\Tests\rollup\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (C:\projets\Tests\rollup\node_modules\async-done\index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

Thanks!

**Comment by manucorporat** [comment]
You need to install tslib as dependency

**Comment by stephenbe** [comment]
Thanks it worked

It was actually looking for it in 
Error: Cannot find module 'tslib/tslib.es6.js' from **'\node_modules\rollup-plugin-typescript\dist'**

so I was thinking it was a missing dependency from there.
