### ISSUE TITLE
acornInjectPlugins with acorn-private-methods "Error: acorn-private-class-elements does not support mixing different acorn copies" error 

### ISSUE THREAD

**Issue by alexgwolff** [rollup/rollup#2878]
- Rollup Version: 1.12.4
- Operating System (or Browser): Windows 1903
- Node Version: v12.1.0

### How Do We Reproduce?
```javascript
import acornPrivateMethods from 'acorn-private-methods';

export default {
  acornInjectPlugins: [ acornPrivateMethods],

  input: 'src/index.js',

  output: {
    file: 'dist/bundle.js',
    format: 'esm'
  }
};
```

### Actual Behavior
[!] Error: acorn-private-class-elements does not support mixing different acorn copies
Error: acorn-private-class-elements does not support mixing different acorn copies
    at module.exports (D:\projects\lab\web components\angular\node_modules\acorn-private-class-elements\index.js:23:11)
    at Array.module.exports (D:\projects\lab\web components\angular\node_modules\acorn-private-methods\index.js:6:26)
    at Function.extend (C:\Users\alexg\AppData\Local\Yarn\Data\global\node_modules\acorn\src\state.js:107:62)
    at new Graph (C:\Users\alexg\AppData\Local\Yarn\Data\global\node_modules\rollup\dist\rollup.js:16242:41)
    at Object.rollup (C:\Users\alexg\AppData\Local\Yarn\Data\global\node_modules\rollup\dist\rollup.js:16871:23)
    at build (C:\Users\alexg\AppData\Local\Yarn\Data\global\node_modules\rollup\bin\rollup:964:19)
    at C:\Users\alexg\AppData\Local\Yarn\Data\global\node_modules\rollup\bin\rollup:1683:24

**Comment by calebdwilliams** [comment]
Since it's been awhile, I wanted to bump this as I'm currently having this issue as well. @alexgwolff were you able to resolve this or is this on Rollup's roadmap?

**Comment by alexgwolff** [comment]
Hey man, you need inject other plugins. 
You can see a example here: https://github.com/struct-js/struct/blob/master/struct-core/rollup.config.dev.js

**Comment by calebdwilliams** [comment]
Hey, thanks for the quick response. I already have most of those, but I'm running into the error below:

`Error: acorn-private-class-elements requires acorn@^6.1.0, not 7.1.0`

If I try to install `acorn@6.1.0`, I get your original error: `Error: acorn-private-class-elements does not support mixing different acorn copies`.

**Comment by 0biWanKenobi** [comment]
This still happens..
