### ISSUE TITLE
Using with ttypescript and typescript-transform-paths for tsconfig paths

### ISSUE THREAD

**Issue by viT-1** [rollup/rollup#3070]
- Rollup Version: 1.17.0

### How Do We Reproduce?
```
// gulpfile.js
const rolTts = require('ttypescript');
const rolTypescript = require('rollup-plugin-typescript2');

// rollup conf:
plugins: [rolTypescript({
tsconfig: './src/tsconfig.json',
typescript: rolTts,
}]

//src/tsconfig.json compilerOptions:
"baseUrl": ".",
"paths": {
"@common/*": [ "./common.blocks/*" ]
},
"plugins": [ { "transform": "typescript-transform-paths" } ]

// some [ts module](https://github.com/viT-1/systemjs-ts-es6/blob/master/src/main.ts)
import SomeComponent from '@common/SomeComponent';
```

### Expected Behavior
rollup is Ok with sources

### Actual Behavior
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
    at error (C:\Projects\...\node_modules\rollup\dist\rollup.js:9408:30)
    at Module.error (C:\Projects\...\node_modules\rollup\dist\rollup.js:13347:9)
    at tryParse (C:\Projects\...\node_modules\rollup\dist\rollup.js:13262:16)
    at Module.setSource (C:\Projects\...\node_modules\rollup\dist\rollup.js:13573:33)
    at Promise.resolve.catch.then.then.then (C:\Projects\...\node_modules\rollup\dist\rollup.js:16398:20)

**Comment by viT-1** [comment]
related: https://github.com/ezolenko/rollup-plugin-typescript2/issues/164

**Comment by shellscape** [comment]
@viT-1 thanks for opening an issue. for future issues, please do not remove portions of the issue template. that information is requested to help making your issue easier to triage for maintainers.

**Comment by viT-1** [comment]
**tt**ypescipt in header wasn't typo
