### ISSUE TITLE
createFilter incorrect resolves transformations

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup#310]
```
const absolutePath = /^(?:\/|(?:[A-Za-z]:)?[\\|\/])/;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\_host\github\rollup\test\test.js:10:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at D:\_host\github\rollup\node_modules\mocha\lib\mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\_host\github\rollup\node_modules\mocha\lib\mocha.js:213:14)
    at Mocha.run (D:\_host\github\rollup\node_modules\mocha\lib\mocha.js:453:10)
    at Object.<anonymous> (D:\_host\github\rollup\node_modules\mocha\bin\_mocha:393:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by eventualbuddha** [comment]
Are you using `rollup-plugin-babel`? If not, rollup won't do anything to transform `const` to `var`.

**Comment by TrySound** [comment]
@eventualbuddha It's rollup itself. I can't test it

**Comment by eventualbuddha** [comment]
What version of node, rollup, etc?

**Comment by TrySound** [comment]
node0.12, frash pull from original master

**Comment by TrySound** [comment]
Maybe something wrong with rollup-plugin-babel1?

**Comment by eventualbuddha** [comment]
I'm having trouble reproducing this. Can you provide a specific command that fails?

**Comment by TrySound** [comment]
No fail, just npm run build gives me code with constants

**Comment by TrySound** [comment]
Of course tests fails after this

**Comment by TrySound** [comment]
@eventualbuddha Let don't transpiller too.

**Comment by TrySound** [comment]
@eventualbuddha Here's output after cloning original repo and running npm install.
https://gist.github.com/TrySound/bd9a0dffc256ac80f3dc

**Comment by Victorystick** [comment]
@TrySound I can't reproduce this in Node v5.0.0. Have you run `npm install` recently to fetch the latest dependencies?

**Comment by TrySound** [comment]
@Victorystick Which os did you try?

**Comment by Victorystick** [comment]
OSX, I'm afraid.

**Comment by TrySound** [comment]
@Victorystick On *nix everything is okay. This problem is just on windows.

**Comment by TrySound** [comment]
@Victorystick Maybe try update with babel6?

**Comment by t128** [comment]
@TrySound so it's an easy fix? just upgrade your OS :)

**Comment by TrySound** [comment]
@t128 With win10? No.

**Comment by TrySound** [comment]
Fixed with https://github.com/rollup/rollup-pluginutils/pull/1
/cc @eventualbuddha @Victorystick @Rich-Harris
