### ISSUE TITLE
mocha fails due to missing module

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollup#325]
I'm trying to `npm link` my local clone of rollup so I can use it globally.

It's getting stuck at `npm test`, which gives this:

```
Error: Cannot find module '/Users/callum/code/rollup/test/form/exported-empty-vars/_config'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/callum/code/rollup/test/test.js:222:17
    at Array.forEach (native)
    at Suite.<anonymous> (/Users/callum/code/rollup/test/test.js:219:37)
    at context.describe.context.context (/Users/callum/code/rollup/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Suite.<anonymous> (/Users/callum/code/rollup/test/test.js:218:2)
    at context.describe.context.context (/Users/callum/code/rollup/node_modules/mocha/lib/interfaces/bdd.js:47:10)
    at Object.<anonymous> (/Users/callum/code/rollup/test/test.js:39:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/callum/code/rollup/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/callum/code/rollup/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/Users/callum/code/rollup/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/Users/callum/code/rollup/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

It's strange because your Travis build is green. Could it be because I'm on Node 5 and npm 3?

**Comment by callumlocke** [comment]
ok I see what's happened... the directory `test/form/exported-empty-vars` has apparently been removed in a recent commit, but its `_actual` subfolder has been retained due to a line in .gitignore, and this means the `exported-empty-vars` exists even though the `_config` file inside it has been removed, which is confusing the tests.

solution: delete rollup and clone it again

**Comment by Rich-Harris** [comment]
> solution: delete rollup and clone it again

![it-crowd](https://cloud.githubusercontent.com/assets/1162160/11449890/10741926-9556-11e5-92ab-abfb61eae340.gif)

I get caught out by this from time to time... maybe we should just fix test.js so it doesn't complain
