### ISSUE TITLE
Confusing error: "Cannot read property 'type' of null"

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollup#326]
I was trying out rollup on an old ES6 project.

I got this error:

```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at Object.walk.enter (/Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/src/ast/attachScopes.js:60:68)
    at visit (/Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/node_modules/estree-walker/dist/estree-walker.es6.js:27:9)
    at walk (/Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/node_modules/estree-walker/dist/estree-walker.es6.js:5:2)
    at attachScopes (/Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/src/ast/attachScopes.js:11:19)
    at Statement.firstPass (/Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/src/Statement.js:59:42)
    at /Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/src/Module.js:162:14
    at Array.forEach (native)
    at Module.analyse (/Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/src/Module.js:158:19)
    at new Module (/Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/src/Module.js:53:8)
    at /Users/callum.locke/code/rollup/Users/callum.locke/code/rollup/src/Bundle.js:155:20
```

There's no way to tell which module was being processed at the time of this error. But the stack trace starts at [this line in rollup](https://github.com/rollup/rollup/blob/d35ffb156568ed1294b9b9961e1c54f48b36ce3c/src/ast/attachScopes.js#L47), I believe the problem is that `parent` is sometimes null.

I tried changing the line as follows and rebuilding my copy of rollup:

```js
if ( node.type === 'BlockStatement' && (!parent || !/Function/.test( parent.type )) ) {
```

and that seems to solve my problem. (But I'm hesitant to PR this small fix in case there's a wider problem)

**Comment by Rich-Harris** [comment]
Ah, interesting – presumably you have a top-level block statement?

```js
{
  let foo = 99;
  // ...
}
```

That seems like the correct fix to me. Workaround in the meantime would be to add an `if (true)` before the opening brace.

**Comment by callumlocke** [comment]
That was it, thanks!
