### ISSUE TITLE
Errors about octal literal in strict mode when repository path contains "\13" or another number

### ISSUE THREAD

**Issue by zleight1** [rollup/rollup#3260]
- Rollup Version: 1.27.5
- Operating System (or Browser): Windows 10
- Node Version: 10.16.x

### How Do We Reproduce?

Create a Vue ESM build and run the build in a directory that contains a `\<number>` that would be considered an octal literal.

For example:

```
C:\work\13\ <-- or any sub folder 
cd C:\work\13
npm run build:rollup
```

### Expected Behavior
The build will work and output the esm built files.

### Actual Behavior
Error about object literal in strict mode on a .vue file
Example:
```
PS C:\Users\zachary\Source\Repos\13> npm run build:esm

> @tipalti/vue-controls@3.3.5 build:esm C:\Users\zachary\Source\Repos\13
> rollup -c --environment BUILD:production
index.js, src/components/TipMultiSelect.vue, src/components/datePickers/TipDatepicker.vue, src/components/TipChecker.vue, src/components/TipLoader.vue, src/components/TipModal.vue, src/components/TipDialog.vue, src/components/TipValueLoader.vue, src/components/TipValuesLoader.vue, src/components/TipSimpleDataGrid.vue, src/components/TipTextInput.vue, src/components/TipConfirmButtons.vue, src/components/TipConfirmCancel.vue, src/components/TipRadioGroup.vue, src/components/TipAsyncRadioGroup.vue, src/components/TipOnDemand.vue, src/components/TipAsyncText.vue, src/components/TipPaginationButtons.vue, src/components/TipAsyncSelect.vue, src/components/TipToggle.vue, src/components/TipAsyncToggle.vue, src/components/TipDynamicDataGrid.vue, src/components/TipDataGrid.vue, src/components/TipAdvancedFilters.vue, src/components/TipCheckerGroup.vue, src/components/TipAsyncCheckerGroup.vue, src/components/TipPdfViewer.vue → dist/esm...(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.src\components\TipLoader.vue: (23:62)
[!] Error: Octal literal in strict mode (Note that you need plugins to import files that are not JavaScript)
21:         circle: {
                               ^
24:         },
25:         color: {
Error: Octal literal in strict mode (Note that you need plugins to import files that are not JavaScript)
    at error (C:\Users\zachary\Source\Repos\13\node_modules\rollup\dist\rollup.js:5330:30)
    at Module.error (C:\Users\zachary\Source\Repos\13\node_modules\rollup\dist\rollup.js:9605:9)
    at tryParse (C:\Users\zachary\Source\Repos\13\node_modules\rollup\dist\rollup.js:9516:16)
    at Module.setSource (C:\Users\zachary\Source\Repos\13\node_modules\rollup\dist\rollup.js:9834:33)
    at Promise.resolve.catch.then.then.then (C:\Users\zachary\Source\Repos\13\node_modules\rollup\dist\rollup.js:12614:20)
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Please add a proper reproduction:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Work to isolate the problem and provide the exact steps in this issue, or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

**Comment by mika76** [comment]
Wow, I think I just hit upon this issue using vite 2.7.1 and pnpm on windows...

I have a build server using TFS which runs builds in a path like `C:\agent\_work\36\s` and I kept getting the same above octal error. I changed the above to `C:\agent\_work\thirtysix\s`and it built fine...

Then, I renamed it back to the number `...\36\s` and then built again and got the octal error again...

(I had to rerun `pnpm i` after every folder name change)

I'll try put a reproduction repo together...

```
+ envinfo 7.8.1

  System:
    OS: Windows 10 10.0.19043
    CPU: (2) x64 Common KVM processor
    Memory: 333.23 MB / 4.00 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.5.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 6.23.6
  Browsers:
    Chrome: 96.0.4664.93
    Edge: Spartan (44.19041.1266.0), Chromium (94.0.992.31)
    Internet Explorer: 11.0.19041.1202
```

**Comment by roydukkey** [comment]
This issue is also reproducible when a RegExp contains the same pattern.
