### ISSUE TITLE
Rollup Failed to Build an Ordinary CJS Module (Failed to tryParse module.exports)

### ISSUE THREAD

**Issue by ryanelian** [rollup/rollup#3304]
- Rollup Version: 1.27.14
- Operating System (or Browser): Microsoft Windows [Version 10.0.18363.535]
- Node Version: v12.14.0

### How Do We Reproduce?

```
  "scripts": {
    "build": "tsc && rollup -c"
  },
  "dependencies": {
    "core-js": "^3.6.0"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^11.0.0",
    "@rollup/plugin-node-resolve": "^6.0.0",
    "rollup": "^1.27.14",
    "rollup-plugin-terser": "^5.1.3",
    "typescript": "3.7.4"
  }
```

```js
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import { terser } from 'rollup-plugin-terser';

export default {
    input: './lib/index.js',
    output: [{
        file: './dist/ts-polyfill.js',
        format: 'iife',
        name: 'tsPolyfill'
    }, {
        file: './dist/ts-polyfill.min.js',
        format: 'iife',
        name: 'tsPolyfill',
        sourcemap: true,
        plugins: [terser()]
    }],
    plugins: [resolve(), commonjs()]
}
```

The source code in question is in this repository, although changes uncommitted because of the failed build: https://github.com/ryanelian/ts-polyfill

### Expected Behavior

Rollup builds the bundle successfully.

### Actual Behavior

```bash
> tsc && rollup -c


./lib/index.js → ./dist/ts-polyfill.js, ./dist/ts-polyfill.min.js...
[!] Error: Unexpected token
node_modules\core-js\es\number\is-finite.js (4:14)
2: var path = require('../../internals/path');
3:
4: module.exports = path.Number.isFinite;
                 ^
Error: Unexpected token
    at error (D:\VS\ts-polyfill\node_modules\rollup\dist\rollup.js:5365:30)
    at Module.error (D:\VS\ts-polyfill\node_modules\rollup\dist\rollup.js:9708:9)
    at tryParse (D:\VS\ts-polyfill\node_modules\rollup\dist\rollup.js:9617:16)
    at Module.setSource (D:\VS\ts-polyfill\node_modules\rollup\dist\rollup.js:9935:33)
    at D:\VS\ts-polyfill\node_modules\rollup\dist\rollup.js:12205:20
    at async Promise.all (index 32)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

Why Rollup failed to parse `module.exports`? Are there newer configuration to enable this behavior?

**Comment by shellscape** [comment]
@ryanelian Thanks for opening an issue. I've moved this to the plugins repo since it appears to be an issue with the commonjs plugin and not rollup core. We're going to need you to break this down into a minimal reproducible repository to triage. The code between the last version of `rollup-plugin-commonjs` and `@rollup/plugin-commonjs` should be identical.
