### ISSUE TITLE
 Error: You must specify "output.format", which can be one of "amd", "cjs", "system", "esm", "iife" or "umd".

### ISSUE THREAD

**Issue by catamphetamine** [rollup/rollup#3311]
For some reason it doesn't see the `output.format` in the config file.

Output:

```
> rollup rollup.config.js


rollup.config.js → stdout...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
rollup-plugin-json (imported by rollup.config.js)
rollup-plugin-terser (imported by rollup.config.js)
[!] Error: You must specify "output.format", which can be one of "amd", "cjs", "system", "esm", "iife" or "umd".
https://rollupjs.org/guide/en/#output-format
Error: You must specify "output.format", which can be one of "amd", "cjs", "system", "esm", "iife" or "umd".
    at error (c:\dev\react-phone-number-input\node_modules\rollup\dist\rollup.js:5365:30)
    at checkOutputOptions (c:\dev\react-phone-number-input\node_modules\rollup\dist\rollup.js:13354:9)
    at normalizeOutputOptions (c:\dev\react-phone-number-input\node_modules\rollup\dist\rollup.js:13704:5)
    at getOutputOptionsAndPluginDriver (c:\dev\react-phone-number-input\node_modules\rollup\dist\rollup.js:13512:32)
    at Object.generate (c:\dev\react-phone-number-input\node_modules\rollup\dist\rollup.js:13577:63)
    at c:\dev\react-phone-number-input\node_modules\rollup\dist\bin\rollup:770:27
```

Config:

```js
import json from 'rollup-plugin-json'
import { terser } from 'rollup-plugin-terser'

export default [
  {
    input: 'min/index.js',
    plugins: [
      json(),
      terser()
    ],
    output: {
      format: 'umd',
      name: 'PhoneInput',
      file: 'bundle/react-phone-number-input.js',
      sourcemap: true,
      globals: {
        'react': 'React',
        'prop-types': 'PropTypes'
      }
    }
  }
]
```

**Comment by catamphetamine** [comment]
For some reason changing `rollup rollup.config.js` to `rollup --config rollup.config.js` seems to have fixed it.

**Comment by lukastaegert** [comment]
Yes, `rollup rollup.config.js` would try to bundle your config file with not configuration at all.
