### ISSUE TITLE
Build problem with @sentry/electron

### ISSUE THREAD

**Issue by sneltyn** [rollup/rollup#3323]
- Rollup Version: 1.28.0
- Operating System (or Browser):  Windows 10 Pro 1903
- Node Version: 10.16.3

#### 1. Install dependencies:

```sh
npm install @sentry/electron
npm install -D rollup @rollup/plugin-node-resolve @rollup/plugin-commonjs @rollup/plugin-json
```

#### 2. Create next files:

**rollup.config.js**

```js

import resolve from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import json from '@rollup/plugin-json';


export default {
  input: './sentry.js',
  output: {
    file: './dist/sentry.js',
    format: 'cjs',
    name: 'sentry'
  },
  plugins: [
    json(),
    commonjs(),
    resolve({ preferBuiltins: true, extensions: ['.js', '.json'] })
  ],
  external: [
    'electron'
  ]
}

```

**sentry.js**

```js
import { init } from '@sentry/electron/dist/main'

init({
  dsn: 'https://714f0b3734594219afc415a365937d9a@sentry.cloud/6',
  defaultIntegrations: false
  // ...
})
```

### Expected Behavior

Success entry build

### Actual Behavior

```
[!] Error: 'LRUMap' is not exported by node_modules\lru_map\lru.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules\@sentry\node\esm\parsers.js (3:9)
1: import { basename, dirname, snipLine, SyncPromise } from '@sentry/utils';
2: import { readFile } from 'fs';
3: import { LRUMap } from 'lru_map';
            ^
4: import * as stacktrace from './stacktrace';
5: // tslint:disable-next-line:no-unsafe-any
Error: 'LRUMap' is not exported by node_modules\lru_map\lru.js
    at error (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:5340:30)
    at Module.error (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:9730:9)
    at handleMissingExport (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:9644:21)
    at Module.traceVariable (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:10069:17)
    at ModuleScope.findVariable (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:8689:39)
    at Identifier$1.bind (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:4363:40)
    at NewExpression.bind (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:3112:23)
    at NewExpression.bind (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:7952:15)
    at VariableDeclarator.bind (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:3112:23)
    at VariableDeclaration.bind (C:\Users\sneltyn\Desktop\electron-rollup-kickstart\node_modules\rollup\dist\rollup.js:3108:31)
```

**Comment by sneltyn** [comment]
@lukastaegert look please

https://github.com/sneltyn/contrib-rollup-bug

**Comment by lukastaegert** [comment]
`lru_map` most likely declares its named exports in a way that cannot be detected by `@rollup/plugin-commonjs`. You should try the `namedExports` option of that plugin. We are working on a solution that will make this unnecessary in the future but for the time being, that is your best bet.
