### ISSUE TITLE
My Babel is configured with the @babel/plugin-proposal-class-properties plug-in, which allows you to use arrow functions in class under webpack, and error reports under rollup

### ISSUE THREAD

**Issue by Binote** [rollup/rollup#3337]
- Rollup Version:"^1.27.8"
- Operating System (or Browser):mac os 10.14.6
- Node Version:v10.16.0

### How Do We Reproduce?
```javascript
class A {
    a=() => {}
}
```

### Expected Behavior

Compiles arrow functions in class

#### Error message：
```
(node:10232) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token (9:5) in /Users/mac/code/wanwu-base-vue/example/main.js
    at Object.pp$4.raise (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:2836:15)
    at Object.pp.unexpected (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:689:10)
    at Object.pp.expect (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:683:28)
    at Object.pp$3.parseMethod (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:2620:10)
    at Object.pp$1.parseClassMethod (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:1387:25)
    at Object.pp$1.parseClassElement (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:1376:10)
    at Object.pp$1.parseClass (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:1315:26)
    at Object.pp$1.parseStatement (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:833:19)
    at Object.parseStatement (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/dist/rollup.js:11727:30)
    at Object.pp$1.parseTopLevel (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:746:23)
    at Object.parse (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:553:17)
    at Function.parse (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/node_modules/acorn/dist/acorn.js:576:37)
    at Graph.contextParse (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup/dist/rollup.js:13072:70)
    at tryParse (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:267:12)
    at checkEsModule (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:281:15)
    at Object.transformAndCheckExports (/Users/mac/.nvm/versions/node/v10.16.0/lib/node_modules/@wanwu/cli-plugin-rollup/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:762:30)
(node:10232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lukastaegert** [comment]
You need to use rollup-plugin-babel for Rollup to use Babel (or @rollup/plugin-babel, not sure if it migrated to the new repo yet). Vanilla Rollup only has support for stage-4 JavaScript

**Comment by lukastaegert** [comment]
Note that Rollup and Webpack have different philosophies and design goals. We do not promise or will ever promise Webpack compatibility, especially with regard to handling non-standard syntax.

**Comment by Binote** [comment]
I just tried to compile the same file using the same configured Babel command line, and it worked, but I reported the above error while using rollup and rollup-plugin-babel

**Comment by Binote** [comment]
I think you might need the version information for my current main package
### Version information for key packages:
```json
{
"@babel/helper-module-imports": "^7.7.4",
"@babel/plugin-proposal-class-properties": "^7.7.4",
"@babel/plugin-proposal-decorators": "^7.7.4",
"@babel/core": "^7.7.4",
"rollup-plugin-babel": "^4.3.3",
"rollup": "^1.27.8"
}
```

**Comment by lukastaegert** [comment]
You did not post your Rollup config, that would be crucial. Also your directory structure. A gist would be ideal.

**Comment by Binote** [comment]
My current network environment may not be able to open this site, perhaps I can give you some simple code examples

**Comment by Binote** [comment]
My current network environment may not be able to open this site, perhaps I can give you some simple code examples

**Comment by Binote** [comment]
A simple example configuration, use the @ vue/babel-preset-app as a preset, there is no other configuration, and compile only the simplest of js

```javascript
// rollup.config.js
module.exports = {
plugins: [
  babel({
    exclude: 'node_modules/**',
    extensions: ['.js', '.jsx', '.es6', '.es', '.mjs', '.vue'],
    runtimeHelpers: true,
    // @vue/babel-preset-app@3.12.1
    presets: [require('@vue/babel-preset-app')],
 }),
],
...
}

// input.js
class A {
 a: ()=>{}
}
export default A;
```

**Comment by Binote** [comment]
This is my repo, only the Babel plugin was compiled successfully, and the external configuration, commonjs plugin, and resolve plugin were added to solve the problem

https://repl.it/repls/WindingCrowdedSpyware

**Comment by lukastaegert** [comment]
Thanks, with the REPL the issue was easy to spot. rollup-plugin-commonjs needs to be able to parse files as JavaScript in order to transform them. This does not work if they contain non-standard syntax. If you sort the Babel plugin before the commonjs plugin, everything works.

I understand this is also a documentation issue. As this is not a Rollup core issue, you might consider opening an issue here so that it can help others, or even better, make a documentation PR that highlights the ordering issues between the commonjs and Babel plugin: https://github.com/rollup/plugins/tree/master/packages/commonjs

Additionally as commonjs is an important plugin, this could also be highlighted here: https://github.com/rollup/rollup-plugin-babel

**Comment by Binote** [comment]
Thank you, I have found the problem, which is caused by @rollup/plugin-commonjs and @rollup/plugin-node-resolve packages that do not recognize the syntax, just put the Babel plugin first
