### ISSUE TITLE
Using acorn-stage3 in acornInjectPlugins causes Error

### ISSUE THREAD

**Issue by DeltaFlush** [rollup/rollup#3405]
- Rollup Version: 1.31.1
- Operating System: Windows 10 x64 18362.657
- Node Version: v13.9.0
- Link to reproduction: <https://github.com/DeltaFlush/rollup-constructor-bug>

This is the same as <https://github.com/rollup/rollup/issues/3015> but that issue was closed by the person who made it with no reply.

### Expected Behavior

```
C:\rollup-constructor-bug>yarn rollup -c
yarn run v1.19.1
warning package.json: No license field
$ C:\rollup-constructor-bug\node_modules\.bin\rollup -c

input.js → stdout...

(!) Generated an empty chunk
input
created stdout in 14ms
Done in 0.22s.
```

### Actual Behavior

```
C:\rollup-constructor-bug>yarn rollup -c
yarn run v1.19.1
$ C:\rollup-constructor-bug\node_modules\.bin\rollup -c

input.js → stdout...
[!] Error: Class constructor  cannot be invoked without 'new'
Error: Class constructor  cannot be invoked without 'new'
    at error (C:\rollup-constructor-bug\node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at Module.error (C:\rollup-constructor-bug\node_modules\rollup\dist\shared\node-entry.js:9820:16)
    at tryParse (C:\rollup-constructor-bug\node_modules\rollup\dist\shared\node-entry.js:9713:23)
    at Module.setSource (C:\rollup-constructor-bug\node_modules\rollup\dist\shared\node-entry.js:10076:33)
    at C:\rollup-constructor-bug\node_modules\rollup\dist\shared\node-entry.js:12362:20
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by DeltaFlush** [comment]
This is `console.log` of `err` at `node-entry.js:9714` which provides additional info
```
TypeError: Class constructor  cannot be invoked without 'new'
    at new _class (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn-dynamic-import\lib\index.js:53:99)
    at new <anonymous> (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn-import-meta\index.js:15:10)
    at new <anonymous> (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn-bigint\index.js:8:10)
    at new Parser (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn-private-class-elements\index.js:26:12)
    at new <anonymous> (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn-class-fields\index.js:18:10)
    at new <anonymous> (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn-static-class-features\index.js:22:10)
    at new <anonymous> (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn-private-methods\index.js:8:10)
    at new <anonymous> (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn-export-ns-from\index.js:8:10)
    at Function.parse (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\acorn\dist\acorn.js:575:10)
    at tryParse (C:\Users\Admin\Documents\Projects\rollup-constructor-bug\node_modules\rollup\dist\shared\node-entry.js:9703:23)
```
