### ISSUE TITLE
Not accepting 'default' as output.exports when I have also named exports in module

### ISSUE THREAD

**Issue by fcole90** [rollup/rollup#3413]
- Rollup Version: v1.31.1
- Operating System (or Browser): Ubuntu 20.04 (daily)
- Node Version (if applicable): v13.8.0
- Link to reproduction: https://repl.it/@fcole90/GreenyellowCadetblueWaterfall

### Expected Behavior
To have the `default` being exported, ignoring the other exports.

So from ES6:
```
let bs = {};

// ... juicy stuff

export default bs;
export { bs };
```

to CJS:
```
main = {};
module.exports = main;
```

### Actual Behavior
Produces an error:
```
$ npm run build

> python_utils_for_js@0.1.0-alpha build /home/runner/GreenyellowCadetblueWaterfall
> rollup -c


/home/runner/GreenyellowCadetblueWaterfall/src/basic_utils.js → dist/basic_utils.node.js, dist/basic_utils.mjs...
[!] Error: "default" was specified for "output.exports", but entry module "src/basic_utils.js" has the following exports: bs, default
Error: "default" was specified for "output.exports", but entry module "src/basic_utils.js" has the following exports: bs, default
    at error (/home/runner/GreenyellowCadetblueWaterfall/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at getExportMode (/home/runner/GreenyellowCadetblueWaterfall/node_modules/rollup/dist/shared/node-entry.js:13532:20)
    at /home/runner/GreenyellowCadetblueWaterfall/node_modules/rollup/dist/shared/node-entry.js:13925:48
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/GreenyellowCadetblueWaterfall/node_modules/rollup/dist/shared/node-entry.js:38:28)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! python_utils_for_js@0.1.0-alpha build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the python_utils_for_js@0.1.0-alpha build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-02-29T08_10_18_864Z-debug.log

```

**Comment by TrySound** [comment]
You cannot use `exports: 'default'` when you have named exports in your module. Rollup does not support patching default export with named ones. If you want to work around this do it manually.
```
export default function fn() {}

fn.namedExport = () => {}
```

**Comment by fcole90** [comment]
So, do you mean that I add it to the final module? Is there any way I can automatise this?

**Comment by fcole90** [comment]
Note that I also have a `default`, so it would be a matter of ignoring the non-default exports :thinking:

**Comment by TrySound** [comment]
Yes, if you want to have proper named exports use `exports: 'named'`.
```
exports.default = function fn() {}
exports.namedExport = () => {}
```

Patching default export is hacky solution.

**Comment by fcole90** [comment]
Ok thank you :blush:
