### ISSUE TITLE
Error: No valid exports main found for `rollup`

### ISSUE THREAD

**Issue by proteriax** [rollup/rollup#3427]
- Rollup Version: 2.0.0
- Operating System (or Browser): macOS
- Node Version (if applicable): 13.5.0
- Link to reproduction (IMPORTANT, read below):
```sh
mkdir temp
cd temp
yarn init --yes
yarn add rollup
node -e "require('rollup')"
```

### Expected Behavior
```txt
{
  VERSION: '2.0.0',
  rollup: [Function: rollup],
  watch: [Function: watch]
}
```

### Actual Behavior
```
internal/modules/cjs/loader.js:625
  throw e;
  ^

Error: No valid exports main found for '...temp/node_modules/rollup'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by Olyno** [comment]
Same issue here:

**OS:** Windows 10
**Node version:** 13.3.0
**Rollup version:** 2.0.0

Works perfectly with rollup ``1.32.1`` (version before this one)

**Comment by lukastaegert** [comment]
I am sorry about this, this is specific to Node version 13.0.x - 13.7.x. Node is using conditional exports to support being used as an ES module in Node. The easiest solution is to update to at least Node 13.8.x. Node 12.x will work as well. Not sure if there is a way to make everything work in older Node 13 versions.

**Comment by lukastaegert** [comment]
Should be fixed in 2.0.1, please check

**Comment by subgan82** [comment]
Hi @lukastaegert 

After updating to `"@rollup/pluginutils": "^3.1.0"` latest , seeing the same issue with this rollup plugin on node v13.5.0 

```
pkg1: Error: No valid exports main found for '../node_modules/@rollup/pluginutils'
pkg1:     at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
pkg1:     at applyExports (internal/modules/cjs/loader.js:499:14)
pkg1:     at resolveExports (internal/modules/cjs/loader.js:548:12)
pkg1:     at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
pkg1:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
pkg1:     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
pkg1:     at Module.require (internal/modules/cjs/loader.js:1028:19)
pkg1:     at require (internal/modules/cjs/helpers.js:72:18)
pkg1:     at Object.<anonymous> (../packages/pkg1/scripts/test.js:5:21)
pkg1:     at Module._compile (internal/modules/cjs/loader.js:1139:30) {
pkg1:   code: 'MODULE_NOT_FOUND'

```

**Comment by guybedford** [comment]
@subgan82 this is because Node.js 13.5.0 does not support this feature of the `"exports"` field. I'd suggest updating Node.js here.

**Comment by bmordan** [comment]
node v13.6.0

I don't directly depend on @rollup/pluginutils

```
> riders-on-the-scorm@1.4.0 prod /app
> rollup -c && node server.js

[!] Error: No valid exports main found for '/app/node_modules/@rollup/pluginutils'
Error: No valid exports main found for '/app/node_modules/@rollup/pluginutils'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/@rollup/plugin-node-resolve/dist/index.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! riders-on-the-scorm@1.4.0 prod: `rollup -c && node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the riders-on-the-scorm@1.4.0 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-11T14_32_57_394Z-debug.log
```

**Comment by bmordan** [comment]
Works with 14.4 😊
