### ISSUE TITLE
Endless recursion error with manual chunking

### ISSUE THREAD

**Issue by lazka** [rollup/rollup#3499]
- Rollup Version: 2.6.1
- Operating System (or Browser): Ubuntu 20.04
- Node Version (if applicable): 12.16.2
- Link to reproduction (IMPORTANT, read below): https://github.com/lazka/rollup-chunks-bug

I'm passing some of my dependencies to manualChunks after updating rollup from 1.x to 2.x I noticed that it fails to build now. See the linked repo for a minimal reproducer. I haven't looked into which version is the last one to work, but I can figure that out if needed.

The culprit is the manualChunks config I pass here: https://github.com/lazka/rollup-chunks-bug/blob/master/rollup.config.js

### Expected Behavior

* Rollup creates separate chunks for my dependencies.

### Actual Behavior

* Rollup crashes:

```
!] RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16400:28)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
    at Chunk$1.inlineChunkDependencies (/home/lazka/Desktop/adwwad/rollup-bug/node_modules/rollup/dist/shared/rollup.js:16411:22)
```

**Comment by lukastaegert** [comment]
Fix at #3510, thanks for spotting!
