### ISSUE TITLE
error when in __PURE__ in class static field

### ISSUE THREAD

**Issue by LongTengDao** [rollup/rollup#3591]
- Rollup Version: 2.10.7
- Operating System (or Browser): Windows 10
- Node Version (if applicable): 12
- Link to reproduction (IMPORTANT, read below):

https://rollupjs.org/repl/?version=2.10.9&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMCU3QiU1Q24lMjAlMjAlMjAlMjBzdGF0aWMlMjBrJTIwJTNEJTIwJTJGKiUyM19fUFVSRV9fKiUyRlYoKSUzQiU1Q24lN0QlM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE

main.js:

```js
export default class {
    static k = /*#__PURE__*/V();
};
```

### Expected Behavior

no error

### Actual Behavior

```
TypeError: base$1[type] is not a function
    at handlePureAnnotationsOfNode                                          (/rollup/dist/shared/rollup.js:14847:21)
    at Object.base$1.ClassBody                                              (/rollup/dist/shared/rollup.js:14831:5)
    at handlePureAnnotationsOfNode                                          (/rollup/dist/shared/rollup.js:14847:21)
    at Object.base$1.Class                                                  (/rollup/dist/shared/rollup.js:14824:3)
    at handlePureAnnotationsOfNode                                          (/rollup/dist/shared/rollup.js:14847:21)
    at Object.base$1.ClassDeclaration.base$1.ClassExpression                (/rollup/dist/shared/rollup.js:14820:84)
    at handlePureAnnotationsOfNode                                          (/rollup/dist/shared/rollup.js:14847:21)
    at Object.skipThrough                                                   (/rollup/dist/shared/rollup.js:14578:37)
    at handlePureAnnotationsOfNode                                          (/rollup/dist/shared/rollup.js:14847:21)
    at Object.base$1.ExportNamedDeclaration.base$1.ExportDefaultDeclaration (/rollup/dist/shared/rollup.js:14796:7)
    at handlePureAnnotationsOfNode                                          (/rollup/dist/shared/rollup.js:14847:21)
    at Object.skipThrough                                                   (/rollup/dist/shared/rollup.js:14578:37)
    at handlePureAnnotationsOfNode                                          (/rollup/dist/shared/rollup.js:14847:21)
    at Object.base$1.Program.base$1.BlockStatement                          (/rollup/dist/shared/rollup.js:14590:5)
    at handlePureAnnotationsOfNode                                          (/rollup/dist/shared/rollup.js:14847:21)
    at markPureCallExpressions                                              (/rollup/dist/shared/rollup.js:14867:5)
    at Module.setSource                                                     (/rollup/dist/shared/rollup.js:15416:13)
    at ModuleLoader.addModuleSource                                         (/rollup/dist/shared/rollup.js:17457:20)
    at async ModuleLoader.fetchModule                                       (/rollup/dist/shared/rollup.js:17518:9)
    at async Promise.all                                                    (index 0)
    at async Promise.all                                                    (index 0)
    at async getCombinedPromise                                             (/rollup/dist/shared/rollup.js:17477:13)
    at async ModuleLoader.awaitLoadModulesPromise                           (/rollup/dist/shared/rollup.js:17482:9)
    at async ModuleLoader.addEntryModules                                   (/rollup/dist/shared/rollup.js:17378:33)
    at async Promise.all                                                    (index 0)
    at async Graph.parseModules                                             (/rollup/dist/shared/rollup.js:18589:63)
    at async Graph.build                                                    (/rollup/dist/shared/rollup.js:18449:61)
    at async rollupInternal                                                 (/rollup/dist/shared/rollup.js:18840:18)
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Please add a reproduction and we'll be happy to triage further.

**Comment by lukastaegert** [comment]
Thanks, fix at #3599. Note though that the annotations themselves are not yet observed by Rollup for static class properties, side-effect detection for static class elements would still need to be implemented.

**Comment by LongTengDao** [comment]
Thank you!

> Note though that the annotations themselves are not yet observed by Rollup for static class properties, side-effect detection for static class elements would still need to be implemented.

I didn't quite understand this. Would you explain more?

**Comment by lukastaegert** [comment]
Ah, I was thinking about side-effects of calls to static properties. Here is is about initialization, where side-effection actually works well, so forget my comment: https://rollupjs.org/repl/?circleci=11395&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwRm9vJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHN0YXRpYyUyMGElMjAlM0QlMjAlMkYqJTIzX19QVVJFX18qJTJGVigpJTNCJTVDbiU3RCUzQiU1Q24lNUNuY2xhc3MlMjBCYXIlMjAlN0IlNUNuJTIwJTIwJTIwJTIwc3RhdGljJTIwYSUyMCUzRCUyMFYoKSUzQiU1Q24lN0QlM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==
