### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by fitzmode** [rollup/rollup#3594]
- Rollup Version:  v2.6.1
- Operating System (or Browser): Mac OS X 10.14.5
- Node Version (if applicable): v12.12, v13.12.0
- Link to reproduction (IMPORTANT, read below): https://github.com/zcued/react-dragline/tree/2.0.0-alpha.1

### Expected Behavior
Should transpile to output files

### Actual Behavior
Rollup fails on start and throws error at ES6 module import within rollup installation folder. Tested with multiple versions of `node`.
```
> Executing task: npm run build <


> react-dragline@2.0.0-alpha.1 build /Users/fitzmode/react-dragline
> cross-env NODE_ENV=production rollup -c

/usr/local/lib/node_modules/rollup/dist/shared/loadConfigFile.js:484
        ? (await import(url.pathToFileURL(fileName).href)).default
                 ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/rollup/dist/bin/rollup:23:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-dragline@2.0.0-alpha.1 build: `cross-env NODE_ENV=production rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-dragline@2.0.0-alpha.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fitzmode/.npm/_logs/2020-05-25T18_18_25_352Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

**Comment by TrySound** [comment]
Please make sure you do not use node version below 10. Such syntax error is specific to them. Node 10+ is able to parse dynamic imports.

**Comment by shellscape** [comment]
Also please try to duplicate your issue using one of the REPLs suggested by the issue template. That will help verify your issue and provide a _minimal_ reproduction as requested.

**Comment by lukastaegert** [comment]
Your reproduction builds correctly for me on Node 10+, please reopen if there are any more issues
