### ISSUE TITLE
ENOENT error while building typescript project

### ISSUE THREAD

**Issue by denissabramovs** [rollup/rollup#3653]
```
@acpdev/db: @acpdev/types: (rpt2 plugin) Error: ENOENT: no such file or directory, open './node_modules/.cache/.rts2_cache_cjs/rpt2_af404fa933f03a7355e8a307fe11e7a9b14ae803/code/cache_/86f0e30c5e774d790e16af13b74f895c86029f3f'
@acpdev/db: @acpdev/types: Error: ENOENT: no such file or directory, open './node_modules/.cache/.rts2_cache_cjs/rpt2_af404fa933f03a7355e8a307fe11e7a9b14ae803/code/cache_/86f0e30c5e774d790e16af13b74f895c86029f3f'
@acpdev/db: @acpdev/types:     at Object.openSync (fs.js:458:3)
@acpdev/db: @acpdev/types:     at Object.writeFileSync (fs.js:1279:35)
@acpdev/db: @acpdev/types:     at Object.writeFileSync (/var/local/acp/dashboards/node_modules/jsonfile/index.js:117:13)
@acpdev/db: @acpdev/types:     at RollingCache.write (/var/local/acp/dashboards/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:23981:17)
@acpdev/db: @acpdev/types:     at TsCache.getCompiled (/var/local/acp/dashboards/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24835:24)
@acpdev/db: @acpdev/types:     at Object.transform (/var/local/acp/dashboards/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27347:36)
@acpdev/db: @acpdev/types:     at /var/local/acp/dashboards/node_modules/rollup/dist/shared/node-entry.js:13117:25

```

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
