### ISSUE TITLE
An error is reported when executing the ‘rollup ’ command！！

### ISSUE THREAD

**Issue by ahboa** [rollup/rollup#3668]
E:\222\rp1>rollup
D:\Program Files\nodejs\node_global\node_modules\rollup\dist\shared\loadConfigFile.js:525
        ? (await import(url.pathToFileURL(fileName).href)).default
                 ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\rollup\dist\bin\rollup:21:25)

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
