### ISSUE TITLE
Error using -c flag in postinstall script.

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [rollup/rollup#3719]
- Rollup Version: 2.23.0
- Operating System (or Browser): Windows 7
- Node Version (if applicable): 12.16.2
- Link to reproduction (IMPORTANT, read below): It's complicated, I can make a github repo if needed.

### My `package.json` scripts in npm package
``` json
{
    "scripts": {
        "postinstall": "rollup -c"
    }
}
```
This is my `rollup.config.js` file.
``` js
export default {
    input: "index.js",
    output: {
        file: "commonjs/index.js",
        format: "cjs"
    }
}
```

### Expected Behavior
When using `npm install <the package>`, it should create a commonjs file called `commonjs/index.js`.

### Actual Behavior
It runs the script with the error: 
```
[!] Error: While loading the Rollup configuration from "rollup.config.js", Node tried to require an ES module from a CommonJS file, which is not supported. A common cause is if there is a package.json file with "type": "module" in the same folder. You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content, which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.

```
### This works if `rollup -c ./rollup.config.js` is used
For some reason, it works just fine when I explicitly give `./rollup.config.js`, but I thought that would be assumed automatically if I just did `rollup -c`. `rollup -c ` works if it is in a build script, but not if it is being installed and called in a `postinstall` script.

**Comment by lukastaegert** [comment]
Did you try to follow the suggestion of changing the extension of your rollup config?

**Comment by ChocolateLoverRaj** [comment]
I tried changing `rollup.config.js` to `rollup.config.mjs`, and I got a different error:
```
[!] TypeError: defaultLoader is not a function
TypeError: defaultLoader is not a function
    at Object.require.extensions.<computed> [as .mjs] (C:\Users\Jui\Documents\GitHub\canvideo\node_modules\rollup\dist\shared\loadConfigFile.js:523:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at loadConfigFromBundledFile (C:\Users\Jui\Documents\GitHub\canvideo\node_modules\rollup\dist\shared\loadConfigFile.js:528:42)
    at getDefaultFromTranspiledConfigFile (C:\Users\Jui\Documents\GitHub\canvideo\node_modules\rollup\dist\shared\loadConfigFile.js:513:12)
    at async loadConfigFile (C:\Users\Jui\Documents\GitHub\canvideo\node_modules\rollup\dist\shared\loadConfigFile.js:491:15)
    at async Object.loadAndParseConfigFile (C:\Users\Jui\Documents\GitHub\canvideo\node_modules\rollup\dist\shared\loadConfigFile.js:470:21)
    at async getConfigs (C:\Users\Jui\Documents\GitHub\canvideo\node_modules\rollup\dist\bin\rollup:1626:39)
```

**Comment by lukastaegert** [comment]
I believe in that case we need a running reproduction as required in the bug template to help you. E.g. a repository or ideally a repl.it link.

**Comment by ChocolateLoverRaj** [comment]
Ok. I don't think I'll be able to do it on repl.it because its about two packages, one depending on the other. I will make a github repository.

**Comment by lukastaegert** [comment]
Oh, looking at your Node version: Are you using by chance "experimentalModules" with Node? This is only supported in Rollup if you use Node 14+. We will not fix this for Node 12.

**Comment by ChocolateLoverRaj** [comment]
Yeah, I have to use the experimental modules flag when running ESModules because I'm using node 12. How exactly does rollup reference to config file?

**Comment by lukastaegert** [comment]
If the extension is `.js`, it is basically bundling and transpiling the config file to CJS. Now if the config file is importing actual ES modules, this is not working because you cannot require an ES module in Node. To work around this if the extension is `.mjs` and the Node version is at least 13, it is using a dynamic import to load the config file. On Node 12, it is always transpiling because ES modules are not supported by default, and the actual implementation is apparently incompatible with the one in Node 14.

**Comment by ChocolateLoverRaj** [comment]
So if I change my file to.`rollup.config.cjs` and changed `export default` to `module.exports =` will it work?

**Comment by lukastaegert** [comment]
Yes, that should work

**Comment by ChocolateLoverRaj** [comment]
I think for now I will just have an esmodule in a .js file, calling 
``` bash
rollup -c rollup.config.js
```
Then I think in October, node 14 will be LTS, and I will switch to node 14.
