### ISSUE TITLE
Windows 10 Error: Unresolved external import

### ISSUE THREAD

**Issue by radum** [rollup/rollup#3768]
- Rollup Version: 2.26.10
- Operating System (or Browser): Windows 10
- Node Version (if applicable): 12.18.3
- Link to reproduction (IMPORTANT, read below): Any simple demo has the same issue.

### Expected Behavior

Rollup expected not to fail on windows builds.

### Actual Behavior

On Windows 10 even on the simplest demo it fails to run with the following error:

```
Build had unhandled rejection Error: Unresolved external import: "D:\a\1\s\src\client\utils\storage.js" (imported by: D:\a\1\s\src\client\app.js), did you forget to npm install?
    at disallowExternal (D:\a\1\s\lib\build\common.js:57:9)
    at Object.external (D:\a\1\s\node_modules\rollup\dist\shared\rollup.js:19399:58)
    at ModuleLoader.normalizeResolveIdResult (D:\a\1\s\node_modules\rollup\dist\shared\rollup.js:18287:62)
    at ModuleLoader.resolveId (D:\a\1\s\node_modules\rollup\dist\shared\rollup.js:18099:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async D:\a\1\s\node_modules\rollup\dist\shared\rollup.js:18238:38
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (D:\a\1\s\node_modules\rollup\dist\shared\rollup.js:18236:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (D:\a\1\s\node_modules\rollup\dist\shared\rollup.js:18213:9) {
  watchFiles: [ 'D:\\a\\1\\s\\src\\client\\app.js' ]

```

```js
// app.js

import { x } from './utils/x';

x['test'] = 'test';
```

```js
// utils/x.js
export const x = {};
```

Plugins used:

```
"@rollup/plugin-commonjs": "^15.0.0",
"@rollup/plugin-node-resolve": "^9.0.0",
```

It works perfectly fine on all other OS. Has anyone experienced something like this?

**Comment by MTerinteTh** [comment]
hey, what was the solution you found, @radum  ? thank you <3
