### ISSUE TITLE
files .node.js are not correctly resolved

### ISSUE THREAD

**Issue by zogs** [rollup/rollup#3795]
- Rollup Version: ^2.3.4
- Operating System (or Browser): Win10
- Node Version (if applicable): v10, v12
- Link to reproduction (IMPORTANT, read below):

Sorry but it's a weird bug. try to reproduce it on REPL but it worked. this is surely due to my environment, but i can not find any useful ressource about it...

So... it seems the resolver can't resolve file extension `.node.js`... because when i rename it without `.node` it is working correctly...

```
rollup v2.27.1
bundles src/main.js → public/build/bundle.js...

(!) Circular dependencies
node_modules/@loaders.gl/core/dist/esm/lib/api/parse.js -> node_modules/@loaders.gl/core/dist/esm/lib/loader-utils/parse-with-worker.js -> node_modules/@loaders.gl/co
re/dist/esm/lib/api/parse.js
node_modules/@luma.gl/gltools/dist/esm/state-tracker/unified-parameter-api.js -> node_modules/@luma.gl/gltools/dist/esm/state-tracker/track-context-state.js -> node_m
odules/@luma.gl/gltools/dist/esm/state-tracker/unified-parameter-api.js
node_modules/@luma.gl/webgl/dist/esm/webgl-utils/texture-utils.js -> node_modules/@luma.gl/webgl/dist/esm/classes/texture-2d.js -> node_modules/@luma.gl/webgl/dist/es
m/classes/texture.js -> node_modules/@luma.gl/webgl/dist/esm/classes/resource.js -> node_modules/@luma.gl/webgl/dist/esm/webgl-utils/index.js -> node_modules/@luma.gl
/webgl/dist/esm/webgl-utils/texture-utils.js
...and 4 more

[!] Error: 'requireFromFile' is not exported by  node-resolve:empty.js, imported by node_modules/@loaders.gl/loader-utils/dist/esm/lib/library-utils/library-utils.js 
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@loaders.gl/loader-utils/dist/esm/lib/library-utils/library-utils.js (4:9)
2: import _asyncToGenerator from "@babel/runtime/helpers/esm/asyncToGenerator";
3: import { global, isBrowser, isWorker } from '../env-utils/globals';
4: import { requireFromFile, requireFromString } from './require-utils.node';
            ^
5: import assert from '../env-utils/assert';
6: var LATEST = 'beta';
Error: 'requireFromFile' is not exported by  node-resolve:empty.js, imported by node_modules/@loaders.gl/loader-utils/dist/esm/lib/library-utils/library-utils.js     
    at error (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:5211:30)
    at Module.error (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:9726:16)
    at handleMissingExport (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:9648:28)
    at Module.traceVariable (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:10121:24)
    at ModuleScope.findVariable (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:8680:39)
    at FunctionScope.findVariable (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:2759:38)
    at ChildScope.findVariable (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:2759:38)
    at FunctionScope.findVariable (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:2759:38)
    at ChildScope.findVariable (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:2759:38)
    at FunctionScope.findVariable (/var/www/mapbox-gl/deckgl/bivb-svelte/node_modules/rollup/dist/shared/rollup.js:2759:38)
```

### Expected Behavior

file `require-utils.node.js` is resolved

### Actual Behavior

Seems like the *resolved* file return an empty object {}, triggering error `[!] Error: 'requireFromFile' is not exported by `
(trust me, requireFromFile is definitively defined in the file)

Thanks for the help

**Comment by vinayakkulkarni** [comment]
Facing the same issue!
