### ISSUE TITLE
Rollup+TypeScript+Jimp: Error: 'default' is not exported by node_modules/jimp/es/index.js, imported by src/index.ts

### ISSUE THREAD

**Issue by mogoh** [rollup/rollup#3900]
I am not sure if this issue is in Rollup, a rollup plugin, or Jimp.
So, if this is (for sure) not a rollup issue, please close this issue and point me to the right direction.
I will also open one Issue over at Jimp and link to this one.

- Rollup Version: 2.34.2
- Operating System (or Browser): Ubunut 20.10
- Node Version (if applicable): 15.3.0
- Link to reproduction (IMPORTANT, read below): https://github.com/mogoh/rollup-typescript-jimp

### Expected Behavior

Compile and Bundle src/index.ts

### Actual Behavior

~~~
$ yarn rollup
yarn run v1.22.5
$ rollup --config

./src/index.ts → ./dist...
[!] Error: 'default' is not exported by node_modules/jimp/es/index.js, imported by src/index.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/index.ts (1:7)
1: import Jimp from 'jimp/es';
          ^
2: 
3: // open a file called "lenna.png"
Error: 'default' is not exported by node_modules/jimp/es/index.js, imported by src/index.ts
    at error (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:5265:30)
    at Module.error (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:9835:16)
    at handleMissingExport (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:9724:28)
    at Module.traceVariable (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:10228:24)
    at ModuleScope.findVariable (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:8747:39)
    at MemberExpression.bind (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:6451:49)
    at CallExpression$1.bind (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:2868:23)
    at CallExpression$1.bind (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:6644:15)
    at MemberExpression.bind (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:2868:23)
    at MemberExpression.bind (/home/mogoh/src/github.com/mogoh/rollup-typescript-jimp/node_modules/rollup/dist/shared/rollup.js:6469:19)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~~~

* The error leads to this page: https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
* It suggests using namedExports from `@rollup/plugin-commonjs`
* namedExports are deprecated: https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#v1300

**Comment by justin2taylor** [comment]
Also running into the same issue with Jimp + Rollup, having to copy the entire module for now. Did you find a fix?

**Comment by mogoh** [comment]
No, but I stopped searching ...

**Comment by justintaylor-dev** [comment]
@mogoh ended up rolling my own basic plugin to copy node modules (with dependencies) that won't bundle:

https://github.com/justintaylor-dev/rollup-plugin-node-copy

**Comment by veikkoeeva** [comment]
I'll link https://github.com/rollup/rollup/issues/3994 and https://github.com/ethers-io/ethers.js/issues/1179 since they seem to be aboutish the same issue. I made progress by patching the `package.json` files to include a `module` field, copying the JS script to `es.js` one and making them to ESM export. I have not tried this plugin yet, but maybe these added notes are beneficial to someone, also linking to this plugin could be useful with someone else with the same problem.

**Comment by lucasriondel** [comment]
To anyone that would see this: using the latest version of Jimp fixed the issue for me.
