### ISSUE TITLE
emitFile({ type: "chunk", fileName: "xyz", ... }) → 

### ISSUE THREAD

**Issue by akvadrako** [rollup/rollup#3939]
- Rollup Version: 2.38.0
- Operating System (or Browser): Linux
- Node Version (if applicable): 14.15.3
- Link to reproduction (IMPORTANT, read below):

In a dummy plugin when I use emitFile with a fileName I get an exception. For example:
```js
        buildStart() {
            this.emitFile({
                type: 'chunk',
                id: './extra.js',
                fileName: 'ref1.js',
            });
        },
```

however using name instead works:
```js
        buildStart() {
            this.emitFile({
                type: 'chunk',
                id: './extra.js',
                name: 'ref1.js',
            });
        },
```

### Expected Behavior

No exception.

### Actual Behavior

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:980:7)
    at writeOutputFile (/home/dev/.nvm/versions/node/v14.15.3/lib/node_modules/rollup/dist/shared/rollup.js:20127:30)
    at /home/dev/.nvm/versions/node/v14.15.3/lib/node_modules/rollup/dist/shared/rollup.js:20071:65
    at Array.map (<anonymous>)
    at handleGenerateWrite (/home/dev/.nvm/versions/node/v14.15.3/lib/node_modules/rollup/dist/shared/rollup.js:20071:50)
    at async Promise.all (index 0)
    at async build (/home/dev/.nvm/versions/node/v14.15.3/lib/node_modules/rollup/dist/bin/rollup:1495:5)
    at async runRollup (/home/dev/.nvm/versions/node/v14.15.3/lib/node_modules/rollup/dist/bin/rollup:1647:21)
```

**Comment by lukastaegert** [comment]
Unfortunately I cannot reproduce the issue with the provided information. Please add a reproduction (e.g. via https://repl.it/@rollup/rollup-repro ) or we have to close the issue
