### ISSUE TITLE
mayModifyThisWhenCalledAtPath causes RangeError: Maximum call stack size exceeded (v2.43.0 only)

### ISSUE THREAD

**Issue by yawetse** [rollup/rollup#4024]
- Rollup Version: v2.43.0
- Operating System (or Browser): MacOS 10.15.7 
- Node Version (if applicable): 14.10.1
- Link to reproduction (IMPORTANT, read below): https://github.com/repetere/jsonx/blob/main/rollup.config.js

#### v2.42.4 
```
rollup -c

build/index.js → dist/index.umd.js, dist/index.web.js...
(!) Circular dependencies
node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/readable.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js
node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/writable.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js
build/index.js -> build/components.js -> build/index.js
...and 8 more
created dist/index.umd.js, dist/index.web.js in 8.1s
```
#### v2.43.0 
```
rollup -c

build/index.js → dist/index.umd.js, dist/index.web.js...
(!) Circular dependencies
node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/readable.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js
node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/writable.js -> node_modules/rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js
build/index.js -> build/components.js -> build/index.js
...and 8 more
[!] RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at LocalVariable.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:2532:18)
    at Identifier.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:4106:46)
    at LocalVariable.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:2535:26)
    at Identifier.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:4106:46)
    at LocalVariable.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:2535:26)
    at Identifier.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:4106:46)
    at LocalVariable.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:2535:26)
    at Identifier.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:4106:46)
    at LocalVariable.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:2535:26)
    at Identifier.mayModifyThisWhenCalledAtPath (/Users/yaw.etse/.nvm/versions/node/v14.10.1/lib/node_modules/rollup/dist/shared/rollup.js:4106:46)
```

**Comment by lukastaegert** [comment]
Thanks for reporting, fix at #4025.
