### ISSUE TITLE
Exception parsing arrow functions

### ISSUE THREAD

**Issue by extraprogram** [rollup/rollup#403]
I get an exception when using Rollup on arrow functions that return a single identifier:
```js
// main.js
const f = a => a;
console.log(f(1));
```
```
$ rollup -i main.js
Cannot read property 'type' of null
[...]
```
This also causes an exception:
```js
const a = 1;
const f = () => a;
console.log(f());
```
This works fine though:
```js
const f = (a => a);
console.log(f(1));
```

**Comment by Victorystick** [comment]
Trace
````
TypeError: Cannot read property 'type' of null
      at isReference (Users/oskar/github/rollup/src/ast/isReference.js:8:14)
      at Object.walk.enter (Users/oskar/github/rollup/src/utils/run.js:58:9)
      at visit (Users/oskar/github/rollup/node_modules/estree-walker/dist/estree-walker.es6.js:27:9)
      at walk (Users/oskar/github/rollup/node_modules/estree-walker/dist/estree-walker.es6.js:5:2)
      at run (Users/oskar/github/rollup/src/utils/run.js:50:27)
      at Declaration.run$$ [as run] (Users/oskar/github/rollup/src/Declaration.js:51:26)
```

**Comment by Rich-Harris** [comment]
Thanks @extraprogram – this is fixed in the current version
