### ISSUE TITLE
rollup, lerna, typescript, when import from sibling package ts compiler complains

### ISSUE THREAD

**Issue by naivefun** [rollup/rollup#4063]
github repo: https://github.com/naivefun/rollup-lerna-ts-demo

```
├── lerna.json
├── package.json
├── packages
│   ├── core (`@test/core`)
│   │   ├── README.md
│   │   ├── package.json
│   │   └── src
│   │       ├── Test.tsx
│   │       └── index.ts
│   └── lib
│       ├── README.md
│       ├── package.json
│       ├── rollup.config.js
│       ├── src
│       │   └── index.tsx (`import {hello} from '@test/core';
│       └── tsconfig.json (`paths { '@test/core': [ '../core/*' ] }`)
└── yarn.lock
```

**Purpose**
lib has dependency on core, both is typescript react package.

**Problem**
when lib add imports from core, rollup cannot compile:
```
lib % yarn compile
yarn run v1.22.10
$ rollup -c

./src/index.tsx → dist/index.js, dist/index.es.js...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
../core/src/Test.tsx (5:7)
3: //#endregion
4: 
5: export interface TestProps {}
          ^
6: 
7: export interface State {}
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/peisong/Desktop/rollup-lerna-ts-demo/node_modules/rollup/dist/shared/rollup.js:5305:30)
    at Module.error (/Users/peisong/Desktop/rollup-lerna-ts-demo/node_modules/rollup/dist/shared/rollup.js:9750:16)
    at Module.tryParse (/Users/peisong/Desktop/rollup-lerna-ts-demo/node_modules/rollup/dist/shared/rollup.js:10156:25)
    at Module.setSource (/Users/peisong/Desktop/rollup-lerna-ts-demo/node_modules/rollup/dist/shared/rollup.js:10057:24)
    at ModuleLoader.addModuleSource (/Users/peisong/Desktop/rollup-lerna-ts-demo/node_modules/rollup/dist/shared/rollup.js:18402:20)
    at async ModuleLoader.fetchModule (/Users/peisong/Desktop/rollup-lerna-ts-demo/node_modules/rollup/dist/shared/rollup.js:18458:9)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/Users/peisong/Desktop/rollup-lerna-ts-demo/node_modules/rollup/dist/shared/rollup.js:18484:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/Users/peisong/Desktop/rollup-lerna-ts-demo/node_modules/rollup/dist/shared/rollup.js:18460:9)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If I publish core to npm and use it from npm install it works fine, but in dev environment this setup cannot work.

**rollup config**
```javascript
import commonjs from "@rollup/plugin-commonjs";
import resolve from "@rollup/plugin-node-resolve";
import typescript from "@rollup/plugin-typescript";
const path = require("path");

// 1321d064-489a-450c-afbf-a49301617184
export default [
  {
    input: "./src/index.tsx",
    external: ["react", "react-dom"],
    output: [
      {
        file: "dist/index.js",
        format: "umd",
        name: "PReactColor",
        exports: "named",
        globals: {
          react: "window.React",
          "react-dom": "window.ReactDOM",
        },
      },
      {
        file: "dist/index.es.js",
        format: "es",
        exports: "named",
        globals: {
          react: "window.React",
          "react-dom": "window.ReactDOM",
        },
      },
    ],
    plugins: [
      typescript({}),
      commonjs({}),
      resolve({
        extensions: [".js", ".jsx", ".ts", ".tsx"],
      }),
      // terser({}),
    ],
  },
];
```

**Comment by LLEmily** [comment]
哥们，你这个咋解决的啊， 我也遇到了 @naivefun

**Comment by raul1991** [comment]
So how to make it work locally then? and so you mean, to use core in lib, you'd 

**NOT use relative imports like** 

`import {something} from (../core/something)` 

**instead, use registry imports like** 

`import {something} from "@namespace/core"`

**Comment by raul1991** [comment]
@naivefun 🆙
