### ISSUE TITLE
support query parameters and fragments

### ISSUE THREAD

**Issue by dnalborczyk** [rollup/rollup#4275]
### Feature Use Case

**index.js**
```
import foo1 from "./foo.js?foo=bar1";
import foo2 from "./foo.js?foo=bar2";

console.log(foo1);
console.log(foo2);
```

**foo.js**
```
export default new URL(import.meta.url).searchParams.get("foo");
```

**rollup.config.js**
```
export default {
  input: "./index.js",
  output: {
    file: "./build/bundle.js",
    format: "module",
  },
};
```

```shell
➜ npx rollup -c

./index.js → ./build/bundle.js...
[!] Error: Could not resolve './foo.js?foo=bar1' from index.js
Error: Could not resolve './foo.js?foo=bar1' from index.js
    at error (/Users/daniel/dev/github-forks/rolLUP/src/utils/error.ts:15:53)
    at ModuleLoader.handleResolveId (/Users/daniel/dev/github-forks/rolLUP/src/ModuleLoader.ts:551:12)
    at /Users/daniel/dev/github-forks/rolLUP/src/ModuleLoader.ts:514:12
```

### Feature Proposal

.

**Comment by dnalborczyk** [comment]
fragments repro:

**index.js**
```js
import foo1 from "./foo.js#bar1"
import foo2 from "./foo.js#bar2"

console.log(foo1);
console.log(foo2);
```

**foo.js**
```js
export default new URL(import.meta.url).hash;
```

```shell
➜ npx rollup -c

./index.js → ./build/bundle.js...
[!] Error: Could not resolve './foo.js#bar1' from index.js
Error: Could not resolve './foo.js#bar1' from index.js
    at error (/Users/daniel/dev/rolLUP/src/utils/error.ts:15:53)
    at ModuleLoader.handleResolveId (/Users/daniel/dev/rolLUP/src/ModuleLoader.ts:551:12)
    at /Users/daniel/dev/rolLUP/src/ModuleLoader.ts:514:12
```

**Comment by lukastaegert** [comment]
I would be surprised to learn that this works in Node, and it only works in browsers if the server strips them automatically before resolving. Why not just write a plugin for that, should not be difficult using  the `resolveId` hook and `this.resolve`.

**Comment by lukastaegert** [comment]
That is not to say we could not implement it, just saying it is slightly non-standard.

**Comment by dnalborczyk** [comment]
> I would be surprised to learn that this works in Node

you might be in for a surprise then 😉  you can literally run the code above "as is" (needs a package.json with type=module)

> and it only works in browsers if the server strips them automatically before resolving. 

I think servers usually just ignore any query parameters if they don't expect any, but it's up to the server what to do in that case. remember, query params are also being used for cache busting.

> Why not just write a plugin for that, should not be difficult using the `resolveId` hook and `this.resolve`.

it seems to me, if implemented, this should be part of the core functionality, as the query params and fragments also become part of the module cache:

```js
import foo1 from "./foo.js?foo=bar1"
import foo2 from "./foo.js?foo=bar2"

console.log(foo1) // prints: bar1
console.log(foo2) // prints: bar2
```

**Comment by dnalborczyk** [comment]
> it is slightly non-standard.

just curious, what is the non-standard?

> Implementing it should in itself be rather easy as the default loader would just strip the query parameters before loading but keep them as part of the module id to distinguish the module instances.

there's a special case where the query parameters can be also dynamic for dynamic imports:

```js
import foo1 from "./foo.js?foo=bar1";

const param = "bar2";

const { default: foo2 } = await import(`./foo.js?foo=${param}`);
const { default: foo3 } = await import(`./foo.js?foo=${param}`);

console.log(foo1); // prints: bar1
console.log(foo2); // prints: bar2
console.log(foo3); // prints: bar2
```

**Comment by dnalborczyk** [comment]
@lukastaegert  I'm not sure, this might be also outside of the responsibilities of bundlers. that said, part of me thinks it should be at least possible to not throw an error when resolving the file path, on the other hand, doing so might cause issues down the road as there was likely an intend by attaching query params.

**Comment by lukastaegert** [comment]
> there's a special case where the query parameters can also be dynamic for dynamic imports

In that case, I think it should be handled like any dynamic import as we cannot figure out the id to use.

In any case, so far I think you may only need to fix `findFile` here to ignore query parameters and hashes when checking if a file exists here https://github.com/rollup/rollup/blob/8d98341bf746d4baa57bbd730b1fa6449555cfca/src/utils/resolveId.ts#L57-L72 and the strip them again for the call to readFile here https://github.com/rollup/rollup/blob/8d98341bf746d4baa57bbd730b1fa6449555cfca/src/ModuleLoader.ts#L245-L245 if you want to go for a PR.

**Comment by dnalborczyk** [comment]
thank you for the pointers @lukastaegert ! I poked around a little bit and got it working.

e.g. this

```js
// index.js
import foo1 from "./foo.js?foo=bar";
import foo2 from "./foo.js";
import foo3 from "./foo.js?foo=bar";

console.log(foo1 === foo2);
console.log(foo2 === foo3);
console.log(foo1 === foo3);

// when run with node.js:
// false
// false
// true
```

is being bundled as:

```js
// bundle.js
var foo3 = {};

var foo2 = {};

console.log(foo3 === foo2);
console.log(foo2 === foo3);
console.log(foo3 === foo3);
// false
// false
// true
```

which I must admit is quite amazing!!

**Comment by lukastaegert** [comment]
Sounds great! If we can land this, one should then have another look at `@rollup/plugin-node-resolve` to align behaviour here. I vaguely remember that issue had popped up in the past, but without the load fix in Rollup, any fix in node-resolve would not have helped much.

**Comment by kzc** [comment]
I'm trying to understand the use case for imports with query parameters.

Does rollup presently support http(s) URLS for imports - either built in or via a plugin?  I see `async fetchModule` in `src/ModuleLoader.ts` - does it actually invoke `fetch`?

**Comment by dnalborczyk** [comment]
> I'm trying to understand the use case for imports with query parameters.

quoted from https://github.com/rollup/rollup/issues/4275#issuecomment-971589686
>  I'm not sure, this might be also outside of the responsibilities for bundlers. that said, part of me thinks it should be at least possible to not throw an error when resolving the file path, on the other hand, doing so might cause issues down the road as there was likely an intend by attaching query params.

My thinking is that since query params are supported in the browser and node.js (thru WHATWG and the host implementation) at the minimum I would expect `rollup` not to throw an error while parsing file paths with a query or a hash, as it currently does, maybe also with a possible warning that query parameters and hashes are currently not supported.

use cases might emerge, once esm is fully supported across the ecosystem.

> Does rollup presently support http(s) URLS for imports - either built in or via a plugin? I see `async fetchModule` in `src/ModuleLoader.ts` - does it actually invoke `fetch`?

I'm pretty sure rollup does not yet support https imports (I believe it should be currently also not possible thru a plugin, as the import string is a file path https://github.com/rollup/rollup/issues/4278 ), but I'm thinking eventually down the road it could, or even should have support. e.g. node.js is trying to add http imports into core as well.

**Comment by kzc** [comment]
Seems reasonable.  I imagine that deno would also support this in its imports since it's a web-first platform.

It should be pretty straightforward for rollup to have support for web URLs and query params in a plugin.  Worse case scenario, the URLs could be fetched and mapped to local file names in the resolveId and load hooks.

**Comment by dnalborczyk** [comment]
> ~I believe it should be currently also not possible thru a plugin, as the import string is a file path~

it seems rollup ignores a [file] URL entirely. I imagine it's also being passed down to a plugin (haven't checked). some of the used node.js buildins also support `PathLike` types (incl. URL). not quite sure why queries and hashes are throwing, I would have to check on that again as well.

that said, I'm thinking URL support should be first class: https://github.com/rollup/rollup/issues/4278 and query and hash support should (could) come after. it's possible without, but you'd have to convert back and forth between file paths and URLs.

**Comment by kzc** [comment]
It also appears that the rollup CLI can't handle URL entry points with query parameter equal signs due to an alias feature:

```
$ cat plug.js 
module.exports = (options = {}) => {
    return {
        name: "plug",
        async options(options) {
            console.error("*** plug options.input:", options.input);
        },
        resolveId(id, importer) {
            console.error("*** plug resolveId:", JSON.stringify(id), JSON.stringify(importer));
        },
    }
};
```

```
$ rollup input.mjs=changed.js -p ./plug.js 

changed.js → stdout...
*** plug options.input: { 'input.mjs': 'changed.js' }
*** plug resolveId: "changed.js" undefined
[!] Error: Could not resolve entry module (changed.js).
```

```
$ rollup 'https://example.org/foo/bar.js?abc=123&def=456#xyz' -p ./plug.js

123&def=456#xyz → stdout...
*** plug options.input: { 'https://example.org/foo/bar.js?abc': '123&def=456#xyz' }
*** plug resolveId: "123&def=456#xyz" undefined
[!] Error: Could not resolve entry module (123&def=456#xyz).
```

A hacky workaround:

```
$ rollup 'url=https://example.org/foo/bar.js?abc=123&def=456#xyz' -p ./plug.js

https://example.org/foo/bar.js?abc=123&def=456#xyz → stdout...
*** plug options.input: { url: 'https://example.org/foo/bar.js?abc=123&def=456#xyz' }
*** plug resolveId: "https://example.org/foo/bar.js?abc=123&def=456#xyz" undefined
[!] Error: Could not resolve entry module (https://example.org/foo/bar.js?abc=123&def=456#xyz).
```

**Comment by FoxDaxian** [comment]
I never use this way In any case of my work time.
build in local dev mode, local path is enough. (for most people?)
I think throw error is available approach and it is low cost and progressive

**Comment by kzc** [comment]
FWIW, this URL resolving/loading plugin works as advertised using rollup v2.60.0 with `file://` and `https://` with query parameters...

https://github.com/mjackson/rollup-plugin-url-resolve

```
$ cat sample.js 
import cc from "https://unpkg.com/lodash-es@4.17.21/camelCase.js?module";
console.log(cc("camel-case-lodash-test"));
```
```
$ rollup sample.js -p url-resolve='{cacheManager:".cache"}' --silent | node --input-type=module
camelCaseLodashTest
```
```
$ rollup "file://`pwd`/sample.js" -p url-resolve='{cacheManager:".cache"}' --silent | node --input-type=module
camelCaseLodashTest
```

It optionally maintains a local cache of fetched files to avoid unnecessary network traffic.  It does appear to work with the network disabled once the cache is primed.

I probably wouldn't want to use it for day to day work, but it's impressive nonetheless.

**Comment by romanlex** [comment]
Hello, are there any changes on this issue?
SVGR with webpack 5(asset modules) support resource query
For example:
`import Svg from './icon.svg?module'`

With rollup I can't build library from my source code((

**Comment by lukastaegert** [comment]
You just need someone to write a plugin that knows what `Svg` is supposed to be in

```
import Svg from './icon.svg?module'
```

and loads it. Likely 10 lines of code.
