### ISSUE TITLE
[!] (plugin Typescript) TypeError: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by rexkenley** [rollup/rollup#4285]
### Rollup Version

2.58.0

### Operating System (or Browser)

windows 10

### Node Version (if applicable)

16.13.0

### Link To Reproduction

https://github.com/rexkenley/rollupError

### Expected Behaviour

npm run build should build the library.

_**This was working before I did an "npm up" last week.**_

### Actual Behaviour

[!] (plugin Typescript) TypeError: Cannot read properties of undefined (reading 'text')
TypeError: Cannot read properties of undefined (reading 'text')
    at getExportedSymbolFromExportSpecifier (C:\vs\rkt\rollupError\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\util\create-export-specifier-from-name-and-modifiers.ts:48:35)
    at createExportSpecifierFromNameAndModifiers (C:\vs\rkt\rollupError\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\util\create-export-specifier-from-name-and-modifiers.ts:82:20)
    at visitEnumDeclaration (C:\vs\rkt\rollupError\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\visitor\visit-enum-declaration.ts:10:27)
    at visitNode (C:\vs\rkt\rollupError\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\visitor\visit-node.ts:25:10)
    at C:\vs\rkt\rollupError\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\track-exports-transformer.ts:19:5
    at visitNodes (C:\vs\rkt\rollupError\node_modules\typescript\lib\typescript.js:29880:30)
    at Object.forEachChild (C:\vs\rkt\rollupError\node_modules\typescript\lib\typescript.js:30122:24)
    at Object.childContinuation (C:\vs\rkt\rollupError\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\track-exports-transformer.ts:18:15)
    at visitModuleDeclaration (C:\vs\rkt\rollupError\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\visitor\visit-module-declaration.ts:9:41)
    at visitNode$c (C:\vs\rkt\rollupError\node_modules\rollup-plugin-ts\src\service\transformer\declaration-bundler\transformers\track-exports-transformer\visitor\visit-node.ts:31:10)

**Comment by rexkenley** [comment]
The issue was from an old version of rollup-plugin-ts. It was resolved by updating to the latest version.
