### ISSUE TITLE
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)

### ISSUE THREAD

**Issue by plastikfan** [rollup/rollup#4359]
### Documentation is

- [X] Missing
- [ ] Needed
- [ ] Confusing
- [ ] Not sure?

### Please Explain in Detail...

This error message in the title of this issue is reported in a way that is not very useful to the developer. The main problem with this error message is that it can be reported when you're not even trying to import a json file so it is misleading (but this issue is about documentation, not the incorrect reporting of the error, which is a separate issue in itself). I have spent way too long trying to find the solution to this and I have now found the reason why it occurs. I would like the solution to this to be added to the 'Trouble Shooting' section of the website to help others avoid this aweful pitfall. The following descibes an example of how this error can be reported and the solution:

Pre-requistes:

+ typescript in use (although I am not sure if this is a contributing factor)
+ esm module
+ client code tries to import from a commonjs package, in this case 'expressjs/express'
 (I am currently using rollup-plugin-typescript2, but i think this would also apply to @rollup/plugin-typescript)

client code:

```javascript
import express from "express";
```

when this is built, you will see something like this:

```
[16:21:47] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:10332:30)
    at Module.error (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12251:16)
    at Module.tryParse (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12654:25)
    at Module.setSource (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12557:24)
    at ModuleLoader.addModuleSource (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:22021:20)
```

Taking a look at express's root level index.js reveals the following:

```javascript
module.exports = require('./lib/express');
```

which is commonjs notation. Ideally. esm should be natively supported by express and I may even raise an issue there. But this error can occur on any 3rd party non esm package, so should be highlighted in the rollup documentation as its a rollup error message.

### Your Proposal for Changes

The solution is to use esm form of require:

```javascript
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const express = require("express");
```

Please can you add this to the trouble shooting section. Thanks.

Proposed explanation text:

When authoring an esm module that is bundled with rollup, care must be taken when importing from commonjs packages that do not natively support [esm](https://nodejs.org/api/esm.html). Taking [express](https://github.com/expressjs/express) as an example, the esm way of importing express would be:

```javascript
import express from "express";
```

However, doing so may cause an error message like so:

```
[16:21:47] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:10332:30)
    at Module.error (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12251:16)
    at Module.tryParse (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12654:25)
    at Module.setSource (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12557:24)
    at ModuleLoader.addModuleSource (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:22021:20)
```

This is because express does not currently natively support esm and the same applies to all other 3rd party commonjs packages. The user needs to investigate the package being imported. In the case of express, the following is present in the root index.js file:

```javascript
module.exports = require('./lib/express');
```

whch is commonjs not esm notation. To accomodate this, the client needs to adjust the import to the esm version of [require](https://nodejs.org/api/esm.html#differences-between-es-modules-and-commonjs) and in this case would be adjusted to:

```javascript
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const express = require("express");
```

**Comment by dnalborczyk** [comment]
I'm trying to think where to start, there's a lot o unpack. that makes it even harder not knowing how much knowledge you have about the tooling involved. it would also make it easier if you would provide a small repro. it all depends on what you are trying to accomplish, and what settings you use.

**Comment by plastikfan** [comment]
Hi @dnalborczyk, sorry its been awhile, I had a few issues to deal with, I meant to get back to you sooner. After considering your comments, actually the one about bundling express, that made me realise that I had forgotten to add express to the externals in the rollup config. So I did and reverted back to using a regular import (import express from 'express';), this actually works. So my initial solution is not required. And for what its worth, yeah I am a beginner using rollup, although I have been doing javascript/typescript for a while, but its issues like this (and there has been loads of them) that constantly prevent me from making progress in the projects I'm working on. And the current state of javascript being in a transition from commonjs to esm does not help in the slightest.

So considering this, there is still useful information that could be included in the trouble shooting section. Seeing:

```
[18:50:38] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:10332:30)
    at Module.error (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12251:16)
    at Module.tryParse (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12654:25)
    at Module.setSource (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:12557:24)
    at ModuleLoader.addModuleSource (file:///home/plastikfan/dev/tutorials/auth0/auth0-node-express-tut/node_modules/rollup/dist/es/shared/rollup.js:22021:20)
```

is not helpful as it bears absolutely no resemblance to the real error.

**Comment by dnalborczyk** [comment]
>  that made me realise that I had forgotten to add express to the externals in the rollup config. So I did and reverted back to using a regular import (import express from 'express';), this actually works. 

not sure if you know, but adding `express` to externals results in **not** bundling `express`.

> And the current state of javascript being in a transition from commonjs to esm does not help in the slightest.

you are not alone, it's a B.I.G. HUUUGE clusterfuck. 😄 

> So considering this, there is still useful information that could be included in the trouble shooting section. Seeing:
> 
> ```
> [18:50:38] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
> is not helpful as it bears absolutely no resemblance to the real error.

you are welcome to create a PR with any improvements, be it the code, the docs, or anything else. it's always appreciated!

> For what its worth, the repo I've been work on is: [auth0/node-express tutorial](https://github.com/plastikfan/auth0-node-express-tut).

thanks for the pointer. some additional advice, if you don't mind: `gulp` has been pretty much replaced by just using (npm) scripts. as you can see, the library has been unmaintained for 3+ years. I would not start a greenfield project with `gulp` nor a `try-out` project. same applies to `grunt` or similar. the other problem is that the `.env` file is missing.

**Comment by plastikfan** [comment]
argh, yeah, I forgot to mention that yu just need to create an empty .env file. Also, I don't want to bundle express. I use rollup just to bundle the internal code and want all 3rd party packages to remain external.

And your comment about gulp/grunt is a bit of a bomb going off in my face. I hadnt realised that that appraoch want being consigned to the dustbin and I've spun my wheels for weeks now getting a gulp setup in place. What a huge waste of energy :(

Thanks for the useful info, I'll probably be dropping gulp now after this.

**Comment by khusamov** [comment]
I have a similar error. The JSON file itself is error-free!

How to fix it?

```
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules/prettier/package.json (2:8)
1: {
2:   "name": "prettier",
           ^
3:   "version": "2.6.1",
4:   "description": "Prettier is an opinionated code formatter",

```

**Comment by tripolskypetr** [comment]
DEPRECATE THE `@rollup/plugin-json` and IMPLEMENT INTERNAL SOLUTION WITHOUT BUGS.

It going to be much better to deprecate that shitcode and give the opportunity to the community to reimplement without that quite informating situation description error messages and spam

```bash
(plugin json) RollupError: Could not parse JSON file
```
