### ISSUE TITLE
TypeError: declaration.run is not a function

### ISSUE THREAD

**Issue by bcherny** [rollup/rollup#442]
what could cause this?

i'm using:

- gulp-rollup
- rollup-plugin-babel
- rollup-plugin-commonjs
- rollup-plugin-npm

```js
function buildJs (src, dest) {
  return () => gulp
    .src(src)
    .on('error', jsError)
    .pipe(rollup({
      plugins: [
        commonjs({}),
        babel({ runtimeHelpers: true }),
        npm({
          browser: true,
          jsnext: true,
          main: true,
          skip: ['react', 'react-dom', 'react-router']
        })
      ]
    }))
    .pipe(gulp.dest(path.dirname(dest)))
}
```

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: declaration.run is not a function
    at Object.walk.enter (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5336:23)
    at visit (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5185:9)
    at visit (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5209:4)
    at visit (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5206:5)
    at visit (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5206:5)
    at visit (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5206:5)
    at visit (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5209:4)
    at visit (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5206:5)
    at visit (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5209:4)
    at walk (/Users/boris/Sites/foo/client/node_modules/rollup/dist/rollup.js:5163:2)
```

**Comment by Rich-Harris** [comment]
Hmm. Are you able to whittle it down to a reproduction of the bug that you can share (i.e. removing all imports that don't cause the bug to appear)? It sounds like the bug is in Rollup itself.

**Comment by bcherny** [comment]
it seems that importing [history](https://github.com/rackt/history) is causing the issue. i use it like this:

```js
import * as createBrowserHistory from 'history/lib/createBrowserHistory'

createBrowserHistory()
// ...
```

**Comment by Victorystick** [comment]
You can't _call_ an imported namespace (`* as foo`). Try changing your import to
```js
import createBrowserHistory from 'history/lib/createBrowserHistory'
```

**Comment by bcherny** [comment]
that was it! thanks!
