### ISSUE TITLE
[BUG] Rollup fails to build react-router on windows 11 machine

### ISSUE THREAD

**Issue by incepter** [rollup/rollup#4462]
Hello,

I created the following issue on react-router's repo, but I know the issue is related to rollup.

The build passes on a linux container (even inside windows). But fails every time in windows.

https://github.com/remix-run/react-router/issues/8791

## What version of React Router are you using?
latest

## Steps to Reproduce
On a windows (tested on 11) machine, perform the following:

Fork the repo on github
- git clone the forked repo
- cd react-router
- yarn
- yarn build

## Expected Behavior
The build process to succeed

Actual Behavior
Fails to resolve several modules, see screenshot

![image](https://user-images.githubusercontent.com/8569885/163222223-2f6aef67-c02b-45cf-bba3-b83285d92a40.png)

Here is the command output:

```
PS C:\github\react-router> yarn build
yarn run v1.22.15
$ rollup -c && tsc -b

packages/react-router/index.ts → build/node_modules/react-router/index.js...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
copied:
  packages/react-router/package.json → build\node_modules\react-router\package.json
  packages/react-router/README.md → build\node_modules\react-router\README.md
  LICENSE.md → build\node_modules\react-router\LICENSE.md
[!] Error: Could not resolve './lib/components' from packages\react-router\index.ts
Error: Could not resolve './lib/components' from packages\react-router\index.ts
    at error (C:\github\react-router\node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (C:\github\react-router\node_modules\rollup\dist\shared\node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (C:\github\react-router\node_modules\rollup\dist\shared\node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (C:\github\react-router\node_modules\rollup\dist\shared\node-entry.js:38:28)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by incepter** [comment]
Watching also doesn't work when watching from within a docker container and the file was edited in the host.

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide a link to one by:
>   1. Using the REPL at https://rollupjs.org/repl/, or
>   2. Using the REPL.it reproduction template at https://repl.it/@rollup/rollup-repro
>      (allows full use of all rollup options and plugins), or
>   3. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.

Could you please reformat your issue using our template, and provide a reproduction that meets our requirements?

**Comment by incepter** [comment]
Hello,

The issue is more related to some platform specific code.

It happens to me on two windows machine running both windows 11.

I just forked react-router's repo and all I did was yarn install and yarn build.

So, I don't know how can I provide a reproduction with the above with the given issue template ?

Sorry for the inconvenience.

**Comment by senseibarni** [comment]
I have the same issue on Windows 10 :(
It happened after splitting index.ts into files inside the `lib` folder in the react-router package.

**Comment by incepter** [comment]
> looks like react-router confgiuration issues rather than

I didn't sincerely investigate the source of the issue, but WSL did solve the problem temporarily for me.
