### ISSUE TITLE
Rollup with Configuration Fails on Windows subst drive

### ISSUE THREAD

**Issue by shawnwildermuth** [rollup/rollup#4465]
### Rollup Version

2.70.1

### Operating System (or Browser)

Windows 10

### Node Version (if applicable)

16.x

### Link To Reproduction

https://github.com/shawnwildermuth/rollup-bug

### Expected Behaviour

While on a subst drive (e.g. my d:\...\rollup-bug is native drive, but p:/ is mapped to that directory), it should compile with a configuration file. 

Should work with configuration on subst drive.

### Native drive:

```
> rollup main.js
```

Works fine.

```
rollup.js -c
```

Works Fine

### Mapped Drive (e.g. subst):

```
> rollup main.js
```

Works fine.

```
rollup.js -c
```
Errors out:

```
[!] SyntaxError: Unexpected token 'export'
P:\rollup-bug\rollup.config.js:1
export default {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\shawn\AppData\Roaming\npm\node_modules\rollup\dist\shared\loadConfigFile.js:617:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (C:\Users\shawn\AppData\Roaming\npm\node_modules\rollup\dist\shared\loadConfigFile.js:622:42)
```

**Comment by dnalborczyk** [comment]
@shawnwildermuth I was not able to repro, could you have a look at this ci run:

https://github.com/dnalborczyk/rollup-bug/runs/6203158031?check_suite_focus=true

**Comment by shawnwildermuth** [comment]
Awesome, thanks!
