### ISSUE TITLE
Error in getAugmentedNamespace

### ISSUE THREAD

**Issue by AlexRMU** [rollup/rollup#4620]
### Rollup Version

2.77.0

### Operating System (or Browser)

Windows 10 

### Node Version (if applicable)

16.15.0

### Link To Reproduction

I can not

### Expected Behaviour

Everything is fine

### Actual Behaviour

I use:
```json
{
"@rollup/plugin-commonjs": "^22.0.2",
"@rollup/plugin-node-resolve": "^13.3.0",
"vite": "^3.0.9",
}
```

```js
import { defineConfig } from "vite";
import { builtinModules } from "module";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";

export default defineConfig({
    build: {
        target: "node14",
        rollupOptions: {
            external: ["./handler.js", ...builtinModules],
            input: "./src/server.js",
            output: {
                format: "es",
            },
            plugins: [
                commonjs({}),
                resolve({}),
            ]
        },
        emptyOutDir: false,
        outDir: "./build/",
        ssr: "./src/server.js",
    },
    ssr: {
        noExternal: true,
    },
});
```
Error:
```
TypeError: Class constructor LRUCache cannot be invoked without 'new'
    at new a (file:///.../build/server.js:60:20)
    at requireRange (file:///.../build/server.js:10701:21)
    at server.js (file:///.../build/server.js:11035:21)
    at __require (file:///.../build/server.js:3:50)
    at file:///.../build/server.js:36579:16
```
Build:
```js
function getAugmentedNamespace(n) {
    var f = n.default;
    if (typeof f == "function") {
    var a = function () {
        return f.apply(this, arguments); //!!! here
    };
    a.prototype = f.prototype;
    } else
    a = {};
    Object.defineProperty(a, "__esModule", { value: true });
    Object.keys(n).forEach(function (k) {
    var d2 = Object.getOwnPropertyDescriptor(n, k);
    Object.defineProperty(a, k, d2.get ? d2 : {
        enumerable: true,
        get: function () {
        return n[k];
        }
    });
    });
    return a;
}

...

class LRUCache { ... }

...

var lruCache = LRUCache;
const lruCache$1 = /* @__PURE__ */ _mergeNamespaces({
    __proto__: null,
    default: lruCache
}, [lruCache]);
const require$$0$r = /* @__PURE__ */ getAugmentedNamespace(lruCache$1);
```
If I change the settings, `require is not defined in ES module` will appear, etc.

**Comment by Tanimodori** [comment]
Vite itself includes `@rollup/plugin-node-resolve` and `@rollup/plugin-commonjs`. Can you reproduce this bug using pure rollup? What's the actual code of `server.ts`?

**Comment by AlexRMU** [comment]
I can't reproduce it now. Maybe someone else can. Or it is solved.
The code from the bundle above came from the `googleapis` library.

**Comment by kotasudhakar** [comment]
I am also facing this issue quite a lottttt, it all started when i started using the `vite-plugin-node-polyfills` plugin. But it does happen at random times to be honest for me. sometimes it will get sorted out when restarted but from next time i was stuck as this is still there.

I am using electron-vite, with react

**Comment by kotasudhakar** [comment]
> Finally got the reason why it is happening
> 
> i have included these two libraries as dependencies in package json in electron
> 
> ```
> "@ericblade/quagga2": "1.8.4",
> 
>  "@ericblade/quagga2-reader-qr": "git+https://github.com/ericblade/quagga2-reader-qr.git"
> ```
> 
> These libraries both are only being used in the main process of electron and when i try to build it with vite rollup config as below
> 
> ```
> main: {
>         build: {
>                 output: {
>                     manualChunks: (id) => {
>                         if (id.includes('node_modules')) {
>                             const chunk = id.toString().split('node_modules/')[1]
>                             const chunkName = chunk.split('/')[0]
>                             return `vendor-${chunkName}`
>                         }
>                     },
>                 },
>             },
>         },
>     },
> ```
> 
> this below error occurs
> 
> ```
> App threw an error during load
> TypeError: vendor__ericblade.getAugmentedNamespace is not a function
>     at Object.<anonymous> (D:\work\zero-lens\out\main\chunks\vendor-gl-matrix-NOn1zxZD.App threw an error during load
> TypeError: vendor__ericblade.getAugmentedNamespace is not a function
>     at Object.<anonymous> (D:\work\zero-lens\out\main\chunks\vendor-gl-matrix-NOn1zxZD.js:3905:54)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
>     at Module.load (node:internal/modules/cjs/loader:1098:32)
>     at Module._load (node:internal/modules/cjs/loader:945:12)
>     at c._load (node:electron/js2c/node_init:2:13672)
>     at Module.require (node:internal/modules/cjs/loader:1122:19)
>     at require (node:internal/modules/helpers:130:18)
>     at Object.<anonymous> (D:\work\zero-lens\out\main\chunks\vendor-@ericblade-CKr16m8d.js:2:24)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
> (node:2704) Warning: Accessing non-existent property 'getAugmentedNamespace' of module exports inside circular dependency
> (Use `electron --trace-warnings ...` to show where the warning was created)
> ```

Later i tried to remove the rollup->outputconfig of chunking for main process and i have only put it for the render process and it works  like a charm

Could someone please fix this

**Comment by lukastaegert** [comment]
This is part of `@rollup/plugin-commonjs`, not Rollup core. https://github.com/rollup/plugins/blob/9e7f576f33e26d65e9f2221d248a2e000923e03f/packages/commonjs/src/helpers.js#L37-L61
Any PR to improve the logic is welcome. This original problem might probably be detected via [`new.target`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target).
The issues in the last post probably have a different reason like `manualChunks` messing up execution order.

**Comment by kotasudhakar** [comment]
Not sure how that is @lukastaegert  as i am not using ```@rollup/plugin-commonjs``` package

**Comment by lukastaegert** [comment]
Well, you are using Vite, and Vite is adding the plugin for you.
