### ISSUE TITLE
Its working on `yarn dev` but after build, and preview its showing an error.

### ISSUE THREAD

**Issue by BroJenuel** [rollup/rollup#4636]
So I actually created a project when I run in yarn dev, eveything works perfectly but after build and preview it this error shows in my console:

 here is a repository: https://github.com/BroJenuel/believers-sword-web
```bash
yarn preview
yarn run v1.22.19
$ nuxt preview
Nuxi 3.0.0-rc.9                                                                                                                                                      19:57:31
i Node.js version: 16.16.0                                                                                                                                           19:57:31
i Preset: node-server                                                                                                                                                19:57:31
i Working dir: .output                                                                                                                                               19:57:31
i Loading .env. This will not be loaded when running the server in production.                                                                                       19:57:31
i Starting preview command: node ./server/index.mjs                                                                                                                  19:57:31
                                                                                                                                                                     19:57:31
Listening on http://0.0.0.0:3000/
[nuxt] [request error] [unhandled] [500] Named export 'VBinder' not found. The requested module 'vueuc' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vueuc';
const { resizeObserverManager, VResizeObserver, VirtualList, VFollower, VFocusTrap, VBinder, VTarget, VOverflow, VLazyTeleport } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:303:24
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:359:64
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:28:22
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (/D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/node_modules/h3/dist/index.mjs:538:7)
[nuxt] [request error] [unhandled] [500] Named export 'VBinder' not found. The requested module 'vueuc' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vueuc';
const { resizeObserverManager, VResizeObserver, VirtualList, VFollower, VFocusTrap, VBinder, VTarget, VOverflow, VLazyTeleport } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:303:24
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:359:64
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:28:22
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (/D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/node_modules/h3/dist/index.mjs:538:7)
[nuxt] [request error] [unhandled] [500] Named export 'VBinder' not found. The requested module 'vueuc' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vueuc';
const { resizeObserverManager, VResizeObserver, VirtualList, VFollower, VFocusTrap, VBinder, VTarget, VOverflow, VLazyTeleport } = pkg;

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:303:24
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:359:64
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/chunks/renderer.mjs:28:22
  at async /D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/node_modules/h3/dist/index.mjs:592:19
  at async Server.nodeHandler (/D:/Projects/_PersonalProjects/Believers%20Sword%20Project/believers-sword-web-new/.output/server/node_modules/h3/dist/index.mjs:538:7)
```

![image](https://user-images.githubusercontent.com/31676163/188873556-2ee6ff31-2a86-4d07-90f6-f350d9be9681.png)

**Comment by Developer27149** [comment]
Me too.

**Comment by Developer27149** [comment]
@BroJenuel hey.I know,I forget to config production config in nuxt.config.ts.
Just need to append this:
```typescript
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile:
      process.env.NODE_ENV === 'production'
        ? [
            'naive-ui',
            'vueuc',
            '@css-render/vue3-ssr',
            '@juggle/resize-observer'
          ]
        : ['@juggle/resize-observer']
  },
  vite: {
    optimizeDeps: {
      include:
        process.env.NODE_ENV === 'development'
          ? ['naive-ui', 'vueuc', 'date-fns-tz/esm/formatInTimeZone']
          : []
    }
  }
})
```

**Comment by BroJenuel** [comment]
@Developer27149 thanks mate,, I deleted my current project and create a new one from scratch.
