### ISSUE TITLE
Rollup ignores imported library "main" and fails to import TypeScript files when present

### ISSUE THREAD

**Issue by smallstepstoday** [rollup/rollup#4695]
### Rollup Version

3.2.3

### Operating System (or Browser)

Not Specific

### Node Version (if applicable)

v18.12.0

### Link To Reproduction

https://replit.com/@smallstepstoday/rollup-import-issue-repro?v=1

### Expected Behaviour

One or both of the following:
- `rollup` should import starting with the package `"main"` entry.
- The TypeScript plugin should ignore TypeScript files that are "riding along" in an imported library and not imported via the "main" entry. Obviously if a package main is `"index.ts"`, then it should process the files that are needed. Otherwise, they should not be processed.

### Actual Behaviour

The build fails, producing output similar to the following:
```bash
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/@josephg/resolvable/index.ts (1:7)
1: export type Resolvable<T> = Promise<T> & {
          ^
2:   resolve: (t: T) => void,
3:   reject: (e: any) => void,
RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:206:30)
    at Module.error (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:13310:16)
    at Module.tryParse (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:13684:25)
    at Module.setSource (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:13594:24)
    at ModuleLoader.addModuleSource (/home/runner/rollup-issue-repro-1/node_modules/rollup/dist/shared/rollup.js:22913:20)
```

**Comment by smallstepstoday** [comment]
I was digging into the issue and found the following:
- The `@josephg/resolvable` correctly resolves to `".../node_modules/@josephg/resolvable/index.js"` on the first pass.
- It then goes through another pass through `resolveIdViaPlugins` with `".../node_modules/@josephg/resolvable/index.js"` as `source`. It is during this pass that it is switched to `index.ts`. Here is the call stack at the point where the switch is made:
```
nodeModuleNameResolverWorker (.../typescript@4.8.4/node_modules/typescript/lib/typescript.js:44034)
nodeModuleNameResolver (.../typescript@4.8.4/node_modules/typescript/lib/typescript.js:44006)
resolveModuleName (.../typescript@4.8.4/node_modules/typescript/lib/typescript.js:43733)
<anonymous> (.../@rollup+plugin-typescript@9.0.2.../node_modules/@rollup/plugin-typescript/dist/es/index.js:48)
resolveId (.../@rollup+plugin-typescript@9.0.2.../node_modules/@rollup/plugin-typescript/dist/es/index.js:803)
<anonymous> (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23664)
processTicksAndRejections (internal/process/task_queues:95)
Promise.then (Unknown Source:0)
runHook (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23659)
<anonymous> (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23565)
processTicksAndRejections (internal/process/task_queues:95)
Promise.then (Unknown Source:0)
hookFirst (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23562)
resolveIdViaPlugins (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:22541)
resolveId (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:22545)
ModuleLoader.resolveId (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:22795)
resolve (.../rollup@3.2.3/node_modules/rollup/dist/shared/rollup.js:23490)
handler (.../@rollup+plugin-node-resolve@15.0.1_rollup@3.2.3/node_modules/@rollup/plugin-node-resolve/dist/es/index.js:1235)
processTicksAndRejections (internal/process/task_queues:95)
```
Hopefully this helps identify the logic that results in making the switch. Thanks for all the hard work! This is such a great toolset.

**Comment by lukastaegert** [comment]
This is very likely a bug somewhere between the node-resolve and typescript plugins. Nothing rollup core can do anything about.
Incidentally, I stumbled upon this very issue myself some time ago and solved it the hard way:

```js
const fixResolvablePlugin = {
      name: 'fix-resolve-resolvable',
      async resolveId(source, importer, options) {
        if (source === '@josephg/resolvable') {
          const result = await this.resolve(source, importer, { ...options, skipSelf: true });
          result.id = result.id.replace(/index.ts$/, 'index.js');
          return result;
        }
      },
    }
}
```

But this is not a fix. Maybe open an issue in the plugins repo?
