### ISSUE TITLE
Memory grow with rollup 3.19

### ISSUE THREAD

**Issue by Mister-Hope** [rollup/rollup#4904]
### Rollup Version

3.19.1

### Operating System (or Browser)

Ubuntu 22.04 (WSL)

### Node Version (if applicable)

18.15.0

### Link To Reproduction

https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/2906

(https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/f1beda027224e3fcdf8c191bf2e564577e8eae67 is working fine)

### Expected Behaviour

I am expecting Rollup can build.

All project using vite (which relies on rollup) run out of memory

I believe rollup have memory leak because webpack actually takes more memory comparing with vite, but all vite ci blows with rollup changing from 3.18.0 to 3.19.1.

If rollup itself runs well all time, perhaps vite can not handle rollup change? Anyway, I hope someone can check why the memory is increasing in my case (At least > 300MB with the version change)

### Actual Behaviour

Run out of memory.

**Comment by kachurun** [comment]
I have the same issue with 3.18

<img width="744" alt="Screenshot 2023-03-15 at 14 18 06" src="https://user-images.githubusercontent.com/12369041/225320288-22d4bf17-a3fa-48aa-8889-f948cf3b0826.png">

**Comment by Mister-Hope** [comment]
> There was additional analysis added in 3.19.0 that might explain a moderate increase in memory consumption.

Thanks for the reply, but I think the additional analysis take no less than 15% extra memory. Can we get a chance to see if we can optimize it?

**Comment by wangyong991** [comment]
RangeError: Maximum call stack size exceeded
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8972:43)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///Users/project/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)

**Comment by cpauwels** [comment]
I also have what I believe is a related issue with building all my Nuxt projects (Related issue: https://github.com/unjs/nitro/issues/1063)

**Comment by lukastaegert** [comment]
A maximum call stack exceeded error looks like an actual bug in Rollup. If we can have a reproduction for the issue, even a complicated one, then I can have a look.

**Comment by warflash** [comment]
Hey @lukastaegert in case you're still looking for a reproduction there's this issue over on nuxt https://github.com/nuxt/nuxt/issues/19824 containing a repro + CI logs

**Comment by lukastaegert** [comment]
I am looking for a reproduction for “Maximum call stack size exceeded”, not “JavaScript heap out of memory”. Those are very different problems.

**Comment by RadiumAg** [comment]
Me too, I restore to "rollup 3.10.0"  that resolve this problems

**Comment by hi-reeve** [comment]
does this solved with the latest version?

**Comment by kalvenschraut** [comment]
https://github.com/nuxt/nuxt/issues/19783#issuecomment-1494464055 @lukastaegert

Looks like a nuxt user was able to figure out a repo in his comment for the callstack error. Found it after digging into myself why I was getting this issue and seems to point to rollup 3.19 as with rollup at 3.18, my build succeeds with no error.

**Comment by Darkmift** [comment]
I believe I am experiening a similar/related issue

sharing this log in hope it might help
my build fails and trying rn to reproduce witha blank project...will update this message asap

```
Maximum call stack size exceeded
error during build:
RangeError: Maximum call stack size exceeded
    at ObjectEntity.deoptimizeArgumentsOnInteractionAtPath (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:6043:43)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:8597:36)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:8589:45)
    at FunctionExpression.deoptimizeArgumentsOnInteractionAtPath (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:8973:15)
    at ParameterVariable.addEntityToBeDeoptimized (file:///***/client/node_modules/rollup/dist/es/shared/node-entry.js:6779:20)
```

**Comment by danielroe** [comment]
From what I can tell, the issue seems to be caused by https://github.com/rollup/rollup/pull/4892.

Here are two stackblitzes:

* [failing] Nuxt + `lodash-es`: https://stackblitz.com/edit/nuxt-starter-7hztxb.
* [working] The same repo but pinned to v3.18.0: https://stackblitz.com/edit/nuxt-starter-wunnhm.

You can update the resolution to just 3.19.0 to reproduce the issue, if that's helpful to narrow down the issue.

**Comment by RadiumAg** [comment]
> From what I can tell, the issue seems to be caused by #4892.
> 
> Here are two stackblitzes:
> 
> * [failing] Nuxt + `lodash-es`: https://stackblitz.com/edit/nuxt-starter-7hztxb.
> * [working] The same repo but pinned to v3.18.0: https://stackblitz.com/edit/nuxt-starter-wunnhm.
> 
> You can update the resolution to just 3.19.0 to reproduce the issue, if that's helpful to narrow down the issue.

yes, you are right

**Comment by lukastaegert** [comment]
I created #4938 to improve the situation, feedback welcome.

**Comment by ddahan** [comment]
@lukastaegert It helps, as a [bug reproduction using Nuxt](https://stackblitz.com/edit/nuxt-starter-6usrbo?file=components/TestFailing.vue) now works.
My (bigger) Nuxt project still raise the error though, so I would not consider the issue solved. Have to try to build a reproduction case from my project.
