### ISSUE TITLE
vue files error import issue

### ISSUE THREAD

**Issue by shaynababe** [rollup/rollup#4928]
Hey there! If you need help or tech support then this is not the place to ask. Please head to the [Rollup Discord](https://is.gd/rollup_chat) instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

If you arrived here because you think Rollup's documentation is unclear, insufficient or wrong, please consider creating an issue for the documentation instead.
installed the plugins all and vite vue 
attached the is log from rollup and my files
[zz.txt](https://github.com/rollup/rollup/files/11163957/zz.txt)
[m2.mjs.txt](https://github.com/rollup/rollup/files/11163979/m2.mjs.txt)
[package.json.txt](https://github.com/rollup/rollup/files/11163981/package.json.txt)
[rollup.config.dev.js.new.txt](https://github.com/rollup/rollup/files/11163982/rollup.config.dev.js.new.txt)

```bash
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/api/overlays/components/ProgressDialogComponent.vue (1:0)
1: <template>
   ^
2: <dialog-component>
3:     <progress-component :model="model" />
    at error (/usr/lib/node_modules/rollup/dist/shared/rollup.js:274:30)
    at Module.error (/usr/lib/node_modules/rollup/dist/shared/rollup.js:13820:16)
    at Module.tryParse (/usr/lib/node_modules/rollup/dist/shared/rollup.js:14497:25)
    at Module.setSource (/usr/lib/node_modules/rollup/dist/shared/rollup.js:14107:39)
    at ModuleLoader.addModuleSource (/usr/lib/node_modules/rollup/dist/shared/rollup.js:24072:20)
```

**Comment by Tanimodori** [comment]
```js
// rollup.config.js
export default {
input [ /* ... */],
output: [
 {
file: 'bundle.js',
format: 'cjs'
},
{
file: 'bundle.min.js',
format: iife,
name: 'version',
plugins: [terser()]
}
],
plugins: [json()]
};
```

It seems you have missing vue plugin here. Try to add them into your config.

**Comment by shaynababe** [comment]
thank you for input
input [ /* ... */],

import vue from 'rollup-plugin-vue'
import json from '@rollup/plugin-json';
export default {
plugins: [vue()]
input:{}
file: 'src/images/favicons/index.js',

file: 'src/src/selection/Selection.js',

file: 'src/api/api.js',

file: 'src/api/priority/PriorityAPI.js',

file: 'src/api/types/TypeRegistrySpec.js',

file: 'src/api/types/index.js',

file: 'src/api/status/StatusAPISpec.js',

file: 'src/api/EditorSpec.js',

file: 'src/api/overlays/ProgressDialog.js',
correct syntax error

**Comment by shaynababe** [comment]
hello
Still have issues 
The config seems fine the m2.js is ok 
rollup -c has error messages
@/utils/testing (imported by "src/plugins/timeline/pluginSpec.js")
[!] RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/api/overlays/components/ProgressDialogComponent.vue (1:0)
1: <template>
   ^
2: <dialog-component>
3:     <progress-component :model="model" />
    at error (/usr/lib/node_modules/rollup/dist/shared/rollup.js:274:30)
    at Module.error (/usr/lib/node_modules/rollup/dist/shared/rollup.js:13820:16)
    at Module.tryParse (/usr/lib/node_modules/rollup/dist/shared/rollup.js:14497:25)
    at Module.setSource (/usr/lib/node_modules/rollup/dist/shared/rollup.js:14107:39)
    at ModuleLoader.addModuleSource (/usr/lib/node_modules/rollup/dist/shared/rollup.js:24072:20)


(base) z@spin7:~/code/z/z2/rollupjs.org/my-rollup-project$ rollup -c rollup.config.js
[!] SyntaxError: Named export 'vue' not found. The requested module 'rollup-plugin-vue' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'rollup-plugin-vue';
const { vue } = pkg;

^^^ this give error

file:///home/z/code/z/z2/rollupjs.org/my-rollup-project/rollup.config.js:9
import { vue } from 'rollup-plugin-vue';
         ^^^
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Can you assist ? the vue plugin is installed now the package.json is good
The rollupconfig is one the was created and is working
[rollup.config.js.txt](https://github.com/rollup/rollup/files/11171192/rollup.config.js.txt)
import { vue } from 'rollup-plugin-vue';
//import { vue } from '@vitejs-plugin-vue';
//import { json } from 'rollup/plugin-json';
import config from 'sapper/config/rollup.js';
//import pkg from '/package.json';
const mode = process.env.NODE_ENV;
const dev = mode === 'development';
const legacy = !!process.env.SAPPER_LEGACY_BUILD;
//import pkg from 'rollup-plugin-vue';



const onwarn = (warning, onwarn) =>
	(warning.code === 'MISSING_EXPORT' && /'preload'/.test(warning.message)) ||
	(warning.code === 'CIRCULAR_DEPENDENCY' && /[/\\]@sapper[/\\]/.test(warning.message)) ||
	onwarn(warning);

export default {
	client: {
		input: config.client.input(),
		
		plugins: [
		vue(),
		],
