### ISSUE TITLE
MagicString.update throws error on build

### ISSUE THREAD

**Issue by estubmo** [rollup/rollup#4945]
### Rollup Version

3.20.5

### Operating System (or Browser)

WSL2 - Ubuntu 20.04.5

### Node Version (if applicable)

Node v18.15.0

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-2dfoda

### Expected Behaviour

Run `pnpm build` with script
`"build": "tsup src/index.ts --format esm,cjs --dts"`

Fails since `3.20.5`, works on` 3.20.4` which you can confirm by adding
 ```
"pnpm": {
    "overrides": {
      "tsup>rollup": "3.20.4"
    }
  },
```
to the package.json.

tsup should build the repository as such:
```
CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Target: es2018
ESM Build start
CJS Build start
DTS Build start
ESM dist/index.mjs 150.00 B
CJS dist/index.js 1.15 KB
ESM ⚡️ Build success in 838ms
CJS ⚡️ Build success in 838ms
DTS ⚡️ Build success in 1095ms
DTS dist/index.d.ts 109.00 B
```

### Actual Behaviour

Without the rollup version override,  `pnpm build`  with script

`"build": "tsup src/index.ts --format esm,cjs --dts"`

returns
```
CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Target: es2018
ESM Build start
CJS Build start
DTS Build start
ESM dist/index.mjs 150.00 B
ESM ⚡️ Build success in 815ms
CJS dist/index.js 1.15 KB
CJS ⚡️ Build success in 816ms
Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead
    at MagicString.update (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:2142:10)
    at MagicString.overwrite (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:2131:15)
    at Identifier.render (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:8762:22)
    at AssignmentPattern.render (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:9439:19)
    at FunctionDeclaration.render (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:6346:28)
    at renderStatementList (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:8913:35)
    at Program.render (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:12199:13)
    at Module.render (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:14105:18)
    at Chunk.renderModules (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:16554:41)
    at Chunk.render (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:16062:111)
Error: error occured in dts build
    at Worker.eval (file:///home/projects/rollup-repro-2dfoda/node_modules/.pnpm/tsup@6.7.0_typescript@5.0.4/node_modules/tsup/dist/index.js:2281:26)
    at EventEmitter.emit (https://rolluprepro2dfoda-1vsq.w-credentialless.staticblitz.com/blitz.c8358679.js:35:156830)
    at _0x3cbdc4.<anonymous> (https://rolluprepro2dfoda-1vsq.w-credentialless.staticblitz.com/blitz.c8358679.js:35:934951)
    at [nodejs.internal.kHybridDispatch] (https://rolluprepro2dfoda-1vsq.w-credentialless.staticblitz.com/blitz.c8358679.js:35:413600)
    at t.emitMessage (https://rolluprepro2dfoda-1vsq.w-credentialless.staticblitz.com/blitz.c8358679.js:35:1134926)
    at <computed>._source.<computed>.<computed> (https://rolluprepro2dfoda-1vsq.w-credentialless.staticblitz.com/blitz.c8358679.js:44:83400)
DTS Build error
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by lukastaegert** [comment]
Thanks, this is very helpful. I will roll back the last update while we can use your reproduction to figure out what went wrong.

**Comment by elboletaire** [comment]
Same here! I've just discovered right now it affects from version 2.0.5 (versions 2.0.4 and before are working OK).
