### ISSUE TITLE
rollup works with npm and not pnpm when dependence ssh2

### ISSUE THREAD

**Issue by x-wink** [rollup/rollup#5019]
### Rollup Version

3.23.0

### Operating System (or Browser)

windows10

### Node Version (if applicable)

v18.16.0

### Link To Reproduction

https://github.com/x-wink/wink-sftp

### Expected Behaviour

boundle successify

### Actual Behaviour

got an error when boundle
```
[!] RollupError: Could not resolve "../build/Release/cpufeatures.node" from "../build/Release/cpufeatures.node?commonjs-external"
../build/Release/cpufeatures.node?commonjs-external
    at error (E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:278:30)
    at ModuleLoader.handleInvalidResolvedId (E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:24485:24)
    at E:\WorkSpace\wink-sftp\node_modules\.pnpm\rollup@3.23.0\node_modules\rollup\dist\shared\rollup.js:24447:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by x-wink** [comment]
[ssh2 repled me](https://github.com/mscdex/ssh2/issues/1304) this isn't their problem,should be pnpm
I think maybe cause by rollup or pnpm?sry I don't known

**Comment by noherczeg** [comment]
@x-wink I had issues with pnpm + Win10 because my IDE locked files. This might be a similar case.
