### ISSUE TITLE
Internal crash on empty export

### ISSUE THREAD

**Issue by ochafik** [rollup/rollup#503]
`export { };` yields the following internal error ([see it live](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22export%20%7B%7D%3B%22%7D%5D%7D)):

```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at Module.addExport (./node_modules/rollup/www/ROLLUP/rollup/src/Module.js:124:21)
    at ./node_modules/rollup/www/ROLLUP/rollup/src/Module.js:168:51
    at Array.forEach (native)
    at Module.analyse (./node_modules/rollup/www/ROLLUP/rollup/src/Module.js:166:19)
    at new Module (./node_modules/rollup/www/ROLLUP/rollup/src/Module.js:59:8)
    at ./node_modules/rollup/www/ROLLUP/rollup/src/Bundle.js:168:20
    at tryCatch (./node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:182:12)
    at invokeCallback (./node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:194:13)
    at publish (./node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:165:7)
    at flush (./node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/asap.js:88:5)
```

**Comment by salztorte** [comment]
I'm not sure that this is a bug, because i see no use case for an empty export. 

If you dont want export something write no export.

**Comment by ochafik** [comment]
@salztorte There's no use case indeed, AFAICT! Yet, a compiler should generally not crash upon a syntactically valid input (or even invalid), it should emit an error instead (or in this case, just ignore the empty export).

**Comment by Rich-Harris** [comment]
There's a PR for this already – https://github.com/rollup/rollup/pull/498 – so I'll close this. I haven't had any time to work on this project recently but it'll get released after the next round of fixes

**Comment by ochafik** [comment]
Thanks!
