### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by janosh** [rollup/rollup#5084]
### Rollup Version

3.27.1

### Operating System (or Browser)

macOS

### Link To Reproduction

https://stackblitz.com/edit/rollup-repro-ughg9c?file=package.json

### Expected Behaviour

`npm run build` succeeds.

### Actual Behaviour

Lazy computing decoded mappings in https://github.com/rollup/rollup/pull/5075 seems to cause undefined `mappings` at `vite` build time in SvelteKit.

https://github.com/janosh/elementari/actions/runs/5754572660/job/15600143441#step:6:18
```
vite v4.4.8 building SSR bundle for production...
transforming...
✓ 5 modules transformed.
✓ built in 556ms
Cannot read properties of undefined (reading 'indexOf')
error during build:
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at indexOf (file:///home/runner/work/elementari/elementari/node_modules/rollup/dist/es/shared/node-entry.js:91:26)
    at decode (file:///home/runner/work/elementari/elementari/node_modules/rollup/dist/es/shared/node-entry.js:54:22)
    at get mappings [as mappings] (file:///home/runner/work/elementari/elementari/node_modules/rollup/dist/es/shared/node-entry.js:13281:37)
    at decodedSourcemap (file:///home/runner/work/elementari/elementari/node_modules/rollup/dist/es/shared/node-entry.js:13254:13)
    at file:///home/runner/work/elementari/elementari/node_modules/rollup/dist/es/shared/node-entry.js:13997:104
    at Array.map (<anonymous>)
    at Module.setSource (file:///home/runner/work/elementari/elementari/node_modules/rollup/dist/es/shared/node-entry.js:13997:46)
    at ModuleLoader.addModuleSource (file:///home/runner/work/elementari/elementari/node_modules/rollup/dist/es/shared/node-entry.js:24523:[20](https://github.com/janosh/elementari/actions/runs/5754572660/job/15600143441#step:6:21))
```

**Comment by lukastaegert** [comment]
Unfortunately your `npm run build` does not run for me in your reproduction. There are several images missing, and when I remove the references I get other errors. Could have a look? In any case, that sounds rather serious, so I will try to re-release the previous version for now.
cc @thebanjomatic, maybe you have an idea how to handle this?

**Comment by thebanjomatic** [comment]
I'll take a look at this today.

**Comment by thebanjomatic** [comment]
@lukastaegert A fix for the above issue is in the linked PR: https://github.com/rollup/rollup/pull/5087
