### ISSUE TITLE
Alleged missing export only on rebuild in watch mode

### ISSUE THREAD

**Issue by CherryDT** [rollup/rollup#5141]
### Rollup Version

v3.29.2

### Operating System (or Browser)

Ubuntu 20.04 on WSL1

### Node Version (if applicable)

v18.17.1

### Link To Reproduction

https://github.com/CherryDT/rollup-bug-repro/

### Expected Behaviour

When the bundle is rebuilt upon changing a watched file, it should work as well as on the initial build.

### Actual Behaviour

A weird error is thrown (not on initial build, only on rebuilding when a watched file changed), complaining about a missing export which is not actually missing. It's not always the same export that rollup complains about - it's 90% of the time the same but sometimes some other export of the same module.

```
[!] RollupError: "fromMiliseconds" is not exported by "node_modules/@walletconnect/time/dist/cjs/index.js", imported by "node_modules/@walletconnect/relay-auth/dist/esm/api.js".
https://rollupjs.org/troubleshooting/#error-name-is-not-exported-by-module
node_modules/@walletconnect/relay-auth/dist/esm/api.js (3:9)
1: import * as ed25519 from "@stablelib/ed25519";
2: import { randomBytes } from "@stablelib/random";
3: import { fromMiliseconds } from "@walletconnect/time";
            ^
4: import { JWT_IRIDIUM_ALG, JWT_IRIDIUM_TYP, KEY_PAIR_SEED_LENGTH, } from "./constants";
5: import { decodeIss, decodeJWT, encodeData, encodeIss, encodeJWT, } from "./utils";
    at error (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:353:30)
    at Module.error (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:15232:16)
    at Module.traceVariable (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:15662:29)
    at ModuleScope.findVariable (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:14109:39)
    at FunctionScope.findVariable (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:8625:38)
    at Identifier.bind (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:9818:40)
    at CallExpression.bind (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:7405:23)
    at CallExpression.bind (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:11384:15)
    at AssignmentPattern.bind (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:7405:23)
    at FunctionDeclaration.bind (/mnt/c/Users/david/proj/rollup-issue-repro/node_modules/rollup/dist/shared/rollup.js:7401:28)
```

You can check the [repro repo](https://github.com/CherryDT/rollup-bug-repro/) here to see it happening live.

While debugging this, I patched the code to output the `searchedNamesAndModules` map in the two cases (working and not working), and I noticed these differences, not sure if this means anything:

![image](https://github.com/rollup/rollup/assets/6010463/1bcdf899-fecd-4eb4-a828-fe2c5a739884)
![image](https://github.com/rollup/rollup/assets/6010463/1fc7cc4f-9ca7-4611-a2b2-a8b41ea709d5)
![image](https://github.com/rollup/rollup/assets/6010463/e056df9c-370c-4408-be99-5332c10bf299)

**Comment by CherryDT** [comment]
This is causing me a lot of troubles during development because it means I have to do a full rebuild on every change, which takes much longer than what normally is done in watch mode.

Was anyone of you able to take a look at this? If there is no actual fix yet, maybe there is some workaround? Is there something I can change on my end to avoid this problem? Thank you!

**Comment by TrickyPi** [comment]
One workaround: write a plugin to resolve `@walletconnect/time` to ESM files, like the following code.
```js
import path from "node:path";
......
    plugins:[
        ...,
        {
          resolveId(source) {
            if (source.endsWith("@walletconnect/time")) {
              return path.resolve(
                "node_modules/@walletconnect/time/dist/esm/index.js"
              );
            }
          },
       },
    ]
......
```
