### ISSUE TITLE
Rollup and prefixed NPM packages

### ISSUE THREAD

**Issue by caccialdo** [rollup/rollup#523]
Hi,

When trying to use rollup on an app that requires a package with the format `@org/foo` (with both `main` and `jsnext:main` props set), I am getting the following output:

```
Treating '@org/foo' as external dependency
Error: Cannot find module '@org/foo' from '/Users/me/git/my-repo'
    at /Users/me/git/my-repo/node_modules/resolve/lib/async.js:46:17
    at process (/Users/me/git/my-repo/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/me/git/my-repo/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/me/git/my-repo/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/me/git/my-repo/node_modules/resolve/lib/async.js:92:31)
    at /Users/me/git/my-repo/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Any idea why?

**Comment by TrySound** [comment]
@caccialdo Move this issue into https://github.com/rollup/rollup-plugin-node-resolve repo please.

**Comment by caccialdo** [comment]
Done https://github.com/rollup/rollup-plugin-node-resolve/issues/25 :+1:
