### ISSUE TITLE
rollup error [commonjs--resolver] Identifier has already been declared

### ISSUE THREAD

**Issue by ssaprank** [rollup/rollup#5306]
### Rollup Version

4.5.1

### Operating System (or Browser)

MacOS Monterey 12.3

### Node Version (if applicable)

18.15.0

### Link To Reproduction

https://rollupjs.org/repl/?version=4.5.1&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmh0dHBzJTNBJTJGJTJGcm9sbHVwanMub3JnJTJGcmVwbCUyRiUzRnZlcnNpb24lM0Q0LjUuMSUyNnNoYXJlYWJsZSUzREpUZENKVEl5WlhoaGJYQnNaU1V5TWlVelFXNTFiR3dsTWtNbE1qSnRiMlIxYkdWekpUSXlKVE5CSlRWQ0pUZENKVEl5WTI5a1pTVXlNaVV6UVNVeU1pVXlSaVV5UmlVeU1GUlNSVVV0VTBoQlMwbE9SeVUxUTI1cGJYQnZjblFsTWpBbE4wSWxNakJqZFdKbEpUSXdKVGRFSlRJd1puSnZiU1V5TUNjdUpUSkdiV0YwYUhNdWFuTW5KVE5DSlRWRGJpVTFRMjVqYjI1emIyeGxMbXh2WnloamRXSmxLRFVwS1NVelFpVXlNQ1V5UmlVeVJpVXlNREV5TlNVeU1pVXlReVV5TW1selJXNTBjbmtsTWpJbE0wRjBjblZsSlRKREpUSXlibUZ0WlNVeU1pVXpRU1V5TW0xaGFXNHVhbk1sTWpJbE4wUWxOVVFsTWtNbE1qSnZjSFJwYjI1ekpUSXlKVE5CSlRkQ0pUSXliM1YwY0hWMEpUSXlKVE5CSlRkQ0pUSXlabTl5YldGMEpUSXlKVE5CSlRJeVpYTWxNaklsTjBRbE1rTWxNakowY21WbGMyaGhhMlVsTWpJbE0wRjBjblZsSlRkRUpUZEUlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==

### Expected Behaviour

Rollup builds the bundles

### Actual Behaviour

```bash
yarn run v1.22.19
$ NODE_OPTIONS=--max_old_space_size=4096 vite build --mode pipeline --config vite-pipeline.config.ts
vite v5.0.10 building for pipeline...
✓ 14993 modules transformed.
[commonjs--resolver] Identifier "l2" has already been declared
file: /Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/azure-maps-control/dist/atlas-esm.min.js:7435:42
error during build:
RollupError: Identifier "l2" has already been declared
    at error (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Module.error (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:12737:16)
    at BlockScope.addDeclaration (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:7520:32)
    at Identifier.declare (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:7188:39)
    at VariableDeclarator.declareDeclarator (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:10178:17)
    at VariableDeclaration.initialise (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:11843:24)
    at new NodeBase (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:4607:14)
    at new VariableDeclaration (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:11815:1)
    at BlockStatement.parseNode (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:4718:27)
    at new NodeBase (file:///Users/ssaprank/Documents/AlixPartners/lineage/AP.Lineage.UI/node_modules/rollup/dist/es/shared/node-entry.js:4606:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ssaprank@Stanislavs-MacBook-Pro review % uname -a
Darwin Stanislavs-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
ssaprank@Stanislavs-MacBook-Pro review % node -v
v18.15.0
ssaprank@Stanislavs-MacBook-Pro review % nvm use 20
N/A: version "20 -> N/A" is not yet installed.

You need to run "nvm install 20" to install it before using it.
ssaprank@Stanislavs-MacBook-Pro review % nvm install 20
Downloading and installing node v20.10.0...
Downloading https://nodejs.org/dist/v20.10.0/node-v20.10.0-darwin-arm64.tar.xz...
############################################################################################################## 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v20.10.0 (npm v10.2.3)
```

Similar to https://github.com/rollup/rollup/issues/5259 but the new rollup version didn't fix it for me

**Comment by ssaprank** [comment]
UPD: with rollup 4.9.1 there is no such error.
if I try 

```json
  "overrides": {
    "vite": {
      "rollup": "^4.9.1"
    }
  },
```

the build is green

**Comment by lukastaegert** [comment]
That means the issue can be closed?

**Comment by ssaprank** [comment]
@lukastaegert I guess so. Vite is using 4.5.1 version of rollout, so I have to override to make it work. But I guess, it's a problem of vite, not rolloup.
