### ISSUE TITLE
Crash on msys2 environment

### ISSUE THREAD

**Issue by thewh1teagle** [rollup/rollup#5333]
### Rollup Version

v4.9.4

### Operating System (or Browser)

Windows

### Node Version (if applicable)

v18.17.1

### Link To Reproduction

https://www.msys2.org/

### Expected Behaviour

It should run normally

### Actual Behaviour

When I run the command `rollup` in `msys2` environment in `ucrt64` terminal
I get the following error
```console
$ npx rollup
thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\napi-sys-2.3.0\src\functions.rs:7:3:
Must load N-API bindings
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
And as a result, every library which depends on rollup receive it too.

**Comment by thewh1teagle** [comment]
Still happen
```console
User@Desktop UCRT64 ~/
$ npx rollup
Need to install the following packages:
  rollup@4.9.5
Ok to proceed? (y) y
thread '<unnamed>' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\napi-sys-2.3.0\src\functions.rs:7:3:
Must load N-API bindings
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kreijstal** [comment]
I have the same issue
