### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by danush-basky** [rollup/rollup#5433]
Hey there! If you need help or tech support then this is not the place to ask. Please head to the [Rollup Discord](https://is.gd/rollup_chat) instead or post a question to https://stackoverflow.com/questions/tagged/rollupjs.

If you arrived here because you think Rollup's documentation is unclear, insufficient or wrong, please consider creating an issue for the documentation instead.

Getting the below error on npm run build while building docker image. Able to build successfully on host machine. Using Vite.

RangeError: Maximum call stack size exceeded
    at convertNodeList (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:2064:34)
    at classBody (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:1142:22)
    at convertNode (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:2057:12)
    at importDefaultSpecifier (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:1484:23)
    at convertNode (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:2057:12)
    at convertNodeList (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:2064:34)
    at classBody (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:1142:22)
    at convertNode (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:2057:12)
    at importDefaultSpecifier (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:1484:23)
    at convertNode (file:///app/node_modules/rollup/dist/es/shared/parseAst.js:2057:12)
building at STEP "RUN npm run build": while running runtime: exit status 1

**Comment by arturog** [comment]
I fixed this by downgrading `@rollup/rollup-linux-x64-gnu` to version `4.17.1`.

**Comment by lukastaegert** [comment]
Sorry I missed this one. If this problem still persists, any kind of reproduction would be more than welcome. This looks like it is caused by a module that cannot be parsed correctly.

**Comment by arturog** [comment]
Impossible for me to tell, sorry.  Only guidance I can provide is the following:
- Failure running `vitest` - vitest/1.1.3 linux-x64 node-v20.12.1
- Linux with clang
- npm version 10.5.0
- Project uses typescript - tsc Version 5.3.3

**Comment by lukastaegert** [comment]
That does not help at all, unfortunately. What we need is the source code of a module that does not parse. If your sources are JavaScript, you could paste sources as "main.js" in the [REPL](https://rollupjs.org/repl) and see if the error triggers there. This can be done file-by-file, no need for imported files to be present.
To limit your search, you could also add a simple plugin that logs whenever we start with a module and  whenever parsing has happened:

```
{
  name: 'log-modules',
  transform(_, id) {
    console.log('Before parsing of', id);
  },
  moduleParsed({id}) {
    console.log('Parsed', id);
  }
}
```

then you only need to check the modules where 'Before parsing of' is not matched by a 'Parsed' log.

**Comment by bdelacroix** [comment]
Hi, I actually encounter the same issue in my Gitlab pipeline when running unit tests using Vitest. Downgrading `@rollup/rollup-linux-x64-gnu` did not seem to fix the issue in my case.

Logging `transform` plugin suggests the `RangeError` exception is thrown before `my-project/node_modules/vitest/node_modules/vite/dist/client/env.mjs` process and its associated code:

```js
const context = (() => {
    if (typeof globalThis !== 'undefined') {
        return globalThis;
    }
    else if (typeof self !== 'undefined') {
        return self;
    }
    else if (typeof window !== 'undefined') {
        return window;
    }
    else {
        return Function('return this')();
    }
})();
// assign defines
const defines = __DEFINES__;
Object.keys(defines).forEach((key) => {
    const segments = key.split('.');
    let target = context;
    for (let i = 0; i < segments.length; i++) {
        const segment = segments[i];
        if (i === segments.length - 1) {
            target[segment] = defines[key];
        }
        else {
            target = target[segment] || (target[segment] = {});
        }
    }
});
```

It might be relevant to know that `moduleParsed` hook is not called by Vite as mentioned in its [documentation](https://vitejs.dev/guide/api-plugin.html#universal-hooks).

It is hard to give you reproducible steps because this issue seems to be flaky in my pipeline. This issue might not be related to Rollup internals, but it appears with Vite 4-5 migration introducing Rollup 4 upgrade.

### System info
```
System:
  Platform: linux
  Distro: Debian GNU/Linux
  CODE: bullseye
  Version: 11
  Kernel: 4.19.0-26-amd64
  Build: n/a
  Architecture: x64
  
Binaries:
  node: 18.20.2
  yarn: 1.22.19
  
Packages:
  vite: 5.2.10
  vitest: 1.6.0
  rollup: 4.18.0
  typescript: 5.4.2
```

Thanks to anyone who will take time to read this.

**Comment by lukastaegert** [comment]
Unfortunately that does not trigger any issue in the [REPL](https://rollupjs.org/repl/) so there might be more to it. It could of course be that there is some plugin transforming the module.
So if you followed the steps I highlighted above https://github.com/rollup/rollup/issues/5433#issuecomment-2101958348, possibly extended with `enforce: "post"` so that it also happens after Vite's build plugins and are sure there is only one module in question, then you could also print the transformed code of the module in the transform hook. If you paste that into the REPL, that should then cause the same error there:

```
{
  name: 'log-modules',
  enforce: 'post',
  transform(code id) {
    console.log('Before parsing of', id);
    if (id === "id-of-broken-module") {
      console.log(code);
    }
  },
  moduleParsed({id}) {
    console.log('Parsed', id);
  }
}
```

Something else that might prove helpful could be the full stack trace of the error. On the other hand, that might not be easy for maximum call stack errors where the stack trace is by definition very long. In the original issue, the stack trace is truncated to show the most irrelevant part. What we are interested is the bottom part of the stack trace, the calls that brought Rollup into a loop. As you can see, the function names correspond to AST node names, however at some point it became nonsense. If we get a stack trace that includes `convertProgram` and what comes above it, we might reconstruct the code from that perspective.

**Comment by bdelacroix** [comment]
Thanks to https://github.com/rollup/rollup/commit/14c966257f084b5431113961e2fe55f052cecc24 with internal `console.trace()`, I can provide a bit more context about the AST parsing error: 

```
$ make run-frontend-apps-unit-tests
DEBUG=vite-node:* VITE_NODE_DEBUG_DUMP=load VITE_NODE_DEBUG_RUNNER=true yarn --cwd ./frontend-apps test:unit
yarn run v1.22.22
$ cd tests/ && vitest
[vite-node] [debug] load modules from /builds/espace-client/eev2/frontend-apps/tests/.vite-node/dump
2024-08-07T12:30:47.949Z vite-node:client:native /builds/espace-client/eev2/frontend-apps/node_modules/@vitest/ui/dist/reporter.js
 RUN  v2.0.5 /builds/espace-client/eev2/frontend-apps/tests
2024-08-07T12:30:48.164Z vite-node:server:request /@vite/env
Trace
    at convertNode (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:966:17)
    at start (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:1024:23)
    at convertNode (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:969:12)
    at start (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:1832:42)
    at convertNode (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:969:12)
    at convertProgram (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:960:48)
    at parseAstAsync (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:2150:20)
    at async ssrTransformScript (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:49846:15)
    at async ViteNodeServer._transformRequest (file:///builds/espace-client/eev2/frontend-apps/node_modules/vite-node/dist/server.mjs:521:18)
    at async ViteNodeServer._fetchModule (file:///builds/espace-client/eev2/frontend-apps/node_modules/vite-node/dist/server.mjs:486:17)
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Unknown node type: 78
```

The AST parsing requested by `vite-node` seems to fail during `@vite/env` process. Unfortunately, I don't master Rollup internal behaviours enough to apprehend the meaning of a node type `78` and why it appears "randomly". As I said in my previous comment, the issue might not be directly related to Rollup, but rather on the way Vitest is parsing its internal `@vite/env`.

Thanks, have a good day!

**Comment by bdelacroix** [comment]
Thanks to https://github.com/rollup/rollup/commit/14c966257f084b5431113961e2fe55f052cecc24 with internal `console.trace()`, I can provide a bit more context about the AST parsing error: 

```
$ make run-frontend-apps-unit-tests
DEBUG=vite-node:* VITE_NODE_DEBUG_DUMP=load VITE_NODE_DEBUG_RUNNER=true yarn --cwd ./frontend-apps test:unit
yarn run v1.22.22
$ cd tests/ && vitest
[vite-node] [debug] load modules from /builds/espace-client/eev2/frontend-apps/tests/.vite-node/dump
2024-08-07T12:30:47.949Z vite-node:client:native /builds/espace-client/eev2/frontend-apps/node_modules/@vitest/ui/dist/reporter.js
 RUN  v2.0.5 /builds/espace-client/eev2/frontend-apps/tests
2024-08-07T12:30:48.164Z vite-node:server:request /@vite/env
Trace
    at convertNode (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:966:17)
    at start (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:1024:23)
    at convertNode (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:969:12)
    at start (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:1832:42)
    at convertNode (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:969:12)
    at convertProgram (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:960:48)
    at parseAstAsync (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/rollup/dist/es/shared/parseAst.js:2150:20)
    at async ssrTransformScript (file:///builds/espace-client/eev2/frontend-apps/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:49846:15)
    at async ViteNodeServer._transformRequest (file:///builds/espace-client/eev2/frontend-apps/node_modules/vite-node/dist/server.mjs:521:18)
    at async ViteNodeServer._fetchModule (file:///builds/espace-client/eev2/frontend-apps/node_modules/vite-node/dist/server.mjs:486:17)
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Unknown node type: 78
```

The AST parsing requested by `vite-node` seems to fail during `@vite/env` process. Unfortunately, I don't master Rollup internal behaviours enough to apprehend the meaning of a node type `78` and why it appears "randomly". As I said in my previous comment, the issue might not be directly related to Rollup, but rather on the way Vitest is parsing its internal `@vite/env`.

Thanks, have a good day!

**Comment by lukastaegert** [comment]
> Unknown node type: 78

That can happen when your rollup version and the version of the binaries, e.g. `@rollup/rollup-linux-x64-gnu`, do not match. Those always need to be perfectly synced. The background is that there is a code generator that generates both Rust and JavaScript code for Rollup which assigns numbers to AST node types, but if a new node type is added it can happen that the two parts no longer work well together.

The original error was `Maximum call stack size exceeded`, that is the one that really worries me.

**Comment by superchangme** [comment]
i have the same problem,my versions is @rollup/wasm-node@4.28.1

**Comment by superchangme** [comment]
✓ 6683 modules transformed.
x Build failed in 1m 12s
error during build:
[vite:build-import-analysis] Maximum call stack size exceeded
at String.replace ()
at Object.generateBundle (file:///E:/rd-process-dashboard-web/web/node_modules/vite/dist/node/chunks/dep-C6uTJdX2.js:65233:41)
at file:///E:/rd-process-dashboard-web/web/node_modules/rollup/dist/es/shared/node-entry.js:20812:40

**Comment by superchangme** [comment]
> i have the same problem,my versions is @rollup/wasm-node@4.28.1

✓ 6683 modules transformed.
x Build failed in 1m 12s
error during build:
[vite:build-import-analysis] Maximum call stack size exceeded
at String.replace ()
at Object.generateBundle (file:///E:/rd-process-dashboard-web/web/node_modules/vite/dist/node/chunks/dep-C6uTJdX2.js:65233:41)
at file:///E:/rd-process-dashboard-web/web/node_modules/rollup/dist/es/shared/node-entry.js:20812:40
