### ISSUE TITLE
Upgrade from vite 4 to vite 5 crashes in rollup with maximum call stack exceeded

### ISSUE THREAD

**Issue by benasher44** [rollup/rollup#5499]
### Rollup Version

4.17.0

### Operating System (or Browser)

macOS

### Node Version (if applicable)

20.11.1

### Link To Reproduction

https://github.com/benasher44/vite-stack-exceeded-repro

run npm install && npm run build

### Expected Behaviour

vite 5 production build works

### Actual Behaviour

We get this crash

```
vite v5.2.10 building for production...
✓ 133 modules transformed.
x Build failed in 405ms
error during build:
RangeError: Maximum call stack size exceeded
    at ParameterVariable.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:7219:34)
    at Identifier.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:6985:53)
    at ParameterVariable.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:7224:27)
    at Identifier.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:6985:53)
    at ParameterVariable.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:7224:27)
    at Identifier.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:6985:53)
    at ParameterVariable.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:7224:27)
    at Identifier.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:6985:53)
    at ParameterVariable.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:7224:27)
    at Identifier.hasEffectsOnInteractionAtPath (file:///Users/basher/code/stack-exceeded-repro/node_modules/rollup/dist/es/shared/node-entry.js:6985:53)
```

~~I'd love some pointers on how to determine what part of our code might have triggered this~~ figured out a repro!

**Comment by liuly0322** [comment]
Thanks for the repro! I get a [REPL](https://rollupjs.org/repl/?version=4.17.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwUGFyc2VyKG9wdGlvbnMpJTIwJTdCJTVDbiUyMCUyMGlmJTIwKCF0aGlzKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBuZXclMjBQYXJzZXIob3B0aW9ucyklM0IlNUNuJTIwJTIwJTdEJTVDbiU1Q24lMjAlMjBpZiUyMChvcHRpb25zLngpJTIwJTdCJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMDAlNUNuJTIwJTIwJTdEJTVDbiU3RCU1Q24lNUNuY29uc3QlMjBwYXJzZXIlMjAlM0QlMjBuZXclMjBQYXJzZXIoJTdCJTdEKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJTdE).

Related rollup code (`NewExpression.ts` and `TaggedTemplateExpression.ts`):

```typescript
hasEffects(context: HasEffectsContext): boolean {
	try {
		for (const argument of this.arguments) {
			if (argument.hasEffects(context)) return true;
		}
		if (this.annotationPure) {
			return false;
		}
		return (
			this.callee.hasEffects(context) ||
			this.callee.hasEffectsOnInteractionAtPath(EMPTY_PATH, this.interaction, context)
		);
	} finally {
		if (!this.deoptimized) this.applyDeoptimizations();
	}
}
```
