### ISSUE TITLE
Packaging vue components, it seems that typescript code is not recognized

### ISSUE THREAD

**Issue by Jevin0** [rollup/rollup#5540]
### Rollup Version

latest

### Operating System (or Browser)

-

### Link To Reproduction

https://github.com/Jevin0/rollup-build-demo

### Expected Behaviour

Normally, a directory `dist/component/button` should be generated.

### Actual Behaviour

Error [RollupError]: Expected ',', got '{'
    at getRollupError (file:///C:/Users/jevin/Desktop/demo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    ... 4 lines matching cause stack trace ...
    at async ModuleLoader.addModuleSource (file:///C:/Users/jevin/Desktop/demo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:18892:13) {
  cause: Error [RollupError]: Expected ',', got '{'
      at getRollupError (file:///C:/Users/jevin/Desktop/demo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
      at ParseError.initialise (file:///C:/Users/jevin/Desktop/demo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:11332:28)
      at convertNode (file:///C:/Users/jevin/Desktop/demo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:13082:10)
      at convertProgram (file:///C:/Users/jevin/Desktop/demo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:12399:12)
      at Module.setSource (file:///C:/Users/jevin/Desktop/demo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:14246:24)
      at async ModuleLoader.addModuleSource (file:///C:/Users/jevin/Desktop/demo/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:18892:13) {
    code: 'PARSE_ERROR',
    pos: 70
  },
  code: 'PARSE_ERROR',
  id: 'C:\\Users\\jevin\\Desktop\\demo\\component\\button\\button.vue?vue&type=script&setup=true&lang.ts',
  pos: 70,
  loc: {
    column: 12,
    file: 'C:\\Users\\jevin\\Desktop\\demo\\component\\button\\button.vue?vue&type=script&setup=true&lang.ts',
    line: 2
  },
  frame: "1: import { defineComponent as _defineComponent } from 'vue'\n" +
    "2: import type {ButtonProps} from './types'\r\n" +
    '               ^',
  watchFiles: [
    'C:\\Users\\jevin\\Desktop\\demo\\index.ts',
    'C:\\Users\\jevin\\Desktop\\demo\\component\\button\\index.ts',
    'C:\\Users\\jevin\\Desktop\\demo\\component\\button\\button.vue'
  ],
  [Symbol(augmented)]: true
} error
file:///C:/Users/jevin/Desktop/demo/build.js:161
  return Promise.all(options.map((option) => bundle.write(option)));
                                                    ^

TypeError: Cannot read properties of undefined (reading 'write')
    at file:///C:/Users/jevin/Desktop/demo/build.js:161:53
    at Array.map (<anonymous>)
    at writeBundles (file:///C:/Users/jevin/Desktop/demo/build.js:161:30)
    at runBuild (file:///C:/Users/jevin/Desktop/demo/build.js:48:3)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by sunnylost** [comment]
Add `.vue` in babel config.

```ts
 babel({
    extensions: [ ..., ".vue"],
  }),
```
