### ISSUE TITLE
Cannot find module @rollup/rollup-win32-x64-msvc (rollup 4.18.1)

### ISSUE THREAD

**Issue by lorand-horvath** [rollup/rollup#5571]
### Rollup Version

4.18.1

### Operating System (or Browser)

Win x64

### Node Version (if applicable)

18.20.4

### Link To Reproduction

http://localhost:5173

### Expected Behaviour

`npm run dev` in latest vite should run

### Actual Behaviour

Since updating to rollup 4.18.1 (dependency of latest vite) this error occurs on `npm run dev`. I have checked and `@rollup/rollup-win32-x64-msvc.node` does exist under node_modules. Also tried to delete node_modules and package-lock.json and npm install, but the issue persists.
If I downgrade to rollup 4.18.0 everything works without any issues. Nothing else has changed.

```
d:\app\node_modules\rollup\dist\native.js:59
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (d:\app\node_modules\rollup\dist\native.js:59:9)
    at Object.<anonymous> (d:\app\node_modules\rollup\dist\native.js:68:76)
    ... 2 lines matching cause stack trace ...
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24) {
  [cause]: Error: The specified procedure could not be found.
  \\?\d:\app\node_modules\@rollup\rollup-win32-x64-msvc\rollup.win32-x64-msvc.node
      at Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
      at Module.load (node:internal/modules/cjs/loader:1203:32)
      at Module._load (node:internal/modules/cjs/loader:1019:12)
      at Module.require (node:internal/modules/cjs/loader:1231:19)
      at require (node:internal/modules/helpers:177:18)
      at requireWithFriendlyError (d:\app\node_modules\rollup\dist\native.js:41:10)
      at Object.<anonymous> (d:\app\node_modules\rollup\dist\native.js:68:76)
      at Module._compile (node:internal/modules/cjs/loader:1364:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
      at Module.load (node:internal/modules/cjs/loader:1203:32) {
    code: 'ERR_DLOPEN_FAILED'
  }
}
```

**Comment by lorand-horvath** [comment]
@lukastaegert I have also tried updating to the latest available Visual C++ Redistributable 14.40.33810 from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 but the issue persists.

**Comment by lorand-horvath** [comment]
Found a workaround: use `@rollup/wasm-node` instead of `rollup` by overriding it in package.json
```json
  "overrides": {
    "vite": {
      "rollup": "npm:@rollup/wasm-node"
    }
  }
```

**Comment by broomfn** [comment]
+1

**Comment by drwillems** [comment]
I have to comment here as I was stuck on the same error and fixed it in a different way. My error because of Windows Subsystem for Linux (WSL), the NPM config was set to OS Linux and a separate NPM prefix.
Run to see if your config has the same settings `npm config list`
os = "linux"
prefix = "C:\\home\\[user]\\npm-global"

I fixed it by running: `npm config delete os` to remove OS linux and `npm config set prefix "C:\Users\[user]\AppData\Roaming\npm"` to revert back to default NPM.

**Comment by edwinzap** [comment]
I have the same error.
Steps to reproduce:
1) npm create vuestic@latestnpm
2) npm install
3) npm run dev

Error: Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

I tried "Please try `npm i` again after removing both package-lock.json and node_modules directory.", does not change anything.

**Comment by HectorGitt** [comment]
> I have to comment here as I was stuck on the same error and fixed it in a different way. My error because of Windows Subsystem for Linux (WSL), the NPM config was set to OS Linux and a separate NPM prefix. Run to see if your config has the same settings `npm config list` os = "linux" prefix = "C:\home\[user]\npm-global"
> 
> I fixed it by running: `npm config delete os` to remove OS linux and `npm config set prefix "C:\Users\[user]\AppData\Roaming\npm"` to revert back to default NPM.

is the dir the same if you use nvm
