### ISSUE TITLE
Error [RollupError]: Expected ';', '}' or <eof>

### ISSUE THREAD

**Issue by yxw007** [rollup/rollup#5635]
### Rollup Version

4.21.1

### Operating System (or Browser)

win11

### Node Version (if applicable)

22.3.0

### Link To Reproduction

https://github.com/yxw007/translate

### Expected Behaviour

Can be compiled and passed

### Actual Behaviour

```bash
$ pnpm build

> translate@0.0.1 build D:\Work\Projects\translate
> pnpm clean && tsx script/build.ts


> translate@0.0.1 clean D:\Work\Projects\translate
> rm -rf dist

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error [RollupError]: Expected ';', '}' or <eof>
    at getRollupError (file:///D:/Work/Projects/translate/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/
    ... 4 lines matching cause stack trace ...
    at ModuleLoader.addModuleSource (D:\Work\Projects\translate\node_modules\.pnpm\rollup@4.21.2\node_modules\rollup\dist\es\s
  cause: Error [RollupError]: Expected ';', '}' or <eof>
      at getRollupError (file:///D:/Work/Projects/translate/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/share
      at ParseError.initialise (D:\Work\Projects\translate\node_modules\.pnpm\rollup@4.21.2\node_modules\rollup\dist\es\shared
      at convertNode (D:\Work\Projects\translate\node_modules\.pnpm\rollup@4.21.2\node_modules\rollup\dist\es\shared\node-entr
      at convertProgram (D:\Work\Projects\translate\node_modules\.pnpm\rollup@4.21.2\node_modules\rollup\dist\es\shared\node-e
      at Module.setSource (D:\Work\Projects\translate\node_modules\.pnpm\rollup@4.21.2\node_modules\rollup\dist\es\shared\node
      at ModuleLoader.addModuleSource (D:\Work\Projects\translate\node_modules\.pnpm\rollup@4.21.2\node_modules\rollup\dist\es
    code: 'PARSE_ERROR',
    pos: 10
  },
  code: 'PARSE_ERROR',
  id: 'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-t
  pos: 10,
  loc: {
    column: 8,
    file: 'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\clie
    line: 2
  },
  frame: '1: {\n' +
    '2:   "name": "@aws-sdk/client-translate",\n' +
    '           ^\n' +
    '3:   "description": "AWS SDK for JavaScript Translate Client for Node.js, Browser and React Native",\n' +
    '4:   "version": "3.637.0",',
  watchFiles: [
    'D:\\Work\\Projects\\translate\\src\\index.ts',
    'D:\\Work\\Projects\\translate\\src\\engines\\index.ts',
    'D:\\Work\\Projects\\translate\\src\\language\\index.ts',
    'D:\\Work\\Projects\\translate\\src\\utils\\index.ts',
    'D:\\Work\\Projects\\translate\\src\\engines\\google.ts',
    'D:\\Work\\Projects\\translate\\src\\engines\\azure.ts',
    'D:\\Work\\Projects\\translate\\src\\engines\\amazon.ts',
    'D:\\Work\\Projects\\translate\\src\\engines\\baidu.ts',
    'D:\\Work\\Projects\\translate\\src\\utils\\cache.ts',
    'D:\\Work\\Projects\\translate\\src\\utils\\logger.ts',
    'D:\\Work\\Projects\\translate\\src\\utils\\path.ts',
    'D:\\Work\\Projects\\translate\\src\\utils\\check.ts',
    'D:\\Work\\Projects\\translate\\src\\utils\\typescript.ts',
    'D:\\Work\\Projects\\translate\\src\\utils\\utils.ts',
    'D:\\Work\\Projects\\translate\\src\\language\\iso.ts',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\crypto-js@4.2.0\\node_modules\\crypto-js\\md5.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\crypto-js@4.2.0\\node_modules\\crypto-js\\core.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+core@2.4.0\\node_modules\\@smithy\\core\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+core@2.4.0\\node_modules\\@smithy\\core\\dist-es\\normalizePr
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+core@2.4.0\\node_modules\\@smithy\\core\\dist-es\\getSmithyCo
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+core@2.4.0\\node_modules\\@smithy\\core\\dist-es\\pagination\
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+core@2.4.0\\node_modules\\@smithy\\core\\dist-es\\protocols\\
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+middleware-endpoint@3.1.0\\node_modules\\@smithy\\middleware-
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+config-resolver@3.0.5\\node_modules\\@smithy\\config-resolver
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+middleware-retry@3.0.15\\node_modules\\@smithy\\middleware-re
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+middleware-content-length@3.0.5\\node_modules\\@smithy\\middl
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+smithy-client@3.2.0\\node_modules\\@smithy\\smithy-client\\di
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-logger@3.609.0\\node_modules\\@aws-sdk\\middlewar
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-logger@3.609.0\\node_modules\\@aws-sdk\\middlewar
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-logger@3.609.0\\node_modules\\@aws-sdk\\middlewar
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-logger@3.609.0\\node_modules\\@aws-sdk\\middlewar
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-logger@3.609.0\\node_modules\\@aws-sdk\\middlewar
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-logger@3.609.0\\node_modules\\@aws-sdk\\middlewar
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-logger@3.609.0\\node_modules\\@aws-sdk\\middlewar
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\@aws-sdk\\middl@aws-sdk\\middnt\\dist-es\\index.js',
leware-user-agent\\dist-es\\index.js',                                                                         ist-es\\index.j
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\dist-es\\index.\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-trajs',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-es\\middleware-    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\@aws-sdk\\mit-es\\runtimeConfig.browser.js',                                                                   es\\middleware-
ddleware-user-agent\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\des\\util-identiist-es\\indeg\\index.js',
x.js',                                                                                                         sdk\\client-tra
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\@aws-sdk\\\dist-es\\runtimeConfig.browser.js',
middleware-user-agent\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\dist-es\\ingning\\index.js',
dex.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\@aws-sdk\te\\dist-es\\runtimeConfig.browser.js',
\middleware-user-agent\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\dist-es\\i-signing\\index.js',
ndex.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\@aws-sdslate\\dist-es\\runtimeConfig.browser.js',
k\\middleware-user-agent\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\dist-es\ttp-signing\\index.js',
\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\@aws-translate\\dist-es\\runtimeConfig.browser.js',
-sdk\\middleware-user-agent\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\dist-are-http-signing\\index.js',
es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\@awient-translate\\dist-es\\runtimeConfig.browser.js',
s-sdk\\middleware-user-agent\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\distdleware-http-signing\\index.js',
-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\@client-translate\\dist-es\\runtimeConfig.browser.js',
aws-sdk\\middleware-user-agent\\dist-es\\index.js',                                                           -
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\diiddleware-http-signing\\index.js',
st-es\\index.js',                                                                                             -
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\\k\\client-translate\\dist-es\\runtimeConfig.browser.js',                                                     -
@aws-sdk\\middleware-user-agent\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\d\\middleware-http-signing\\index.js',                                                                        -
ist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modules\k\\client-translate\\dist-es\\runtimeConfig.browser.js',
\@aws-sdk\\middleware-user-agent\\dist-es\\index.js',                                                       st
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\\\\middleware-http-signing\\index.js',
dist-es\\index.js',                                                                                         st
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@a    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+middleware-user-agent@3.637.0\\node_modulessdk\\client-translate\\dist-es\\runtimeConfig.browser.js',                                                 st
\\@aws-sdk\\middleware-user-agent\\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+core@3.635.0\\node_modules\\@aws-sdk\\core\es\\middleware-http-signing\\index.js',                                                                    ws
\dist-es\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@anslate\\dist-es\\runtimeConfig.browser.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+core@2.4.0\\node_modules\\@smithy\\core\\dist-es\\middleware-http-signing\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+core@2.4.0\\node_modules\\@smithy\\core\\dist-es\\middleware-http-auth-scheme\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@smithy+core@2.4.0\\node_modules\\@smithy\\core\\dist-es\\util-identity-and-auth\\index.js',
    'D:\\Work\\Projects\\translate\\node_modules\\.pnpm\\@aws-sdk+client-translate@3.637.0\\node_modules\\@aws-sdk\\client-translate\\package.json'
  ],
  [Symbol(augmented)]: true
}

Node.js v22.3.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by sunnylost** [comment]
I think the issue is that `@aws-sdk/client-translate` imports its `package.json`, and Rollup treats it as an ES module, even though it's not. You can use `@rollup/plugin-json` to handle JSON files properly.

```ts
import json from "@rollup/plugin-json"

export default defineConfig([
  {
    // ...
    plugins: [json()]
  }
])
```

**Comment by yxw007** [comment]
> I think the issue is that `@aws-sdk/client-translate` imports its `package.json`, and Rollup treats it as an ES module, even though it's not. You can use `@rollup/plugin-json` to handle JSON files properly.
> 
> ```ts
> import json from "@rollup/plugin-json"
> 
> export default defineConfig([
>   {
>     // ...
>     plugins: [json()]
>   }
> ])
> ```
Thanks for rewriting the liberation method you provided, which has successfully solved my problem. I checked that @awd-sdk/client-translate already supports esm, so why do I need this @rollup/plugin-json plugin to process it?
![image](https://github.com/user-attachments/assets/0476f91a-bd44-43e6-84b9-b2421d329ece)

**Comment by sunnylost** [comment]
You can test this code without the JSON plugin:

```ts
import pkg from './package.json';
```

You'll notice that Rollup tries to parse it as a standard ES module but fails. `@aws-sdk/client-translate` includes something similar, so you need to install the JSON plugin to transform the JSON format into a ES module format.

**Comment by yxw007** [comment]
> You can test this code without the JSON plugin:
>
> ```ts
> import pkg from './package.json';
> ```
>
> You'll notice that Rollup tries to parse it as a standard ES module but fails. `@aws-sdk/client-translate` includes something similar, so you need to install the JSON plugin to transform the JSON format into a ES module format.

Thank you for your answer.

**Comment by tanishqmanuja** [comment]
I am getting same thing when unbuild is calling rollup internally.

```sh
❯ bun run build --verbose
$ unbuild --verbose
ℹ Automatically detected entries: src/index [esm] [cjs] [dts]                                                                                                                   11:18:27 AM
ℹ Building nice-logger                                                                                                                                                          11:18:27 AM   
ℹ Cleaning dist directory: ./dist                                                                                                                                               11:18:27 AM   

[11:18:30 AM]  ERROR  Error building C:/Users/tanishq/Projects/library/nice-logger: RollupError: Expected ';', '}' or <eof> in C:\Users\tanishq\Projects\library\nice-logger\node_modules\@sinclair\typebox\build\cjs\type\type\index.d.ts


 ERROR  Expected ';', '}' or <eof> in C:\Users\tanishq\Projects\library\nice-logger\node_modules\@sinclair\typebox\build\cjs\type\type\index.d.ts                                11:18:30 AM  

  at getRollupError (/C:/Users/tanishq/Projects/library/nice-logger/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
  at convertProgram (/C:/Users/tanishq/Projects/library/nice-logger/node_modules/rollup/dist/es/shared/parseAst.js:1084:26)
  at parseAst (/C:/Users/tanishq/Projects/library/nice-logger/node_modules/rollup/dist/es/shared/parseAst.js:2069:87)
  at tryParse (/C:/Users/tanishq/Projects/library/nice-logger/node_modules/@rollup/plugin-commonjs/dist/es/index.js:17:12)
  at analyzeTopLevelStatements (/C:/Users/tanishq/Projects/library/nice-logger/node_modules/@rollup/plugin-commonjs/dist/es/index.js:37:15)
  at Object.transformAndCheckExports (/C:/Users/tanishq/Projects/library/nice-logger/node_modules/@rollup/plugin-commonjs/dist/es/index.js:2113:68)
  at Object.transform (/C:/Users/tanishq/Projects/library/nice-logger/node_modules/@rollup/plugin-commonjs/dist/es/index.js:2317:41)
  at /C:/Users/tanishq/Projects/library/nice-logger/node_modules/rollup/dist/es/shared/node-entry.js:20874:40



 ERROR  Expected ';', '}' or <eof> in C:\Users\tanishq\Projects\library\nice-logger\node_modules\@sinclair\typebox\build\cjs\type\type\index.d.ts                                11:18:30 AM  

error: script "build" exited with code 1
```

I have to switch from unbuild to tsup + tsc due to this :(
https://github.com/tanishqmanuja/nice-logger/commit/f239682f555b9c0f2a8dd26dede7a4de2170931e
