### ISSUE TITLE
Cannot read properties of null (reading 'start')

### ISSUE THREAD

**Issue by Sceat** [rollup/rollup#5733]
### Rollup Version

v4.27.2

### Operating System (or Browser)

Mac M1 / Vercel

### Node Version (if applicable)

v23

### Link To Reproduction

https://github.com/aresrpg/aresrpg-dapp

### Expected Behaviour

`npm run build` should run correctly

Since this PR https://github.com/aresrpg/aresrpg-dapp/pull/165 which changes nothing concerning the bundling, it's impossible to build the app anymore. I've been looking for specific snippets that could have had impacted the build but nothing solves the issue.

The rollup code impacted is
```js
            const colonPos = findFirstOccurrenceOutsideComment(code.original, ':', this.consequent.end);
            const inclusionStart = findNonWhiteSpace(code.original, (this.consequent.included
                ? findFirstOccurrenceOutsideComment(code.original, '?', this.test.end)
                : colonPos) + 1);
            if (preventASI) {
                removeLineBreaks(code, inclusionStart, usedBranch.start);
            }
```

`usedBranch` is `null`

### Actual Behaviour

```
PWA v0.21.0
mode      generateSW
precache  19 entries (1105.59 KiB)
files generated
  dist/sw.js
  dist/workbox-1c98a0cb.js
error during build:
Cannot read properties of null (reading 'start')
    at ConditionalExpression.render (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:11924:67)
    at ReturnStatement.render (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:13850:27)
    at renderStatementList (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:1851:25)
    at BlockStatement.render (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:6341:13)
    at FunctionDeclaration.render (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:2822:23)
    at renderStatementList (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:1851:25)
    at Program.render (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:13717:13)
    at Module.render (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:16291:18)
    at Chunk.renderModules (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:18039:41)
    at Chunk.render (file:///aresrpg/aresrpg-dapp/node_modules/rollup/dist/es/shared/node-entry.js:17528:111)
```

**Comment by lukastaegert** [comment]
I tried your reproduction but it does not fail for me. Do I need to change anything?

**Comment by Sceat** [comment]
This commit fixed it, and I truly have no idea even why https://github.com/aresrpg/aresrpg-dapp/commit/dbeca00309e4b1ce021a85c2ee053a4f3da8fd49

If you revert before that, it should fail 

Vercel was failing too
![image](https://github.com/user-attachments/assets/e22d97f4-5c51-4005-b45f-68a40d380aa8)

**Comment by Sceat** [comment]
Actually the package lock seem to gave picked up rollup 4.27.3

**Comment by Sceat** [comment]
I couldn't reproduce it so I went back and restored the failing branch, this PR https://github.com/aresrpg/aresrpg-dapp/pull/165 still fails for me

**Comment by lukastaegert** [comment]
Still not failing. I wonder what it could be. What is the exact Node version you are using? On what OS is it failing?

**Comment by lukastaegert** [comment]
I did, and I am using `npm ci` for installation. Also on a Mac. Weird.

**Comment by TrickyPi** [comment]
I didn't encounter this issue on the `feat/use_items` branch either. Using Node.js 23.2 on a Mac M1 Pro.

**Comment by TrickyPi** [comment]
Can you check which version of `@rollup/rollup-darwin-arm64` is in your `node_modules` by running `npm list @rollup/rollup-darwin-arm64` locally?

**Comment by TrickyPi** [comment]
Alright, it's too weird.

**Comment by lukastaegert** [comment]
Can you habe a look if rollup@4.29.0-0 has this issue?

**Comment by Sceat** [comment]
I haven't experienced any issue anymore, we could close it until it potentially happen again?

**Comment by Sceat** [comment]
I'm using vite so I added to the package.json

```
  "overrides": {
    "rollup": "4.29.0-0"
  },
```

it then fails

```
✓ 1411 modules transformed.
x Build failed in 4.18s
error during build:
[vite-plugin-pwa:build] Cannot add property 0, object is not extensible
file: /Users/sceat/dev/aresrpg/aresrpg-dapp/src/core/utils/terrain/world_compute_worker.js?url&worker
    at Array.push (<anonymous>)
```

but that's probably because of those plugins relying on different versions

**Comment by lukastaegert** [comment]
That is an issue in rollup@4.29.0-0. Can you try again with rollup@4.29.0-2?
