### ISSUE TITLE
On Travis CI build fails with `Error: Could not load null: path must be a string`

### ISSUE THREAD

**Issue by zebMcCorkle** [rollup/rollup#727]
This error only happens when the build is run in Travis CI. On my local system it works perfectly.

Error:

```
Error: Could not load null: path must be a string
    at /home/travis/build/zebMcCorkle/live-portfolio-framework/node_modules/rollup/dist/rollup.js:7320:10
    at process._tickCallback (node.js:369:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

Here's my build script:

```js
const path = require('path');
const fs = require('fs');

const rollup = require('rollup').rollup;
const babel = require('rollup-plugin-babel');

rollup({
    entry: path.join(__dirname, 'src', 'index.js'),
    plugins: [
        babel({
            exclude: 'node_modules/**'
        })
    ]
}).then(function (bundle) {
    return bundle.write({
        format: 'cjs',
        dest: path.join(__dirname, 'index.js')
    });
}).then(function () {
    return new Promise(function (resolve, reject) {
        fs.readFile(path.join(__dirname, 'index.js'), (err, contents) => {
            if (err != null) {
                reject(err);
            } else {
                resolve(contents);
            }
        });
    });
}).then(function (contents) {
    console.log('Good. index.js written to ' + path.join(__dirname, 'index.js'));
}).catch(function (error) {
    console.error('Oh, no! index.js not written to ' + path.join(__dirname, 'index.js') + ', error is ' + error.stack);
});
```

The build also failed with this command line:

```sh
rollup src/index.js -o index.es6.js -f es6 -m inline && babel index.es6.js -o index.js --presets es2015 --source-maps inline
```

Node version:

```
$ node --version
v4.4.5
```

**Comment by zebMcCorkle** [comment]
Never mind, I forgot to check `index.js` into `git`.
