### ISSUE TITLE
Issue with babel-preset-es2015 > 6.13.0

### ISSUE THREAD

**Issue by bhoriuchi** [rollup/rollup#829]
I am currently getting the following error when babel-preset-es2015 greater than 6.13.0 (6.13.1 and .2 as of this issue) is is installed

if i roll back to 6.13.0 or lower everything builds w/o issue

```
Error transforming /***/src/index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
Error: Error transforming /***/src/index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (/***/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:43:102)
    at Object.transform$1 [as transform] (/***/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:104:18)
    at /***/node_modules/rollup/src/utils/transform.js:13:35
    at process._tickCallback (node.js:368:9)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
```

Rollup config

```js
import babel from 'rollup-plugin-babel';

export default {
  entry: 'src/index.js',
  format: 'cjs',
  plugins: [ babel() ],
  dest: 'index.js'
}
```

.babelrc (located in src directory)

```
{
  "presets": ["es2015-rollup"]
}
```

build command

```
rollup -c build/rollup.config.js
```

rollup and babel deps installed

```js
{
    "babel-core": "^6.0.0",
    "babel-preset-es2015": "6.13.2", // causes failure .1 or .2
    "babel-preset-stage-2": "^6.0.0",
    "babel-register": "^6.11.0",
    "babel-runtime": "^6.9.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "rollup": "^0.34.0",
    "rollup-plugin-babel": "^2.6.0",
    "babel-preset-es2015-rollup": "^1.1.0"
}
```

**Comment by TrySound** [comment]
It's not rollup itself issue. Please reopen it in https://github.com/rollup/rollup-plugin-babel
