### ISSUE TITLE
Using Rollup with Babel guide not working on Windows 10

### ISSUE THREAD

**Issue by moose56** [rollup/rollup#868]
Hi,

I have followed this [guide](http://rollupjs.org/guide/#using-rollup-with-babel) through on a Windows 10 machine as well as Mac and Linux machines. Both the Mac and Linux machines work as described by the guide, but on the Windows machine I get the following error:

```
Error transforming C:\Testing\rollup_guide\src\main.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.co
m/rollup/rollup-plugin-babel#configuring-babel for more information
Error: Error transforming C:\Testing\rollup_guide\src\main.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://gi
thub.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (C:\Testing\rollup_guide\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:45:102)
    at Object.transform$1 [as transform] (C:\Testing\rollup_guide\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:106:18)
    at C:\Users\david.madden\AppData\Roaming\npm\node_modules\rollup\src\utils\transform.js:19:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

Looking into I can see that the code that is being generated in C:\Testing\rollup_guide\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js from this line:

```javascript
var check = babelCore.transform( 'export default class Foo {}', options ).code;
```
 on Windows is:
```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var Foo = function Foo() {
  babelHelpers.classCallCheck(this, Foo);
};

exports.default = Foo;`
```
And on a Linux is:

```javascript
var Foo = function Foo() {
  babelHelpers.classCallCheck(this, Foo);
};

export default Foo;
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

let Foo = function Foo() {
  _classCallCheck(this, Foo);
};

export default Foo;
```

As this different behavior is being generated from copies of the same files I am not sure where the difference is coming from. I have checked the versions of node/npm/modules and they are the same on all platforms.

Any pointers greatly received.

**Comment by moose56** [comment]
It looks like the problem may be in the babel-preset-es2015-rollup module rather than rollup itself as after changing the .babelrc file from

```javascript
{
  "presets": ["es2015-rollup"]
}
```
to
```javascript
{
  "plugins": ["external-helpers"],
  "presets": [
    ["es2015", { "modules": false }]
  ]
}
```
Which effectively replicates what this module is doing it works on Windows.

**Comment by moose56** [comment]
Finally after a lot of digging the issue is actually in [modify-babel-preset](https://github.com/developit/modify-babel-preset).

I will close this issue now.
