### ISSUE TITLE
cannot depend on cjs module with an `arguments.js` file

### ISSUE THREAD

**Issue by KenanY** [rollup/rollup#871]
Test repository: https://github.com/KenanY/rollup-arguments-bug

``` shell
$ git clone https://github.com/KenanY/rollup-arguments-bug.git
$ cd rollup-arguments-bug/
$ npm install

# with CLI
$ npm run build

> @ build /tmp/rollup-arguments
> rollup -c -o bundle.js

Error parsing /tmp/rollup-arguments/node_modules/my-module/arguments.js: Binding arguments in strict mode (3:4) in /tmp/rollup-arguments/node_modules/my-module/arguments.js
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki

# with js api
$ node rollup.js 
{ SyntaxError: Binding arguments in strict mode (3:4) in /tmp/rollup-arguments/node_modules/my-module/arguments.js
    at Parser.pp$4.raise (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:3813:13)
    at Parser.pp$2.checkLVal (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:3050:12)
    at Parser.pp$1.parseVarId (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:2628:8)
    at Parser.pp$1.parseVar (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:2610:12)
    at Parser.pp$1.parseVarStatement (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:2495:8)
    at Parser.pp$1.parseStatement (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:2284:17)
    at Parser.pp$1.parseTopLevel (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:2216:23)
    at Parser.parse (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:2094:15)
    at parse (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:4713:37)
    at Module.parse$1 [as parse] (/tmp/rollup-arguments/node_modules/rollup/dist/rollup.js:6048:15)
  pos: 58,
  loc: Position { line: 3, column: 4 },
  raisedAt: 69,
  code: 'PARSE_ERROR',
  file: '/tmp/rollup-arguments/node_modules/my-module/arguments.js' }
```

Found this out when trying to make a bundle with [`feathers-commons`](https://github.com/feathersjs/feathers-commons) as a dependency. That module is written in ES6 but builds and publishes a cjs version before publish. This package has a file named `arguments.js` which apparently is not playing well with `rollup`. If this is an `acorn` issue or something feel free to let me know :)

Node.js v6.3.1, `npm@3.10.6`, `rollup@0.34.10`.

**Comment by Rich-Harris** [comment]
Thanks for the test case – tracked this down to https://github.com/rollup/rollup-pluginutils/issues/10, if you reinstall your dependencies everything should work

**Comment by KenanY** [comment]
@Rich-Harris Works like a charm, thanks so much!
