### ISSUE TITLE
process.hrtime() error in 0.35.6

### ISSUE THREAD

**Issue by veltman** [rollup/rollup#923]
Running v0.35.6 throws the following error in Node v4.5.0:

```
> rollup index.js
process.hrtime() only accepts an Array tuple.
TypeError: process.hrtime() only accepts an Array tuple.
    at TypeError (native)
    at time (/rollup-test/node_modules/rollup/src/utils/flushTime.js:13:26)
    at timeStart (/rollup-test/node_modules/rollup/src/utils/flushTime.js:26:27)
    at Object.rollup (/rollup-test/node_modules/rollup/src/rollup.js:58:2)
    at bundle (/rollup-test/node_modules/rollup/bin/rollup:905:16)
    at execute (/rollup-test/node_modules/rollup/bin/rollup:882:4)
    at runRollup (/rollup-test/node_modules/rollup/bin/rollup:780:3)
    at Object.<anonymous> (/rollup-test/node_modules/rollup/bin/rollup:967:2)
    at Module._compile (module.js:409:26)
```

The tests also fail.
 
Pretty sure the issue is in 55c23a3f, because the initial call to `process.hrtime()` behaves differently when passed a single undefined argument vs. no arguments as of v4.5.0.  Possible that the most recent Node versions make `hrtime()` a little less fickle but I assume this should stay working on LTS. Will send over a PR.

**Comment by Rich-Harris** [comment]
closing, fixed in 0.35.7
