### ISSUE TITLE
Did rollup drop support for Node 0.12?

### ISSUE THREAD

**Issue by markistaylor** [rollup/rollup#929]
Since `0.35.*` including `0.35.7` I have been getting these errors with Travis when it tries to build my project:

```
/home/travis/build/.../node_modules/rollup/dist/rollup.js:18
const DEBUG = false;
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/.../node_modules/rollup/bin/rollup:5:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by eventualbuddha** [comment]
Please update to [0.35.9](https://github.com/rollup/rollup/commit/a1478d744577c4cf1d94ab7da4e120f147f3141c), where 0.12 support was reinstated.
